
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import * as $Class from "./internal/class.ts"
import * as Prisma from "./internal/prismaNamespace.ts"

export * as $Enums from './enums.ts'
export * from "./enums.ts"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Bags
 * const bags = await prisma.bag.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Bag
 * 
 */
export type Bag = Prisma.BagModel
/**
 * Model BagPermission
 * 
 */
export type BagPermission = Prisma.BagPermissionModel
/**
 * Model Tiddler
 * 
 */
export type Tiddler = Prisma.TiddlerModel
/**
 * Model TiddlerEvent
 * 
 */
export type TiddlerEvent = Prisma.TiddlerEventModel
/**
 * Model Template
 * 
 */
export type Template = Prisma.TemplateModel
/**
 * Model TemplatePermission
 * 
 */
export type TemplatePermission = Prisma.TemplatePermissionModel
/**
 * Model Recipe
 * 
 */
export type Recipe = Prisma.RecipeModel
/**
 * Model RecipePermission
 * 
 */
export type RecipePermission = Prisma.RecipePermissionModel
/**
 * Model RecipeBag
 * 
 */
export type RecipeBag = Prisma.RecipeBagModel
/**
 * Model Settings
 * 
 */
export type Settings = Prisma.SettingsModel
/**
 * Model Roles
 * 
 */
export type Roles = Prisma.RolesModel
/**
 * Model Users
 * 
 */
export type Users = Prisma.UsersModel
/**
 * Model Sessions
 * 
 */
export type Sessions = Prisma.SessionsModel
/**
 * Model PinboardNote
 * 
 */
export type PinboardNote = Prisma.PinboardNoteModel
/**
 * Model PinboardNoteRead
 * 
 */
export type PinboardNoteRead = Prisma.PinboardNoteReadModel
/**
 * Model PinboardNotePosition
 * Where a single user has placed a note on the wall (the arrangement is
 * per-user, not shared). x/y are fractions (0..1) of the wall dimensions
 * describing the note's centre, snapped to the wall raster by the UI.
 */
export type PinboardNotePosition = Prisma.PinboardNotePositionModel
/**
 * Model UserFile
 * 
 */
export type UserFile = Prisma.UserFileModel
