
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Bag` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Bag
 * 
 */
export type BagModel = runtime.Types.Result.DefaultSelection<Prisma.$BagPayload>

export type AggregateBag = {
  _count: BagCountAggregateOutputType | null
  _min: BagMinAggregateOutputType | null
  _max: BagMaxAggregateOutputType | null
}

export type BagMinAggregateOutputType = {
  id: string | null
  name: string | null
  created: Date | null
  updated: Date | null
  description: string | null
  owner_user_id: string | null
}

export type BagMaxAggregateOutputType = {
  id: string | null
  name: string | null
  created: Date | null
  updated: Date | null
  description: string | null
  owner_user_id: string | null
}

export type BagCountAggregateOutputType = {
  id: number
  name: number
  created: number
  updated: number
  description: number
  owner_user_id: number
  _all: number
}


export type BagMinAggregateInputType = {
  id?: true
  name?: true
  created?: true
  updated?: true
  description?: true
  owner_user_id?: true
}

export type BagMaxAggregateInputType = {
  id?: true
  name?: true
  created?: true
  updated?: true
  description?: true
  owner_user_id?: true
}

export type BagCountAggregateInputType = {
  id?: true
  name?: true
  created?: true
  updated?: true
  description?: true
  owner_user_id?: true
  _all?: true
}

export type BagAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Bag to aggregate.
   */
  where?: Prisma.BagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bags to fetch.
   */
  orderBy?: Prisma.BagOrderByWithRelationInput | Prisma.BagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Bags
  **/
  _count?: true | BagCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BagMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BagMaxAggregateInputType
}

export type GetBagAggregateType<T extends BagAggregateArgs> = {
      [P in keyof T & keyof AggregateBag]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBag[P]>
    : Prisma.GetScalarType<T[P], AggregateBag[P]>
}




export type BagGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BagWhereInput
  orderBy?: Prisma.BagOrderByWithAggregationInput | Prisma.BagOrderByWithAggregationInput[]
  by: Prisma.BagScalarFieldEnum[] | Prisma.BagScalarFieldEnum
  having?: Prisma.BagScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BagCountAggregateInputType | true
  _min?: BagMinAggregateInputType
  _max?: BagMaxAggregateInputType
}

export type BagGroupByOutputType = {
  id: string
  name: string
  created: Date
  updated: Date
  description: string
  owner_user_id: string | null
  _count: BagCountAggregateOutputType | null
  _min: BagMinAggregateOutputType | null
  _max: BagMaxAggregateOutputType | null
}

export type GetBagGroupByPayload<T extends BagGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BagGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BagGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BagGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BagGroupByOutputType[P]>
      }
    >
  >



export type BagWhereInput = {
  AND?: Prisma.BagWhereInput | Prisma.BagWhereInput[]
  OR?: Prisma.BagWhereInput[]
  NOT?: Prisma.BagWhereInput | Prisma.BagWhereInput[]
  id?: Prisma.StringFilter<"Bag"> | string
  name?: Prisma.StringFilter<"Bag"> | string
  created?: Prisma.DateTimeFilter<"Bag"> | Date | string
  updated?: Prisma.DateTimeFilter<"Bag"> | Date | string
  description?: Prisma.StringFilter<"Bag"> | string
  owner_user_id?: Prisma.StringNullableFilter<"Bag"> | string | null
  permissions?: Prisma.BagPermissionListRelationFilter
  tiddlers?: Prisma.TiddlerListRelationFilter
  recipe_bags?: Prisma.RecipeBagListRelationFilter
  tiddler_events?: Prisma.TiddlerEventListRelationFilter
}

export type BagOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  permissions?: Prisma.BagPermissionOrderByRelationAggregateInput
  tiddlers?: Prisma.TiddlerOrderByRelationAggregateInput
  recipe_bags?: Prisma.RecipeBagOrderByRelationAggregateInput
  tiddler_events?: Prisma.TiddlerEventOrderByRelationAggregateInput
}

export type BagWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.BagWhereInput | Prisma.BagWhereInput[]
  OR?: Prisma.BagWhereInput[]
  NOT?: Prisma.BagWhereInput | Prisma.BagWhereInput[]
  created?: Prisma.DateTimeFilter<"Bag"> | Date | string
  updated?: Prisma.DateTimeFilter<"Bag"> | Date | string
  description?: Prisma.StringFilter<"Bag"> | string
  owner_user_id?: Prisma.StringNullableFilter<"Bag"> | string | null
  permissions?: Prisma.BagPermissionListRelationFilter
  tiddlers?: Prisma.TiddlerListRelationFilter
  recipe_bags?: Prisma.RecipeBagListRelationFilter
  tiddler_events?: Prisma.TiddlerEventListRelationFilter
}, "id" | "name">

export type BagOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.BagCountOrderByAggregateInput
  _max?: Prisma.BagMaxOrderByAggregateInput
  _min?: Prisma.BagMinOrderByAggregateInput
}

export type BagScalarWhereWithAggregatesInput = {
  AND?: Prisma.BagScalarWhereWithAggregatesInput | Prisma.BagScalarWhereWithAggregatesInput[]
  OR?: Prisma.BagScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BagScalarWhereWithAggregatesInput | Prisma.BagScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Bag"> | string
  name?: Prisma.StringWithAggregatesFilter<"Bag"> | string
  created?: Prisma.DateTimeWithAggregatesFilter<"Bag"> | Date | string
  updated?: Prisma.DateTimeWithAggregatesFilter<"Bag"> | Date | string
  description?: Prisma.StringWithAggregatesFilter<"Bag"> | string
  owner_user_id?: Prisma.StringNullableWithAggregatesFilter<"Bag"> | string | null
}

export type BagCreateInput = {
  id?: string
  name: string
  created?: Date | string
  updated?: Date | string
  description: string
  owner_user_id?: string | null
  permissions?: Prisma.BagPermissionCreateNestedManyWithoutBagInput
  tiddlers?: Prisma.TiddlerCreateNestedManyWithoutBagInput
  recipe_bags?: Prisma.RecipeBagCreateNestedManyWithoutBagInput
  tiddler_events?: Prisma.TiddlerEventCreateNestedManyWithoutBagInput
}

export type BagUncheckedCreateInput = {
  id?: string
  name: string
  created?: Date | string
  updated?: Date | string
  description: string
  owner_user_id?: string | null
  permissions?: Prisma.BagPermissionUncheckedCreateNestedManyWithoutBagInput
  tiddlers?: Prisma.TiddlerUncheckedCreateNestedManyWithoutBagInput
  recipe_bags?: Prisma.RecipeBagUncheckedCreateNestedManyWithoutBagInput
  tiddler_events?: Prisma.TiddlerEventUncheckedCreateNestedManyWithoutBagInput
}

export type BagUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.BagPermissionUpdateManyWithoutBagNestedInput
  tiddlers?: Prisma.TiddlerUpdateManyWithoutBagNestedInput
  recipe_bags?: Prisma.RecipeBagUpdateManyWithoutBagNestedInput
  tiddler_events?: Prisma.TiddlerEventUpdateManyWithoutBagNestedInput
}

export type BagUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.BagPermissionUncheckedUpdateManyWithoutBagNestedInput
  tiddlers?: Prisma.TiddlerUncheckedUpdateManyWithoutBagNestedInput
  recipe_bags?: Prisma.RecipeBagUncheckedUpdateManyWithoutBagNestedInput
  tiddler_events?: Prisma.TiddlerEventUncheckedUpdateManyWithoutBagNestedInput
}

export type BagCreateManyInput = {
  id?: string
  name: string
  created?: Date | string
  updated?: Date | string
  description: string
  owner_user_id?: string | null
}

export type BagUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BagUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type BagCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrder
}

export type BagMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrder
}

export type BagMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  description?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrder
}

export type BagScalarRelationFilter = {
  is?: Prisma.BagWhereInput
  isNot?: Prisma.BagWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type BagCreateNestedOneWithoutPermissionsInput = {
  create?: Prisma.XOR<Prisma.BagCreateWithoutPermissionsInput, Prisma.BagUncheckedCreateWithoutPermissionsInput>
  connectOrCreate?: Prisma.BagCreateOrConnectWithoutPermissionsInput
  connect?: Prisma.BagWhereUniqueInput
}

export type BagUpdateOneRequiredWithoutPermissionsNestedInput = {
  create?: Prisma.XOR<Prisma.BagCreateWithoutPermissionsInput, Prisma.BagUncheckedCreateWithoutPermissionsInput>
  connectOrCreate?: Prisma.BagCreateOrConnectWithoutPermissionsInput
  upsert?: Prisma.BagUpsertWithoutPermissionsInput
  connect?: Prisma.BagWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BagUpdateToOneWithWhereWithoutPermissionsInput, Prisma.BagUpdateWithoutPermissionsInput>, Prisma.BagUncheckedUpdateWithoutPermissionsInput>
}

export type BagCreateNestedOneWithoutTiddlersInput = {
  create?: Prisma.XOR<Prisma.BagCreateWithoutTiddlersInput, Prisma.BagUncheckedCreateWithoutTiddlersInput>
  connectOrCreate?: Prisma.BagCreateOrConnectWithoutTiddlersInput
  connect?: Prisma.BagWhereUniqueInput
}

export type BagUpdateOneRequiredWithoutTiddlersNestedInput = {
  create?: Prisma.XOR<Prisma.BagCreateWithoutTiddlersInput, Prisma.BagUncheckedCreateWithoutTiddlersInput>
  connectOrCreate?: Prisma.BagCreateOrConnectWithoutTiddlersInput
  upsert?: Prisma.BagUpsertWithoutTiddlersInput
  connect?: Prisma.BagWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BagUpdateToOneWithWhereWithoutTiddlersInput, Prisma.BagUpdateWithoutTiddlersInput>, Prisma.BagUncheckedUpdateWithoutTiddlersInput>
}

export type BagCreateNestedOneWithoutTiddler_eventsInput = {
  create?: Prisma.XOR<Prisma.BagCreateWithoutTiddler_eventsInput, Prisma.BagUncheckedCreateWithoutTiddler_eventsInput>
  connectOrCreate?: Prisma.BagCreateOrConnectWithoutTiddler_eventsInput
  connect?: Prisma.BagWhereUniqueInput
}

export type BagUpdateOneRequiredWithoutTiddler_eventsNestedInput = {
  create?: Prisma.XOR<Prisma.BagCreateWithoutTiddler_eventsInput, Prisma.BagUncheckedCreateWithoutTiddler_eventsInput>
  connectOrCreate?: Prisma.BagCreateOrConnectWithoutTiddler_eventsInput
  upsert?: Prisma.BagUpsertWithoutTiddler_eventsInput
  connect?: Prisma.BagWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BagUpdateToOneWithWhereWithoutTiddler_eventsInput, Prisma.BagUpdateWithoutTiddler_eventsInput>, Prisma.BagUncheckedUpdateWithoutTiddler_eventsInput>
}

export type BagCreateNestedOneWithoutRecipe_bagsInput = {
  create?: Prisma.XOR<Prisma.BagCreateWithoutRecipe_bagsInput, Prisma.BagUncheckedCreateWithoutRecipe_bagsInput>
  connectOrCreate?: Prisma.BagCreateOrConnectWithoutRecipe_bagsInput
  connect?: Prisma.BagWhereUniqueInput
}

export type BagUpdateOneRequiredWithoutRecipe_bagsNestedInput = {
  create?: Prisma.XOR<Prisma.BagCreateWithoutRecipe_bagsInput, Prisma.BagUncheckedCreateWithoutRecipe_bagsInput>
  connectOrCreate?: Prisma.BagCreateOrConnectWithoutRecipe_bagsInput
  upsert?: Prisma.BagUpsertWithoutRecipe_bagsInput
  connect?: Prisma.BagWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BagUpdateToOneWithWhereWithoutRecipe_bagsInput, Prisma.BagUpdateWithoutRecipe_bagsInput>, Prisma.BagUncheckedUpdateWithoutRecipe_bagsInput>
}

export type BagCreateWithoutPermissionsInput = {
  id?: string
  name: string
  created?: Date | string
  updated?: Date | string
  description: string
  owner_user_id?: string | null
  tiddlers?: Prisma.TiddlerCreateNestedManyWithoutBagInput
  recipe_bags?: Prisma.RecipeBagCreateNestedManyWithoutBagInput
  tiddler_events?: Prisma.TiddlerEventCreateNestedManyWithoutBagInput
}

export type BagUncheckedCreateWithoutPermissionsInput = {
  id?: string
  name: string
  created?: Date | string
  updated?: Date | string
  description: string
  owner_user_id?: string | null
  tiddlers?: Prisma.TiddlerUncheckedCreateNestedManyWithoutBagInput
  recipe_bags?: Prisma.RecipeBagUncheckedCreateNestedManyWithoutBagInput
  tiddler_events?: Prisma.TiddlerEventUncheckedCreateNestedManyWithoutBagInput
}

export type BagCreateOrConnectWithoutPermissionsInput = {
  where: Prisma.BagWhereUniqueInput
  create: Prisma.XOR<Prisma.BagCreateWithoutPermissionsInput, Prisma.BagUncheckedCreateWithoutPermissionsInput>
}

export type BagUpsertWithoutPermissionsInput = {
  update: Prisma.XOR<Prisma.BagUpdateWithoutPermissionsInput, Prisma.BagUncheckedUpdateWithoutPermissionsInput>
  create: Prisma.XOR<Prisma.BagCreateWithoutPermissionsInput, Prisma.BagUncheckedCreateWithoutPermissionsInput>
  where?: Prisma.BagWhereInput
}

export type BagUpdateToOneWithWhereWithoutPermissionsInput = {
  where?: Prisma.BagWhereInput
  data: Prisma.XOR<Prisma.BagUpdateWithoutPermissionsInput, Prisma.BagUncheckedUpdateWithoutPermissionsInput>
}

export type BagUpdateWithoutPermissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiddlers?: Prisma.TiddlerUpdateManyWithoutBagNestedInput
  recipe_bags?: Prisma.RecipeBagUpdateManyWithoutBagNestedInput
  tiddler_events?: Prisma.TiddlerEventUpdateManyWithoutBagNestedInput
}

export type BagUncheckedUpdateWithoutPermissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tiddlers?: Prisma.TiddlerUncheckedUpdateManyWithoutBagNestedInput
  recipe_bags?: Prisma.RecipeBagUncheckedUpdateManyWithoutBagNestedInput
  tiddler_events?: Prisma.TiddlerEventUncheckedUpdateManyWithoutBagNestedInput
}

export type BagCreateWithoutTiddlersInput = {
  id?: string
  name: string
  created?: Date | string
  updated?: Date | string
  description: string
  owner_user_id?: string | null
  permissions?: Prisma.BagPermissionCreateNestedManyWithoutBagInput
  recipe_bags?: Prisma.RecipeBagCreateNestedManyWithoutBagInput
  tiddler_events?: Prisma.TiddlerEventCreateNestedManyWithoutBagInput
}

export type BagUncheckedCreateWithoutTiddlersInput = {
  id?: string
  name: string
  created?: Date | string
  updated?: Date | string
  description: string
  owner_user_id?: string | null
  permissions?: Prisma.BagPermissionUncheckedCreateNestedManyWithoutBagInput
  recipe_bags?: Prisma.RecipeBagUncheckedCreateNestedManyWithoutBagInput
  tiddler_events?: Prisma.TiddlerEventUncheckedCreateNestedManyWithoutBagInput
}

export type BagCreateOrConnectWithoutTiddlersInput = {
  where: Prisma.BagWhereUniqueInput
  create: Prisma.XOR<Prisma.BagCreateWithoutTiddlersInput, Prisma.BagUncheckedCreateWithoutTiddlersInput>
}

export type BagUpsertWithoutTiddlersInput = {
  update: Prisma.XOR<Prisma.BagUpdateWithoutTiddlersInput, Prisma.BagUncheckedUpdateWithoutTiddlersInput>
  create: Prisma.XOR<Prisma.BagCreateWithoutTiddlersInput, Prisma.BagUncheckedCreateWithoutTiddlersInput>
  where?: Prisma.BagWhereInput
}

export type BagUpdateToOneWithWhereWithoutTiddlersInput = {
  where?: Prisma.BagWhereInput
  data: Prisma.XOR<Prisma.BagUpdateWithoutTiddlersInput, Prisma.BagUncheckedUpdateWithoutTiddlersInput>
}

export type BagUpdateWithoutTiddlersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.BagPermissionUpdateManyWithoutBagNestedInput
  recipe_bags?: Prisma.RecipeBagUpdateManyWithoutBagNestedInput
  tiddler_events?: Prisma.TiddlerEventUpdateManyWithoutBagNestedInput
}

export type BagUncheckedUpdateWithoutTiddlersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.BagPermissionUncheckedUpdateManyWithoutBagNestedInput
  recipe_bags?: Prisma.RecipeBagUncheckedUpdateManyWithoutBagNestedInput
  tiddler_events?: Prisma.TiddlerEventUncheckedUpdateManyWithoutBagNestedInput
}

export type BagCreateWithoutTiddler_eventsInput = {
  id?: string
  name: string
  created?: Date | string
  updated?: Date | string
  description: string
  owner_user_id?: string | null
  permissions?: Prisma.BagPermissionCreateNestedManyWithoutBagInput
  tiddlers?: Prisma.TiddlerCreateNestedManyWithoutBagInput
  recipe_bags?: Prisma.RecipeBagCreateNestedManyWithoutBagInput
}

export type BagUncheckedCreateWithoutTiddler_eventsInput = {
  id?: string
  name: string
  created?: Date | string
  updated?: Date | string
  description: string
  owner_user_id?: string | null
  permissions?: Prisma.BagPermissionUncheckedCreateNestedManyWithoutBagInput
  tiddlers?: Prisma.TiddlerUncheckedCreateNestedManyWithoutBagInput
  recipe_bags?: Prisma.RecipeBagUncheckedCreateNestedManyWithoutBagInput
}

export type BagCreateOrConnectWithoutTiddler_eventsInput = {
  where: Prisma.BagWhereUniqueInput
  create: Prisma.XOR<Prisma.BagCreateWithoutTiddler_eventsInput, Prisma.BagUncheckedCreateWithoutTiddler_eventsInput>
}

export type BagUpsertWithoutTiddler_eventsInput = {
  update: Prisma.XOR<Prisma.BagUpdateWithoutTiddler_eventsInput, Prisma.BagUncheckedUpdateWithoutTiddler_eventsInput>
  create: Prisma.XOR<Prisma.BagCreateWithoutTiddler_eventsInput, Prisma.BagUncheckedCreateWithoutTiddler_eventsInput>
  where?: Prisma.BagWhereInput
}

export type BagUpdateToOneWithWhereWithoutTiddler_eventsInput = {
  where?: Prisma.BagWhereInput
  data: Prisma.XOR<Prisma.BagUpdateWithoutTiddler_eventsInput, Prisma.BagUncheckedUpdateWithoutTiddler_eventsInput>
}

export type BagUpdateWithoutTiddler_eventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.BagPermissionUpdateManyWithoutBagNestedInput
  tiddlers?: Prisma.TiddlerUpdateManyWithoutBagNestedInput
  recipe_bags?: Prisma.RecipeBagUpdateManyWithoutBagNestedInput
}

export type BagUncheckedUpdateWithoutTiddler_eventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.BagPermissionUncheckedUpdateManyWithoutBagNestedInput
  tiddlers?: Prisma.TiddlerUncheckedUpdateManyWithoutBagNestedInput
  recipe_bags?: Prisma.RecipeBagUncheckedUpdateManyWithoutBagNestedInput
}

export type BagCreateWithoutRecipe_bagsInput = {
  id?: string
  name: string
  created?: Date | string
  updated?: Date | string
  description: string
  owner_user_id?: string | null
  permissions?: Prisma.BagPermissionCreateNestedManyWithoutBagInput
  tiddlers?: Prisma.TiddlerCreateNestedManyWithoutBagInput
  tiddler_events?: Prisma.TiddlerEventCreateNestedManyWithoutBagInput
}

export type BagUncheckedCreateWithoutRecipe_bagsInput = {
  id?: string
  name: string
  created?: Date | string
  updated?: Date | string
  description: string
  owner_user_id?: string | null
  permissions?: Prisma.BagPermissionUncheckedCreateNestedManyWithoutBagInput
  tiddlers?: Prisma.TiddlerUncheckedCreateNestedManyWithoutBagInput
  tiddler_events?: Prisma.TiddlerEventUncheckedCreateNestedManyWithoutBagInput
}

export type BagCreateOrConnectWithoutRecipe_bagsInput = {
  where: Prisma.BagWhereUniqueInput
  create: Prisma.XOR<Prisma.BagCreateWithoutRecipe_bagsInput, Prisma.BagUncheckedCreateWithoutRecipe_bagsInput>
}

export type BagUpsertWithoutRecipe_bagsInput = {
  update: Prisma.XOR<Prisma.BagUpdateWithoutRecipe_bagsInput, Prisma.BagUncheckedUpdateWithoutRecipe_bagsInput>
  create: Prisma.XOR<Prisma.BagCreateWithoutRecipe_bagsInput, Prisma.BagUncheckedCreateWithoutRecipe_bagsInput>
  where?: Prisma.BagWhereInput
}

export type BagUpdateToOneWithWhereWithoutRecipe_bagsInput = {
  where?: Prisma.BagWhereInput
  data: Prisma.XOR<Prisma.BagUpdateWithoutRecipe_bagsInput, Prisma.BagUncheckedUpdateWithoutRecipe_bagsInput>
}

export type BagUpdateWithoutRecipe_bagsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.BagPermissionUpdateManyWithoutBagNestedInput
  tiddlers?: Prisma.TiddlerUpdateManyWithoutBagNestedInput
  tiddler_events?: Prisma.TiddlerEventUpdateManyWithoutBagNestedInput
}

export type BagUncheckedUpdateWithoutRecipe_bagsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  permissions?: Prisma.BagPermissionUncheckedUpdateManyWithoutBagNestedInput
  tiddlers?: Prisma.TiddlerUncheckedUpdateManyWithoutBagNestedInput
  tiddler_events?: Prisma.TiddlerEventUncheckedUpdateManyWithoutBagNestedInput
}


/**
 * Count Type BagCountOutputType
 */

export type BagCountOutputType = {
  permissions: number
  tiddlers: number
  recipe_bags: number
  tiddler_events: number
}

export type BagCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  permissions?: boolean | BagCountOutputTypeCountPermissionsArgs
  tiddlers?: boolean | BagCountOutputTypeCountTiddlersArgs
  recipe_bags?: boolean | BagCountOutputTypeCountRecipe_bagsArgs
  tiddler_events?: boolean | BagCountOutputTypeCountTiddler_eventsArgs
}

/**
 * BagCountOutputType without action
 */
export type BagCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagCountOutputType
   */
  select?: Prisma.BagCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BagCountOutputType without action
 */
export type BagCountOutputTypeCountPermissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BagPermissionWhereInput
}

/**
 * BagCountOutputType without action
 */
export type BagCountOutputTypeCountTiddlersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TiddlerWhereInput
}

/**
 * BagCountOutputType without action
 */
export type BagCountOutputTypeCountRecipe_bagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipeBagWhereInput
}

/**
 * BagCountOutputType without action
 */
export type BagCountOutputTypeCountTiddler_eventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TiddlerEventWhereInput
}


export type BagSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  created?: boolean
  updated?: boolean
  description?: boolean
  owner_user_id?: boolean
  permissions?: boolean | Prisma.Bag$permissionsArgs<ExtArgs>
  tiddlers?: boolean | Prisma.Bag$tiddlersArgs<ExtArgs>
  recipe_bags?: boolean | Prisma.Bag$recipe_bagsArgs<ExtArgs>
  tiddler_events?: boolean | Prisma.Bag$tiddler_eventsArgs<ExtArgs>
  _count?: boolean | Prisma.BagCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bag"]>

export type BagSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  created?: boolean
  updated?: boolean
  description?: boolean
  owner_user_id?: boolean
}, ExtArgs["result"]["bag"]>

export type BagSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  created?: boolean
  updated?: boolean
  description?: boolean
  owner_user_id?: boolean
}, ExtArgs["result"]["bag"]>

export type BagSelectScalar = {
  id?: boolean
  name?: boolean
  created?: boolean
  updated?: boolean
  description?: boolean
  owner_user_id?: boolean
}

export type BagOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "created" | "updated" | "description" | "owner_user_id", ExtArgs["result"]["bag"]>
export type BagInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  permissions?: boolean | Prisma.Bag$permissionsArgs<ExtArgs>
  tiddlers?: boolean | Prisma.Bag$tiddlersArgs<ExtArgs>
  recipe_bags?: boolean | Prisma.Bag$recipe_bagsArgs<ExtArgs>
  tiddler_events?: boolean | Prisma.Bag$tiddler_eventsArgs<ExtArgs>
  _count?: boolean | Prisma.BagCountOutputTypeDefaultArgs<ExtArgs>
}
export type BagIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type BagIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $BagPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Bag"
  objects: {
    permissions: Prisma.$BagPermissionPayload<ExtArgs>[]
    tiddlers: Prisma.$TiddlerPayload<ExtArgs>[]
    recipe_bags: Prisma.$RecipeBagPayload<ExtArgs>[]
    tiddler_events: Prisma.$TiddlerEventPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    created: Date
    updated: Date
    description: string
    /**
     * user_id of the user who created this bag; editable only by the
     * owner or the site admin account ("admin"). No FK (auth module).
     */
    owner_user_id: string | null
  }, ExtArgs["result"]["bag"]>
  composites: {}
}

export type BagGetPayload<S extends boolean | null | undefined | BagDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BagPayload, S>

export type BagCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BagFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BagCountAggregateInputType | true
  }

export interface BagDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Bag'], meta: { name: 'Bag' } }
  /**
   * Find zero or one Bag that matches the filter.
   * @param {BagFindUniqueArgs} args - Arguments to find a Bag
   * @example
   * // Get one Bag
   * const bag = await prisma.bag.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BagFindUniqueArgs>(args: Prisma.SelectSubset<T, BagFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BagClient<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Bag that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BagFindUniqueOrThrowArgs} args - Arguments to find a Bag
   * @example
   * // Get one Bag
   * const bag = await prisma.bag.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BagFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BagFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BagClient<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Bag that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagFindFirstArgs} args - Arguments to find a Bag
   * @example
   * // Get one Bag
   * const bag = await prisma.bag.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BagFindFirstArgs>(args?: Prisma.SelectSubset<T, BagFindFirstArgs<ExtArgs>>): Prisma.Prisma__BagClient<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Bag that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagFindFirstOrThrowArgs} args - Arguments to find a Bag
   * @example
   * // Get one Bag
   * const bag = await prisma.bag.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BagFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BagFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BagClient<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Bags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Bags
   * const bags = await prisma.bag.findMany()
   * 
   * // Get first 10 Bags
   * const bags = await prisma.bag.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const bagWithIdOnly = await prisma.bag.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BagFindManyArgs>(args?: Prisma.SelectSubset<T, BagFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Bag.
   * @param {BagCreateArgs} args - Arguments to create a Bag.
   * @example
   * // Create one Bag
   * const Bag = await prisma.bag.create({
   *   data: {
   *     // ... data to create a Bag
   *   }
   * })
   * 
   */
  create<T extends BagCreateArgs>(args: Prisma.SelectSubset<T, BagCreateArgs<ExtArgs>>): Prisma.Prisma__BagClient<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Bags.
   * @param {BagCreateManyArgs} args - Arguments to create many Bags.
   * @example
   * // Create many Bags
   * const bag = await prisma.bag.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BagCreateManyArgs>(args?: Prisma.SelectSubset<T, BagCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Bags and returns the data saved in the database.
   * @param {BagCreateManyAndReturnArgs} args - Arguments to create many Bags.
   * @example
   * // Create many Bags
   * const bag = await prisma.bag.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Bags and only return the `id`
   * const bagWithIdOnly = await prisma.bag.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BagCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BagCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Bag.
   * @param {BagDeleteArgs} args - Arguments to delete one Bag.
   * @example
   * // Delete one Bag
   * const Bag = await prisma.bag.delete({
   *   where: {
   *     // ... filter to delete one Bag
   *   }
   * })
   * 
   */
  delete<T extends BagDeleteArgs>(args: Prisma.SelectSubset<T, BagDeleteArgs<ExtArgs>>): Prisma.Prisma__BagClient<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Bag.
   * @param {BagUpdateArgs} args - Arguments to update one Bag.
   * @example
   * // Update one Bag
   * const bag = await prisma.bag.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BagUpdateArgs>(args: Prisma.SelectSubset<T, BagUpdateArgs<ExtArgs>>): Prisma.Prisma__BagClient<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Bags.
   * @param {BagDeleteManyArgs} args - Arguments to filter Bags to delete.
   * @example
   * // Delete a few Bags
   * const { count } = await prisma.bag.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BagDeleteManyArgs>(args?: Prisma.SelectSubset<T, BagDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Bags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Bags
   * const bag = await prisma.bag.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BagUpdateManyArgs>(args: Prisma.SelectSubset<T, BagUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Bags and returns the data updated in the database.
   * @param {BagUpdateManyAndReturnArgs} args - Arguments to update many Bags.
   * @example
   * // Update many Bags
   * const bag = await prisma.bag.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Bags and only return the `id`
   * const bagWithIdOnly = await prisma.bag.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BagUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BagUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Bag.
   * @param {BagUpsertArgs} args - Arguments to update or create a Bag.
   * @example
   * // Update or create a Bag
   * const bag = await prisma.bag.upsert({
   *   create: {
   *     // ... data to create a Bag
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Bag we want to update
   *   }
   * })
   */
  upsert<T extends BagUpsertArgs>(args: Prisma.SelectSubset<T, BagUpsertArgs<ExtArgs>>): Prisma.Prisma__BagClient<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Bags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagCountArgs} args - Arguments to filter Bags to count.
   * @example
   * // Count the number of Bags
   * const count = await prisma.bag.count({
   *   where: {
   *     // ... the filter for the Bags we want to count
   *   }
   * })
  **/
  count<T extends BagCountArgs>(
    args?: Prisma.Subset<T, BagCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BagCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Bag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BagAggregateArgs>(args: Prisma.Subset<T, BagAggregateArgs>): Prisma.PrismaPromise<GetBagAggregateType<T>>

  /**
   * Group by Bag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BagGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BagGroupByArgs['orderBy'] }
      : { orderBy?: BagGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BagGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBagGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Bag model
 */
readonly fields: BagFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Bag.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BagClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  permissions<T extends Prisma.Bag$permissionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Bag$permissionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BagPermissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  tiddlers<T extends Prisma.Bag$tiddlersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Bag$tiddlersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TiddlerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  recipe_bags<T extends Prisma.Bag$recipe_bagsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Bag$recipe_bagsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeBagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  tiddler_events<T extends Prisma.Bag$tiddler_eventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Bag$tiddler_eventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TiddlerEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Bag model
 */
export interface BagFieldRefs {
  readonly id: Prisma.FieldRef<"Bag", 'String'>
  readonly name: Prisma.FieldRef<"Bag", 'String'>
  readonly created: Prisma.FieldRef<"Bag", 'DateTime'>
  readonly updated: Prisma.FieldRef<"Bag", 'DateTime'>
  readonly description: Prisma.FieldRef<"Bag", 'String'>
  readonly owner_user_id: Prisma.FieldRef<"Bag", 'String'>
}
    

// Custom InputTypes
/**
 * Bag findUnique
 */
export type BagFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bag
   */
  select?: Prisma.BagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bag
   */
  omit?: Prisma.BagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagInclude<ExtArgs> | null
  /**
   * Filter, which Bag to fetch.
   */
  where: Prisma.BagWhereUniqueInput
}

/**
 * Bag findUniqueOrThrow
 */
export type BagFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bag
   */
  select?: Prisma.BagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bag
   */
  omit?: Prisma.BagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagInclude<ExtArgs> | null
  /**
   * Filter, which Bag to fetch.
   */
  where: Prisma.BagWhereUniqueInput
}

/**
 * Bag findFirst
 */
export type BagFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bag
   */
  select?: Prisma.BagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bag
   */
  omit?: Prisma.BagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagInclude<ExtArgs> | null
  /**
   * Filter, which Bag to fetch.
   */
  where?: Prisma.BagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bags to fetch.
   */
  orderBy?: Prisma.BagOrderByWithRelationInput | Prisma.BagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Bags.
   */
  cursor?: Prisma.BagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Bags.
   */
  distinct?: Prisma.BagScalarFieldEnum | Prisma.BagScalarFieldEnum[]
}

/**
 * Bag findFirstOrThrow
 */
export type BagFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bag
   */
  select?: Prisma.BagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bag
   */
  omit?: Prisma.BagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagInclude<ExtArgs> | null
  /**
   * Filter, which Bag to fetch.
   */
  where?: Prisma.BagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bags to fetch.
   */
  orderBy?: Prisma.BagOrderByWithRelationInput | Prisma.BagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Bags.
   */
  cursor?: Prisma.BagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Bags.
   */
  distinct?: Prisma.BagScalarFieldEnum | Prisma.BagScalarFieldEnum[]
}

/**
 * Bag findMany
 */
export type BagFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bag
   */
  select?: Prisma.BagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bag
   */
  omit?: Prisma.BagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagInclude<ExtArgs> | null
  /**
   * Filter, which Bags to fetch.
   */
  where?: Prisma.BagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bags to fetch.
   */
  orderBy?: Prisma.BagOrderByWithRelationInput | Prisma.BagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Bags.
   */
  cursor?: Prisma.BagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Bags.
   */
  distinct?: Prisma.BagScalarFieldEnum | Prisma.BagScalarFieldEnum[]
}

/**
 * Bag create
 */
export type BagCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bag
   */
  select?: Prisma.BagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bag
   */
  omit?: Prisma.BagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagInclude<ExtArgs> | null
  /**
   * The data needed to create a Bag.
   */
  data: Prisma.XOR<Prisma.BagCreateInput, Prisma.BagUncheckedCreateInput>
}

/**
 * Bag createMany
 */
export type BagCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Bags.
   */
  data: Prisma.BagCreateManyInput | Prisma.BagCreateManyInput[]
}

/**
 * Bag createManyAndReturn
 */
export type BagCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bag
   */
  select?: Prisma.BagSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Bag
   */
  omit?: Prisma.BagOmit<ExtArgs> | null
  /**
   * The data used to create many Bags.
   */
  data: Prisma.BagCreateManyInput | Prisma.BagCreateManyInput[]
}

/**
 * Bag update
 */
export type BagUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bag
   */
  select?: Prisma.BagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bag
   */
  omit?: Prisma.BagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagInclude<ExtArgs> | null
  /**
   * The data needed to update a Bag.
   */
  data: Prisma.XOR<Prisma.BagUpdateInput, Prisma.BagUncheckedUpdateInput>
  /**
   * Choose, which Bag to update.
   */
  where: Prisma.BagWhereUniqueInput
}

/**
 * Bag updateMany
 */
export type BagUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Bags.
   */
  data: Prisma.XOR<Prisma.BagUpdateManyMutationInput, Prisma.BagUncheckedUpdateManyInput>
  /**
   * Filter which Bags to update
   */
  where?: Prisma.BagWhereInput
  /**
   * Limit how many Bags to update.
   */
  limit?: number
}

/**
 * Bag updateManyAndReturn
 */
export type BagUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bag
   */
  select?: Prisma.BagSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Bag
   */
  omit?: Prisma.BagOmit<ExtArgs> | null
  /**
   * The data used to update Bags.
   */
  data: Prisma.XOR<Prisma.BagUpdateManyMutationInput, Prisma.BagUncheckedUpdateManyInput>
  /**
   * Filter which Bags to update
   */
  where?: Prisma.BagWhereInput
  /**
   * Limit how many Bags to update.
   */
  limit?: number
}

/**
 * Bag upsert
 */
export type BagUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bag
   */
  select?: Prisma.BagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bag
   */
  omit?: Prisma.BagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagInclude<ExtArgs> | null
  /**
   * The filter to search for the Bag to update in case it exists.
   */
  where: Prisma.BagWhereUniqueInput
  /**
   * In case the Bag found by the `where` argument doesn't exist, create a new Bag with this data.
   */
  create: Prisma.XOR<Prisma.BagCreateInput, Prisma.BagUncheckedCreateInput>
  /**
   * In case the Bag was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BagUpdateInput, Prisma.BagUncheckedUpdateInput>
}

/**
 * Bag delete
 */
export type BagDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bag
   */
  select?: Prisma.BagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bag
   */
  omit?: Prisma.BagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagInclude<ExtArgs> | null
  /**
   * Filter which Bag to delete.
   */
  where: Prisma.BagWhereUniqueInput
}

/**
 * Bag deleteMany
 */
export type BagDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Bags to delete
   */
  where?: Prisma.BagWhereInput
  /**
   * Limit how many Bags to delete.
   */
  limit?: number
}

/**
 * Bag.permissions
 */
export type Bag$permissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagPermission
   */
  select?: Prisma.BagPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BagPermission
   */
  omit?: Prisma.BagPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagPermissionInclude<ExtArgs> | null
  where?: Prisma.BagPermissionWhereInput
  orderBy?: Prisma.BagPermissionOrderByWithRelationInput | Prisma.BagPermissionOrderByWithRelationInput[]
  cursor?: Prisma.BagPermissionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BagPermissionScalarFieldEnum | Prisma.BagPermissionScalarFieldEnum[]
}

/**
 * Bag.tiddlers
 */
export type Bag$tiddlersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddler
   */
  select?: Prisma.TiddlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddler
   */
  omit?: Prisma.TiddlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerInclude<ExtArgs> | null
  where?: Prisma.TiddlerWhereInput
  orderBy?: Prisma.TiddlerOrderByWithRelationInput | Prisma.TiddlerOrderByWithRelationInput[]
  cursor?: Prisma.TiddlerWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TiddlerScalarFieldEnum | Prisma.TiddlerScalarFieldEnum[]
}

/**
 * Bag.recipe_bags
 */
export type Bag$recipe_bagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeBag
   */
  select?: Prisma.RecipeBagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeBag
   */
  omit?: Prisma.RecipeBagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeBagInclude<ExtArgs> | null
  where?: Prisma.RecipeBagWhereInput
  orderBy?: Prisma.RecipeBagOrderByWithRelationInput | Prisma.RecipeBagOrderByWithRelationInput[]
  cursor?: Prisma.RecipeBagWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RecipeBagScalarFieldEnum | Prisma.RecipeBagScalarFieldEnum[]
}

/**
 * Bag.tiddler_events
 */
export type Bag$tiddler_eventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlerEvent
   */
  select?: Prisma.TiddlerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TiddlerEvent
   */
  omit?: Prisma.TiddlerEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerEventInclude<ExtArgs> | null
  where?: Prisma.TiddlerEventWhereInput
  orderBy?: Prisma.TiddlerEventOrderByWithRelationInput | Prisma.TiddlerEventOrderByWithRelationInput[]
  cursor?: Prisma.TiddlerEventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TiddlerEventScalarFieldEnum | Prisma.TiddlerEventScalarFieldEnum[]
}

/**
 * Bag without action
 */
export type BagDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bag
   */
  select?: Prisma.BagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bag
   */
  omit?: Prisma.BagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagInclude<ExtArgs> | null
}
