
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PinboardNoteRead` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model PinboardNoteRead
 * 
 */
export type PinboardNoteReadModel = runtime.Types.Result.DefaultSelection<Prisma.$PinboardNoteReadPayload>

export type AggregatePinboardNoteRead = {
  _count: PinboardNoteReadCountAggregateOutputType | null
  _min: PinboardNoteReadMinAggregateOutputType | null
  _max: PinboardNoteReadMaxAggregateOutputType | null
}

export type PinboardNoteReadMinAggregateOutputType = {
  note_id: string | null
  user_id: string | null
  read_at: Date | null
  dismissed_at: Date | null
}

export type PinboardNoteReadMaxAggregateOutputType = {
  note_id: string | null
  user_id: string | null
  read_at: Date | null
  dismissed_at: Date | null
}

export type PinboardNoteReadCountAggregateOutputType = {
  note_id: number
  user_id: number
  read_at: number
  dismissed_at: number
  _all: number
}


export type PinboardNoteReadMinAggregateInputType = {
  note_id?: true
  user_id?: true
  read_at?: true
  dismissed_at?: true
}

export type PinboardNoteReadMaxAggregateInputType = {
  note_id?: true
  user_id?: true
  read_at?: true
  dismissed_at?: true
}

export type PinboardNoteReadCountAggregateInputType = {
  note_id?: true
  user_id?: true
  read_at?: true
  dismissed_at?: true
  _all?: true
}

export type PinboardNoteReadAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PinboardNoteRead to aggregate.
   */
  where?: Prisma.PinboardNoteReadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PinboardNoteReads to fetch.
   */
  orderBy?: Prisma.PinboardNoteReadOrderByWithRelationInput | Prisma.PinboardNoteReadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PinboardNoteReadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PinboardNoteReads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PinboardNoteReads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PinboardNoteReads
  **/
  _count?: true | PinboardNoteReadCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PinboardNoteReadMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PinboardNoteReadMaxAggregateInputType
}

export type GetPinboardNoteReadAggregateType<T extends PinboardNoteReadAggregateArgs> = {
      [P in keyof T & keyof AggregatePinboardNoteRead]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePinboardNoteRead[P]>
    : Prisma.GetScalarType<T[P], AggregatePinboardNoteRead[P]>
}




export type PinboardNoteReadGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PinboardNoteReadWhereInput
  orderBy?: Prisma.PinboardNoteReadOrderByWithAggregationInput | Prisma.PinboardNoteReadOrderByWithAggregationInput[]
  by: Prisma.PinboardNoteReadScalarFieldEnum[] | Prisma.PinboardNoteReadScalarFieldEnum
  having?: Prisma.PinboardNoteReadScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PinboardNoteReadCountAggregateInputType | true
  _min?: PinboardNoteReadMinAggregateInputType
  _max?: PinboardNoteReadMaxAggregateInputType
}

export type PinboardNoteReadGroupByOutputType = {
  note_id: string
  user_id: string
  read_at: Date | null
  dismissed_at: Date | null
  _count: PinboardNoteReadCountAggregateOutputType | null
  _min: PinboardNoteReadMinAggregateOutputType | null
  _max: PinboardNoteReadMaxAggregateOutputType | null
}

export type GetPinboardNoteReadGroupByPayload<T extends PinboardNoteReadGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PinboardNoteReadGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PinboardNoteReadGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PinboardNoteReadGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PinboardNoteReadGroupByOutputType[P]>
      }
    >
  >



export type PinboardNoteReadWhereInput = {
  AND?: Prisma.PinboardNoteReadWhereInput | Prisma.PinboardNoteReadWhereInput[]
  OR?: Prisma.PinboardNoteReadWhereInput[]
  NOT?: Prisma.PinboardNoteReadWhereInput | Prisma.PinboardNoteReadWhereInput[]
  note_id?: Prisma.StringFilter<"PinboardNoteRead"> | string
  user_id?: Prisma.StringFilter<"PinboardNoteRead"> | string
  read_at?: Prisma.DateTimeNullableFilter<"PinboardNoteRead"> | Date | string | null
  dismissed_at?: Prisma.DateTimeNullableFilter<"PinboardNoteRead"> | Date | string | null
  note?: Prisma.XOR<Prisma.PinboardNoteScalarRelationFilter, Prisma.PinboardNoteWhereInput>
}

export type PinboardNoteReadOrderByWithRelationInput = {
  note_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  read_at?: Prisma.SortOrderInput | Prisma.SortOrder
  dismissed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  note?: Prisma.PinboardNoteOrderByWithRelationInput
}

export type PinboardNoteReadWhereUniqueInput = Prisma.AtLeast<{
  note_id_user_id?: Prisma.PinboardNoteReadNote_idUser_idCompoundUniqueInput
  AND?: Prisma.PinboardNoteReadWhereInput | Prisma.PinboardNoteReadWhereInput[]
  OR?: Prisma.PinboardNoteReadWhereInput[]
  NOT?: Prisma.PinboardNoteReadWhereInput | Prisma.PinboardNoteReadWhereInput[]
  note_id?: Prisma.StringFilter<"PinboardNoteRead"> | string
  user_id?: Prisma.StringFilter<"PinboardNoteRead"> | string
  read_at?: Prisma.DateTimeNullableFilter<"PinboardNoteRead"> | Date | string | null
  dismissed_at?: Prisma.DateTimeNullableFilter<"PinboardNoteRead"> | Date | string | null
  note?: Prisma.XOR<Prisma.PinboardNoteScalarRelationFilter, Prisma.PinboardNoteWhereInput>
}, "note_id_user_id">

export type PinboardNoteReadOrderByWithAggregationInput = {
  note_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  read_at?: Prisma.SortOrderInput | Prisma.SortOrder
  dismissed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PinboardNoteReadCountOrderByAggregateInput
  _max?: Prisma.PinboardNoteReadMaxOrderByAggregateInput
  _min?: Prisma.PinboardNoteReadMinOrderByAggregateInput
}

export type PinboardNoteReadScalarWhereWithAggregatesInput = {
  AND?: Prisma.PinboardNoteReadScalarWhereWithAggregatesInput | Prisma.PinboardNoteReadScalarWhereWithAggregatesInput[]
  OR?: Prisma.PinboardNoteReadScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PinboardNoteReadScalarWhereWithAggregatesInput | Prisma.PinboardNoteReadScalarWhereWithAggregatesInput[]
  note_id?: Prisma.StringWithAggregatesFilter<"PinboardNoteRead"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"PinboardNoteRead"> | string
  read_at?: Prisma.DateTimeNullableWithAggregatesFilter<"PinboardNoteRead"> | Date | string | null
  dismissed_at?: Prisma.DateTimeNullableWithAggregatesFilter<"PinboardNoteRead"> | Date | string | null
}

export type PinboardNoteReadCreateInput = {
  user_id: string
  read_at?: Date | string | null
  dismissed_at?: Date | string | null
  note: Prisma.PinboardNoteCreateNestedOneWithoutReadsInput
}

export type PinboardNoteReadUncheckedCreateInput = {
  note_id: string
  user_id: string
  read_at?: Date | string | null
  dismissed_at?: Date | string | null
}

export type PinboardNoteReadUpdateInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  read_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dismissed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  note?: Prisma.PinboardNoteUpdateOneRequiredWithoutReadsNestedInput
}

export type PinboardNoteReadUncheckedUpdateInput = {
  note_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  read_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dismissed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PinboardNoteReadCreateManyInput = {
  note_id: string
  user_id: string
  read_at?: Date | string | null
  dismissed_at?: Date | string | null
}

export type PinboardNoteReadUpdateManyMutationInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  read_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dismissed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PinboardNoteReadUncheckedUpdateManyInput = {
  note_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  read_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dismissed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PinboardNoteReadListRelationFilter = {
  every?: Prisma.PinboardNoteReadWhereInput
  some?: Prisma.PinboardNoteReadWhereInput
  none?: Prisma.PinboardNoteReadWhereInput
}

export type PinboardNoteReadOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PinboardNoteReadNote_idUser_idCompoundUniqueInput = {
  note_id: string
  user_id: string
}

export type PinboardNoteReadCountOrderByAggregateInput = {
  note_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  read_at?: Prisma.SortOrder
  dismissed_at?: Prisma.SortOrder
}

export type PinboardNoteReadMaxOrderByAggregateInput = {
  note_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  read_at?: Prisma.SortOrder
  dismissed_at?: Prisma.SortOrder
}

export type PinboardNoteReadMinOrderByAggregateInput = {
  note_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  read_at?: Prisma.SortOrder
  dismissed_at?: Prisma.SortOrder
}

export type PinboardNoteReadCreateNestedManyWithoutNoteInput = {
  create?: Prisma.XOR<Prisma.PinboardNoteReadCreateWithoutNoteInput, Prisma.PinboardNoteReadUncheckedCreateWithoutNoteInput> | Prisma.PinboardNoteReadCreateWithoutNoteInput[] | Prisma.PinboardNoteReadUncheckedCreateWithoutNoteInput[]
  connectOrCreate?: Prisma.PinboardNoteReadCreateOrConnectWithoutNoteInput | Prisma.PinboardNoteReadCreateOrConnectWithoutNoteInput[]
  createMany?: Prisma.PinboardNoteReadCreateManyNoteInputEnvelope
  connect?: Prisma.PinboardNoteReadWhereUniqueInput | Prisma.PinboardNoteReadWhereUniqueInput[]
}

export type PinboardNoteReadUncheckedCreateNestedManyWithoutNoteInput = {
  create?: Prisma.XOR<Prisma.PinboardNoteReadCreateWithoutNoteInput, Prisma.PinboardNoteReadUncheckedCreateWithoutNoteInput> | Prisma.PinboardNoteReadCreateWithoutNoteInput[] | Prisma.PinboardNoteReadUncheckedCreateWithoutNoteInput[]
  connectOrCreate?: Prisma.PinboardNoteReadCreateOrConnectWithoutNoteInput | Prisma.PinboardNoteReadCreateOrConnectWithoutNoteInput[]
  createMany?: Prisma.PinboardNoteReadCreateManyNoteInputEnvelope
  connect?: Prisma.PinboardNoteReadWhereUniqueInput | Prisma.PinboardNoteReadWhereUniqueInput[]
}

export type PinboardNoteReadUpdateManyWithoutNoteNestedInput = {
  create?: Prisma.XOR<Prisma.PinboardNoteReadCreateWithoutNoteInput, Prisma.PinboardNoteReadUncheckedCreateWithoutNoteInput> | Prisma.PinboardNoteReadCreateWithoutNoteInput[] | Prisma.PinboardNoteReadUncheckedCreateWithoutNoteInput[]
  connectOrCreate?: Prisma.PinboardNoteReadCreateOrConnectWithoutNoteInput | Prisma.PinboardNoteReadCreateOrConnectWithoutNoteInput[]
  upsert?: Prisma.PinboardNoteReadUpsertWithWhereUniqueWithoutNoteInput | Prisma.PinboardNoteReadUpsertWithWhereUniqueWithoutNoteInput[]
  createMany?: Prisma.PinboardNoteReadCreateManyNoteInputEnvelope
  set?: Prisma.PinboardNoteReadWhereUniqueInput | Prisma.PinboardNoteReadWhereUniqueInput[]
  disconnect?: Prisma.PinboardNoteReadWhereUniqueInput | Prisma.PinboardNoteReadWhereUniqueInput[]
  delete?: Prisma.PinboardNoteReadWhereUniqueInput | Prisma.PinboardNoteReadWhereUniqueInput[]
  connect?: Prisma.PinboardNoteReadWhereUniqueInput | Prisma.PinboardNoteReadWhereUniqueInput[]
  update?: Prisma.PinboardNoteReadUpdateWithWhereUniqueWithoutNoteInput | Prisma.PinboardNoteReadUpdateWithWhereUniqueWithoutNoteInput[]
  updateMany?: Prisma.PinboardNoteReadUpdateManyWithWhereWithoutNoteInput | Prisma.PinboardNoteReadUpdateManyWithWhereWithoutNoteInput[]
  deleteMany?: Prisma.PinboardNoteReadScalarWhereInput | Prisma.PinboardNoteReadScalarWhereInput[]
}

export type PinboardNoteReadUncheckedUpdateManyWithoutNoteNestedInput = {
  create?: Prisma.XOR<Prisma.PinboardNoteReadCreateWithoutNoteInput, Prisma.PinboardNoteReadUncheckedCreateWithoutNoteInput> | Prisma.PinboardNoteReadCreateWithoutNoteInput[] | Prisma.PinboardNoteReadUncheckedCreateWithoutNoteInput[]
  connectOrCreate?: Prisma.PinboardNoteReadCreateOrConnectWithoutNoteInput | Prisma.PinboardNoteReadCreateOrConnectWithoutNoteInput[]
  upsert?: Prisma.PinboardNoteReadUpsertWithWhereUniqueWithoutNoteInput | Prisma.PinboardNoteReadUpsertWithWhereUniqueWithoutNoteInput[]
  createMany?: Prisma.PinboardNoteReadCreateManyNoteInputEnvelope
  set?: Prisma.PinboardNoteReadWhereUniqueInput | Prisma.PinboardNoteReadWhereUniqueInput[]
  disconnect?: Prisma.PinboardNoteReadWhereUniqueInput | Prisma.PinboardNoteReadWhereUniqueInput[]
  delete?: Prisma.PinboardNoteReadWhereUniqueInput | Prisma.PinboardNoteReadWhereUniqueInput[]
  connect?: Prisma.PinboardNoteReadWhereUniqueInput | Prisma.PinboardNoteReadWhereUniqueInput[]
  update?: Prisma.PinboardNoteReadUpdateWithWhereUniqueWithoutNoteInput | Prisma.PinboardNoteReadUpdateWithWhereUniqueWithoutNoteInput[]
  updateMany?: Prisma.PinboardNoteReadUpdateManyWithWhereWithoutNoteInput | Prisma.PinboardNoteReadUpdateManyWithWhereWithoutNoteInput[]
  deleteMany?: Prisma.PinboardNoteReadScalarWhereInput | Prisma.PinboardNoteReadScalarWhereInput[]
}

export type PinboardNoteReadCreateWithoutNoteInput = {
  user_id: string
  read_at?: Date | string | null
  dismissed_at?: Date | string | null
}

export type PinboardNoteReadUncheckedCreateWithoutNoteInput = {
  user_id: string
  read_at?: Date | string | null
  dismissed_at?: Date | string | null
}

export type PinboardNoteReadCreateOrConnectWithoutNoteInput = {
  where: Prisma.PinboardNoteReadWhereUniqueInput
  create: Prisma.XOR<Prisma.PinboardNoteReadCreateWithoutNoteInput, Prisma.PinboardNoteReadUncheckedCreateWithoutNoteInput>
}

export type PinboardNoteReadCreateManyNoteInputEnvelope = {
  data: Prisma.PinboardNoteReadCreateManyNoteInput | Prisma.PinboardNoteReadCreateManyNoteInput[]
}

export type PinboardNoteReadUpsertWithWhereUniqueWithoutNoteInput = {
  where: Prisma.PinboardNoteReadWhereUniqueInput
  update: Prisma.XOR<Prisma.PinboardNoteReadUpdateWithoutNoteInput, Prisma.PinboardNoteReadUncheckedUpdateWithoutNoteInput>
  create: Prisma.XOR<Prisma.PinboardNoteReadCreateWithoutNoteInput, Prisma.PinboardNoteReadUncheckedCreateWithoutNoteInput>
}

export type PinboardNoteReadUpdateWithWhereUniqueWithoutNoteInput = {
  where: Prisma.PinboardNoteReadWhereUniqueInput
  data: Prisma.XOR<Prisma.PinboardNoteReadUpdateWithoutNoteInput, Prisma.PinboardNoteReadUncheckedUpdateWithoutNoteInput>
}

export type PinboardNoteReadUpdateManyWithWhereWithoutNoteInput = {
  where: Prisma.PinboardNoteReadScalarWhereInput
  data: Prisma.XOR<Prisma.PinboardNoteReadUpdateManyMutationInput, Prisma.PinboardNoteReadUncheckedUpdateManyWithoutNoteInput>
}

export type PinboardNoteReadScalarWhereInput = {
  AND?: Prisma.PinboardNoteReadScalarWhereInput | Prisma.PinboardNoteReadScalarWhereInput[]
  OR?: Prisma.PinboardNoteReadScalarWhereInput[]
  NOT?: Prisma.PinboardNoteReadScalarWhereInput | Prisma.PinboardNoteReadScalarWhereInput[]
  note_id?: Prisma.StringFilter<"PinboardNoteRead"> | string
  user_id?: Prisma.StringFilter<"PinboardNoteRead"> | string
  read_at?: Prisma.DateTimeNullableFilter<"PinboardNoteRead"> | Date | string | null
  dismissed_at?: Prisma.DateTimeNullableFilter<"PinboardNoteRead"> | Date | string | null
}

export type PinboardNoteReadCreateManyNoteInput = {
  user_id: string
  read_at?: Date | string | null
  dismissed_at?: Date | string | null
}

export type PinboardNoteReadUpdateWithoutNoteInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  read_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dismissed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PinboardNoteReadUncheckedUpdateWithoutNoteInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  read_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dismissed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PinboardNoteReadUncheckedUpdateManyWithoutNoteInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  read_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dismissed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type PinboardNoteReadSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  note_id?: boolean
  user_id?: boolean
  read_at?: boolean
  dismissed_at?: boolean
  note?: boolean | Prisma.PinboardNoteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pinboardNoteRead"]>

export type PinboardNoteReadSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  note_id?: boolean
  user_id?: boolean
  read_at?: boolean
  dismissed_at?: boolean
  note?: boolean | Prisma.PinboardNoteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pinboardNoteRead"]>

export type PinboardNoteReadSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  note_id?: boolean
  user_id?: boolean
  read_at?: boolean
  dismissed_at?: boolean
  note?: boolean | Prisma.PinboardNoteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pinboardNoteRead"]>

export type PinboardNoteReadSelectScalar = {
  note_id?: boolean
  user_id?: boolean
  read_at?: boolean
  dismissed_at?: boolean
}

export type PinboardNoteReadOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"note_id" | "user_id" | "read_at" | "dismissed_at", ExtArgs["result"]["pinboardNoteRead"]>
export type PinboardNoteReadInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  note?: boolean | Prisma.PinboardNoteDefaultArgs<ExtArgs>
}
export type PinboardNoteReadIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  note?: boolean | Prisma.PinboardNoteDefaultArgs<ExtArgs>
}
export type PinboardNoteReadIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  note?: boolean | Prisma.PinboardNoteDefaultArgs<ExtArgs>
}

export type $PinboardNoteReadPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PinboardNoteRead"
  objects: {
    note: Prisma.$PinboardNotePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    note_id: string
    user_id: string
    read_at: Date | null
    dismissed_at: Date | null
  }, ExtArgs["result"]["pinboardNoteRead"]>
  composites: {}
}

export type PinboardNoteReadGetPayload<S extends boolean | null | undefined | PinboardNoteReadDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PinboardNoteReadPayload, S>

export type PinboardNoteReadCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PinboardNoteReadFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PinboardNoteReadCountAggregateInputType | true
  }

export interface PinboardNoteReadDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PinboardNoteRead'], meta: { name: 'PinboardNoteRead' } }
  /**
   * Find zero or one PinboardNoteRead that matches the filter.
   * @param {PinboardNoteReadFindUniqueArgs} args - Arguments to find a PinboardNoteRead
   * @example
   * // Get one PinboardNoteRead
   * const pinboardNoteRead = await prisma.pinboardNoteRead.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PinboardNoteReadFindUniqueArgs>(args: Prisma.SelectSubset<T, PinboardNoteReadFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteReadClient<runtime.Types.Result.GetResult<Prisma.$PinboardNoteReadPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PinboardNoteRead that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PinboardNoteReadFindUniqueOrThrowArgs} args - Arguments to find a PinboardNoteRead
   * @example
   * // Get one PinboardNoteRead
   * const pinboardNoteRead = await prisma.pinboardNoteRead.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PinboardNoteReadFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PinboardNoteReadFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteReadClient<runtime.Types.Result.GetResult<Prisma.$PinboardNoteReadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PinboardNoteRead that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteReadFindFirstArgs} args - Arguments to find a PinboardNoteRead
   * @example
   * // Get one PinboardNoteRead
   * const pinboardNoteRead = await prisma.pinboardNoteRead.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PinboardNoteReadFindFirstArgs>(args?: Prisma.SelectSubset<T, PinboardNoteReadFindFirstArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteReadClient<runtime.Types.Result.GetResult<Prisma.$PinboardNoteReadPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PinboardNoteRead that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteReadFindFirstOrThrowArgs} args - Arguments to find a PinboardNoteRead
   * @example
   * // Get one PinboardNoteRead
   * const pinboardNoteRead = await prisma.pinboardNoteRead.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PinboardNoteReadFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PinboardNoteReadFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteReadClient<runtime.Types.Result.GetResult<Prisma.$PinboardNoteReadPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PinboardNoteReads that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteReadFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PinboardNoteReads
   * const pinboardNoteReads = await prisma.pinboardNoteRead.findMany()
   * 
   * // Get first 10 PinboardNoteReads
   * const pinboardNoteReads = await prisma.pinboardNoteRead.findMany({ take: 10 })
   * 
   * // Only select the `note_id`
   * const pinboardNoteReadWithNote_idOnly = await prisma.pinboardNoteRead.findMany({ select: { note_id: true } })
   * 
   */
  findMany<T extends PinboardNoteReadFindManyArgs>(args?: Prisma.SelectSubset<T, PinboardNoteReadFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PinboardNoteReadPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PinboardNoteRead.
   * @param {PinboardNoteReadCreateArgs} args - Arguments to create a PinboardNoteRead.
   * @example
   * // Create one PinboardNoteRead
   * const PinboardNoteRead = await prisma.pinboardNoteRead.create({
   *   data: {
   *     // ... data to create a PinboardNoteRead
   *   }
   * })
   * 
   */
  create<T extends PinboardNoteReadCreateArgs>(args: Prisma.SelectSubset<T, PinboardNoteReadCreateArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteReadClient<runtime.Types.Result.GetResult<Prisma.$PinboardNoteReadPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PinboardNoteReads.
   * @param {PinboardNoteReadCreateManyArgs} args - Arguments to create many PinboardNoteReads.
   * @example
   * // Create many PinboardNoteReads
   * const pinboardNoteRead = await prisma.pinboardNoteRead.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PinboardNoteReadCreateManyArgs>(args?: Prisma.SelectSubset<T, PinboardNoteReadCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PinboardNoteReads and returns the data saved in the database.
   * @param {PinboardNoteReadCreateManyAndReturnArgs} args - Arguments to create many PinboardNoteReads.
   * @example
   * // Create many PinboardNoteReads
   * const pinboardNoteRead = await prisma.pinboardNoteRead.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PinboardNoteReads and only return the `note_id`
   * const pinboardNoteReadWithNote_idOnly = await prisma.pinboardNoteRead.createManyAndReturn({
   *   select: { note_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PinboardNoteReadCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PinboardNoteReadCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PinboardNoteReadPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PinboardNoteRead.
   * @param {PinboardNoteReadDeleteArgs} args - Arguments to delete one PinboardNoteRead.
   * @example
   * // Delete one PinboardNoteRead
   * const PinboardNoteRead = await prisma.pinboardNoteRead.delete({
   *   where: {
   *     // ... filter to delete one PinboardNoteRead
   *   }
   * })
   * 
   */
  delete<T extends PinboardNoteReadDeleteArgs>(args: Prisma.SelectSubset<T, PinboardNoteReadDeleteArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteReadClient<runtime.Types.Result.GetResult<Prisma.$PinboardNoteReadPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PinboardNoteRead.
   * @param {PinboardNoteReadUpdateArgs} args - Arguments to update one PinboardNoteRead.
   * @example
   * // Update one PinboardNoteRead
   * const pinboardNoteRead = await prisma.pinboardNoteRead.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PinboardNoteReadUpdateArgs>(args: Prisma.SelectSubset<T, PinboardNoteReadUpdateArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteReadClient<runtime.Types.Result.GetResult<Prisma.$PinboardNoteReadPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PinboardNoteReads.
   * @param {PinboardNoteReadDeleteManyArgs} args - Arguments to filter PinboardNoteReads to delete.
   * @example
   * // Delete a few PinboardNoteReads
   * const { count } = await prisma.pinboardNoteRead.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PinboardNoteReadDeleteManyArgs>(args?: Prisma.SelectSubset<T, PinboardNoteReadDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PinboardNoteReads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteReadUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PinboardNoteReads
   * const pinboardNoteRead = await prisma.pinboardNoteRead.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PinboardNoteReadUpdateManyArgs>(args: Prisma.SelectSubset<T, PinboardNoteReadUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PinboardNoteReads and returns the data updated in the database.
   * @param {PinboardNoteReadUpdateManyAndReturnArgs} args - Arguments to update many PinboardNoteReads.
   * @example
   * // Update many PinboardNoteReads
   * const pinboardNoteRead = await prisma.pinboardNoteRead.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PinboardNoteReads and only return the `note_id`
   * const pinboardNoteReadWithNote_idOnly = await prisma.pinboardNoteRead.updateManyAndReturn({
   *   select: { note_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PinboardNoteReadUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PinboardNoteReadUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PinboardNoteReadPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PinboardNoteRead.
   * @param {PinboardNoteReadUpsertArgs} args - Arguments to update or create a PinboardNoteRead.
   * @example
   * // Update or create a PinboardNoteRead
   * const pinboardNoteRead = await prisma.pinboardNoteRead.upsert({
   *   create: {
   *     // ... data to create a PinboardNoteRead
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PinboardNoteRead we want to update
   *   }
   * })
   */
  upsert<T extends PinboardNoteReadUpsertArgs>(args: Prisma.SelectSubset<T, PinboardNoteReadUpsertArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteReadClient<runtime.Types.Result.GetResult<Prisma.$PinboardNoteReadPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PinboardNoteReads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteReadCountArgs} args - Arguments to filter PinboardNoteReads to count.
   * @example
   * // Count the number of PinboardNoteReads
   * const count = await prisma.pinboardNoteRead.count({
   *   where: {
   *     // ... the filter for the PinboardNoteReads we want to count
   *   }
   * })
  **/
  count<T extends PinboardNoteReadCountArgs>(
    args?: Prisma.Subset<T, PinboardNoteReadCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PinboardNoteReadCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PinboardNoteRead.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteReadAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PinboardNoteReadAggregateArgs>(args: Prisma.Subset<T, PinboardNoteReadAggregateArgs>): Prisma.PrismaPromise<GetPinboardNoteReadAggregateType<T>>

  /**
   * Group by PinboardNoteRead.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteReadGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PinboardNoteReadGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PinboardNoteReadGroupByArgs['orderBy'] }
      : { orderBy?: PinboardNoteReadGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PinboardNoteReadGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPinboardNoteReadGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PinboardNoteRead model
 */
readonly fields: PinboardNoteReadFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PinboardNoteRead.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PinboardNoteReadClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  note<T extends Prisma.PinboardNoteDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PinboardNoteDefaultArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteClient<runtime.Types.Result.GetResult<Prisma.$PinboardNotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PinboardNoteRead model
 */
export interface PinboardNoteReadFieldRefs {
  readonly note_id: Prisma.FieldRef<"PinboardNoteRead", 'String'>
  readonly user_id: Prisma.FieldRef<"PinboardNoteRead", 'String'>
  readonly read_at: Prisma.FieldRef<"PinboardNoteRead", 'DateTime'>
  readonly dismissed_at: Prisma.FieldRef<"PinboardNoteRead", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PinboardNoteRead findUnique
 */
export type PinboardNoteReadFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteRead
   */
  select?: Prisma.PinboardNoteReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNoteRead
   */
  omit?: Prisma.PinboardNoteReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteReadInclude<ExtArgs> | null
  /**
   * Filter, which PinboardNoteRead to fetch.
   */
  where: Prisma.PinboardNoteReadWhereUniqueInput
}

/**
 * PinboardNoteRead findUniqueOrThrow
 */
export type PinboardNoteReadFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteRead
   */
  select?: Prisma.PinboardNoteReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNoteRead
   */
  omit?: Prisma.PinboardNoteReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteReadInclude<ExtArgs> | null
  /**
   * Filter, which PinboardNoteRead to fetch.
   */
  where: Prisma.PinboardNoteReadWhereUniqueInput
}

/**
 * PinboardNoteRead findFirst
 */
export type PinboardNoteReadFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteRead
   */
  select?: Prisma.PinboardNoteReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNoteRead
   */
  omit?: Prisma.PinboardNoteReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteReadInclude<ExtArgs> | null
  /**
   * Filter, which PinboardNoteRead to fetch.
   */
  where?: Prisma.PinboardNoteReadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PinboardNoteReads to fetch.
   */
  orderBy?: Prisma.PinboardNoteReadOrderByWithRelationInput | Prisma.PinboardNoteReadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PinboardNoteReads.
   */
  cursor?: Prisma.PinboardNoteReadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PinboardNoteReads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PinboardNoteReads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PinboardNoteReads.
   */
  distinct?: Prisma.PinboardNoteReadScalarFieldEnum | Prisma.PinboardNoteReadScalarFieldEnum[]
}

/**
 * PinboardNoteRead findFirstOrThrow
 */
export type PinboardNoteReadFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteRead
   */
  select?: Prisma.PinboardNoteReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNoteRead
   */
  omit?: Prisma.PinboardNoteReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteReadInclude<ExtArgs> | null
  /**
   * Filter, which PinboardNoteRead to fetch.
   */
  where?: Prisma.PinboardNoteReadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PinboardNoteReads to fetch.
   */
  orderBy?: Prisma.PinboardNoteReadOrderByWithRelationInput | Prisma.PinboardNoteReadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PinboardNoteReads.
   */
  cursor?: Prisma.PinboardNoteReadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PinboardNoteReads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PinboardNoteReads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PinboardNoteReads.
   */
  distinct?: Prisma.PinboardNoteReadScalarFieldEnum | Prisma.PinboardNoteReadScalarFieldEnum[]
}

/**
 * PinboardNoteRead findMany
 */
export type PinboardNoteReadFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteRead
   */
  select?: Prisma.PinboardNoteReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNoteRead
   */
  omit?: Prisma.PinboardNoteReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteReadInclude<ExtArgs> | null
  /**
   * Filter, which PinboardNoteReads to fetch.
   */
  where?: Prisma.PinboardNoteReadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PinboardNoteReads to fetch.
   */
  orderBy?: Prisma.PinboardNoteReadOrderByWithRelationInput | Prisma.PinboardNoteReadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PinboardNoteReads.
   */
  cursor?: Prisma.PinboardNoteReadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PinboardNoteReads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PinboardNoteReads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PinboardNoteReads.
   */
  distinct?: Prisma.PinboardNoteReadScalarFieldEnum | Prisma.PinboardNoteReadScalarFieldEnum[]
}

/**
 * PinboardNoteRead create
 */
export type PinboardNoteReadCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteRead
   */
  select?: Prisma.PinboardNoteReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNoteRead
   */
  omit?: Prisma.PinboardNoteReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteReadInclude<ExtArgs> | null
  /**
   * The data needed to create a PinboardNoteRead.
   */
  data: Prisma.XOR<Prisma.PinboardNoteReadCreateInput, Prisma.PinboardNoteReadUncheckedCreateInput>
}

/**
 * PinboardNoteRead createMany
 */
export type PinboardNoteReadCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PinboardNoteReads.
   */
  data: Prisma.PinboardNoteReadCreateManyInput | Prisma.PinboardNoteReadCreateManyInput[]
}

/**
 * PinboardNoteRead createManyAndReturn
 */
export type PinboardNoteReadCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteRead
   */
  select?: Prisma.PinboardNoteReadSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNoteRead
   */
  omit?: Prisma.PinboardNoteReadOmit<ExtArgs> | null
  /**
   * The data used to create many PinboardNoteReads.
   */
  data: Prisma.PinboardNoteReadCreateManyInput | Prisma.PinboardNoteReadCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteReadIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PinboardNoteRead update
 */
export type PinboardNoteReadUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteRead
   */
  select?: Prisma.PinboardNoteReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNoteRead
   */
  omit?: Prisma.PinboardNoteReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteReadInclude<ExtArgs> | null
  /**
   * The data needed to update a PinboardNoteRead.
   */
  data: Prisma.XOR<Prisma.PinboardNoteReadUpdateInput, Prisma.PinboardNoteReadUncheckedUpdateInput>
  /**
   * Choose, which PinboardNoteRead to update.
   */
  where: Prisma.PinboardNoteReadWhereUniqueInput
}

/**
 * PinboardNoteRead updateMany
 */
export type PinboardNoteReadUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PinboardNoteReads.
   */
  data: Prisma.XOR<Prisma.PinboardNoteReadUpdateManyMutationInput, Prisma.PinboardNoteReadUncheckedUpdateManyInput>
  /**
   * Filter which PinboardNoteReads to update
   */
  where?: Prisma.PinboardNoteReadWhereInput
  /**
   * Limit how many PinboardNoteReads to update.
   */
  limit?: number
}

/**
 * PinboardNoteRead updateManyAndReturn
 */
export type PinboardNoteReadUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteRead
   */
  select?: Prisma.PinboardNoteReadSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNoteRead
   */
  omit?: Prisma.PinboardNoteReadOmit<ExtArgs> | null
  /**
   * The data used to update PinboardNoteReads.
   */
  data: Prisma.XOR<Prisma.PinboardNoteReadUpdateManyMutationInput, Prisma.PinboardNoteReadUncheckedUpdateManyInput>
  /**
   * Filter which PinboardNoteReads to update
   */
  where?: Prisma.PinboardNoteReadWhereInput
  /**
   * Limit how many PinboardNoteReads to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteReadIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PinboardNoteRead upsert
 */
export type PinboardNoteReadUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteRead
   */
  select?: Prisma.PinboardNoteReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNoteRead
   */
  omit?: Prisma.PinboardNoteReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteReadInclude<ExtArgs> | null
  /**
   * The filter to search for the PinboardNoteRead to update in case it exists.
   */
  where: Prisma.PinboardNoteReadWhereUniqueInput
  /**
   * In case the PinboardNoteRead found by the `where` argument doesn't exist, create a new PinboardNoteRead with this data.
   */
  create: Prisma.XOR<Prisma.PinboardNoteReadCreateInput, Prisma.PinboardNoteReadUncheckedCreateInput>
  /**
   * In case the PinboardNoteRead was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PinboardNoteReadUpdateInput, Prisma.PinboardNoteReadUncheckedUpdateInput>
}

/**
 * PinboardNoteRead delete
 */
export type PinboardNoteReadDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteRead
   */
  select?: Prisma.PinboardNoteReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNoteRead
   */
  omit?: Prisma.PinboardNoteReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteReadInclude<ExtArgs> | null
  /**
   * Filter which PinboardNoteRead to delete.
   */
  where: Prisma.PinboardNoteReadWhereUniqueInput
}

/**
 * PinboardNoteRead deleteMany
 */
export type PinboardNoteReadDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PinboardNoteReads to delete
   */
  where?: Prisma.PinboardNoteReadWhereInput
  /**
   * Limit how many PinboardNoteReads to delete.
   */
  limit?: number
}

/**
 * PinboardNoteRead without action
 */
export type PinboardNoteReadDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteRead
   */
  select?: Prisma.PinboardNoteReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNoteRead
   */
  omit?: Prisma.PinboardNoteReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteReadInclude<ExtArgs> | null
}
