
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PinboardNote` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model PinboardNote
 * 
 */
export type PinboardNoteModel = runtime.Types.Result.DefaultSelection<Prisma.$PinboardNotePayload>

export type AggregatePinboardNote = {
  _count: PinboardNoteCountAggregateOutputType | null
  _min: PinboardNoteMinAggregateOutputType | null
  _max: PinboardNoteMaxAggregateOutputType | null
}

export type PinboardNoteMinAggregateOutputType = {
  id: string | null
  author_user_id: string | null
  author_name: string | null
  scope_type: string | null
  scope_id: string | null
  body: string | null
  color: string | null
  is_important: boolean | null
  is_active: boolean | null
  created_at: Date | null
  updated_at: Date | null
  expires_at: Date | null
}

export type PinboardNoteMaxAggregateOutputType = {
  id: string | null
  author_user_id: string | null
  author_name: string | null
  scope_type: string | null
  scope_id: string | null
  body: string | null
  color: string | null
  is_important: boolean | null
  is_active: boolean | null
  created_at: Date | null
  updated_at: Date | null
  expires_at: Date | null
}

export type PinboardNoteCountAggregateOutputType = {
  id: number
  author_user_id: number
  author_name: number
  scope_type: number
  scope_id: number
  body: number
  color: number
  is_important: number
  is_active: number
  created_at: number
  updated_at: number
  expires_at: number
  _all: number
}


export type PinboardNoteMinAggregateInputType = {
  id?: true
  author_user_id?: true
  author_name?: true
  scope_type?: true
  scope_id?: true
  body?: true
  color?: true
  is_important?: true
  is_active?: true
  created_at?: true
  updated_at?: true
  expires_at?: true
}

export type PinboardNoteMaxAggregateInputType = {
  id?: true
  author_user_id?: true
  author_name?: true
  scope_type?: true
  scope_id?: true
  body?: true
  color?: true
  is_important?: true
  is_active?: true
  created_at?: true
  updated_at?: true
  expires_at?: true
}

export type PinboardNoteCountAggregateInputType = {
  id?: true
  author_user_id?: true
  author_name?: true
  scope_type?: true
  scope_id?: true
  body?: true
  color?: true
  is_important?: true
  is_active?: true
  created_at?: true
  updated_at?: true
  expires_at?: true
  _all?: true
}

export type PinboardNoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PinboardNote to aggregate.
   */
  where?: Prisma.PinboardNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PinboardNotes to fetch.
   */
  orderBy?: Prisma.PinboardNoteOrderByWithRelationInput | Prisma.PinboardNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PinboardNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PinboardNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PinboardNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PinboardNotes
  **/
  _count?: true | PinboardNoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PinboardNoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PinboardNoteMaxAggregateInputType
}

export type GetPinboardNoteAggregateType<T extends PinboardNoteAggregateArgs> = {
      [P in keyof T & keyof AggregatePinboardNote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePinboardNote[P]>
    : Prisma.GetScalarType<T[P], AggregatePinboardNote[P]>
}




export type PinboardNoteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PinboardNoteWhereInput
  orderBy?: Prisma.PinboardNoteOrderByWithAggregationInput | Prisma.PinboardNoteOrderByWithAggregationInput[]
  by: Prisma.PinboardNoteScalarFieldEnum[] | Prisma.PinboardNoteScalarFieldEnum
  having?: Prisma.PinboardNoteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PinboardNoteCountAggregateInputType | true
  _min?: PinboardNoteMinAggregateInputType
  _max?: PinboardNoteMaxAggregateInputType
}

export type PinboardNoteGroupByOutputType = {
  id: string
  author_user_id: string
  author_name: string
  scope_type: string
  scope_id: string | null
  body: string
  color: string
  is_important: boolean
  is_active: boolean
  created_at: Date
  updated_at: Date
  expires_at: Date | null
  _count: PinboardNoteCountAggregateOutputType | null
  _min: PinboardNoteMinAggregateOutputType | null
  _max: PinboardNoteMaxAggregateOutputType | null
}

export type GetPinboardNoteGroupByPayload<T extends PinboardNoteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PinboardNoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PinboardNoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PinboardNoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PinboardNoteGroupByOutputType[P]>
      }
    >
  >



export type PinboardNoteWhereInput = {
  AND?: Prisma.PinboardNoteWhereInput | Prisma.PinboardNoteWhereInput[]
  OR?: Prisma.PinboardNoteWhereInput[]
  NOT?: Prisma.PinboardNoteWhereInput | Prisma.PinboardNoteWhereInput[]
  id?: Prisma.StringFilter<"PinboardNote"> | string
  author_user_id?: Prisma.StringFilter<"PinboardNote"> | string
  author_name?: Prisma.StringFilter<"PinboardNote"> | string
  scope_type?: Prisma.StringFilter<"PinboardNote"> | string
  scope_id?: Prisma.StringNullableFilter<"PinboardNote"> | string | null
  body?: Prisma.StringFilter<"PinboardNote"> | string
  color?: Prisma.StringFilter<"PinboardNote"> | string
  is_important?: Prisma.BoolFilter<"PinboardNote"> | boolean
  is_active?: Prisma.BoolFilter<"PinboardNote"> | boolean
  created_at?: Prisma.DateTimeFilter<"PinboardNote"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"PinboardNote"> | Date | string
  expires_at?: Prisma.DateTimeNullableFilter<"PinboardNote"> | Date | string | null
  reads?: Prisma.PinboardNoteReadListRelationFilter
  positions?: Prisma.PinboardNotePositionListRelationFilter
}

export type PinboardNoteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  author_user_id?: Prisma.SortOrder
  author_name?: Prisma.SortOrder
  scope_type?: Prisma.SortOrder
  scope_id?: Prisma.SortOrderInput | Prisma.SortOrder
  body?: Prisma.SortOrder
  color?: Prisma.SortOrder
  is_important?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  reads?: Prisma.PinboardNoteReadOrderByRelationAggregateInput
  positions?: Prisma.PinboardNotePositionOrderByRelationAggregateInput
}

export type PinboardNoteWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PinboardNoteWhereInput | Prisma.PinboardNoteWhereInput[]
  OR?: Prisma.PinboardNoteWhereInput[]
  NOT?: Prisma.PinboardNoteWhereInput | Prisma.PinboardNoteWhereInput[]
  author_user_id?: Prisma.StringFilter<"PinboardNote"> | string
  author_name?: Prisma.StringFilter<"PinboardNote"> | string
  scope_type?: Prisma.StringFilter<"PinboardNote"> | string
  scope_id?: Prisma.StringNullableFilter<"PinboardNote"> | string | null
  body?: Prisma.StringFilter<"PinboardNote"> | string
  color?: Prisma.StringFilter<"PinboardNote"> | string
  is_important?: Prisma.BoolFilter<"PinboardNote"> | boolean
  is_active?: Prisma.BoolFilter<"PinboardNote"> | boolean
  created_at?: Prisma.DateTimeFilter<"PinboardNote"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"PinboardNote"> | Date | string
  expires_at?: Prisma.DateTimeNullableFilter<"PinboardNote"> | Date | string | null
  reads?: Prisma.PinboardNoteReadListRelationFilter
  positions?: Prisma.PinboardNotePositionListRelationFilter
}, "id">

export type PinboardNoteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  author_user_id?: Prisma.SortOrder
  author_name?: Prisma.SortOrder
  scope_type?: Prisma.SortOrder
  scope_id?: Prisma.SortOrderInput | Prisma.SortOrder
  body?: Prisma.SortOrder
  color?: Prisma.SortOrder
  is_important?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PinboardNoteCountOrderByAggregateInput
  _max?: Prisma.PinboardNoteMaxOrderByAggregateInput
  _min?: Prisma.PinboardNoteMinOrderByAggregateInput
}

export type PinboardNoteScalarWhereWithAggregatesInput = {
  AND?: Prisma.PinboardNoteScalarWhereWithAggregatesInput | Prisma.PinboardNoteScalarWhereWithAggregatesInput[]
  OR?: Prisma.PinboardNoteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PinboardNoteScalarWhereWithAggregatesInput | Prisma.PinboardNoteScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PinboardNote"> | string
  author_user_id?: Prisma.StringWithAggregatesFilter<"PinboardNote"> | string
  author_name?: Prisma.StringWithAggregatesFilter<"PinboardNote"> | string
  scope_type?: Prisma.StringWithAggregatesFilter<"PinboardNote"> | string
  scope_id?: Prisma.StringNullableWithAggregatesFilter<"PinboardNote"> | string | null
  body?: Prisma.StringWithAggregatesFilter<"PinboardNote"> | string
  color?: Prisma.StringWithAggregatesFilter<"PinboardNote"> | string
  is_important?: Prisma.BoolWithAggregatesFilter<"PinboardNote"> | boolean
  is_active?: Prisma.BoolWithAggregatesFilter<"PinboardNote"> | boolean
  created_at?: Prisma.DateTimeWithAggregatesFilter<"PinboardNote"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"PinboardNote"> | Date | string
  expires_at?: Prisma.DateTimeNullableWithAggregatesFilter<"PinboardNote"> | Date | string | null
}

export type PinboardNoteCreateInput = {
  id?: string
  author_user_id: string
  author_name: string
  scope_type: string
  scope_id?: string | null
  body: string
  color?: string
  is_important?: boolean
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  expires_at?: Date | string | null
  reads?: Prisma.PinboardNoteReadCreateNestedManyWithoutNoteInput
  positions?: Prisma.PinboardNotePositionCreateNestedManyWithoutNoteInput
}

export type PinboardNoteUncheckedCreateInput = {
  id?: string
  author_user_id: string
  author_name: string
  scope_type: string
  scope_id?: string | null
  body: string
  color?: string
  is_important?: boolean
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  expires_at?: Date | string | null
  reads?: Prisma.PinboardNoteReadUncheckedCreateNestedManyWithoutNoteInput
  positions?: Prisma.PinboardNotePositionUncheckedCreateNestedManyWithoutNoteInput
}

export type PinboardNoteUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  author_name?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  body?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  is_important?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reads?: Prisma.PinboardNoteReadUpdateManyWithoutNoteNestedInput
  positions?: Prisma.PinboardNotePositionUpdateManyWithoutNoteNestedInput
}

export type PinboardNoteUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  author_name?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  body?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  is_important?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reads?: Prisma.PinboardNoteReadUncheckedUpdateManyWithoutNoteNestedInput
  positions?: Prisma.PinboardNotePositionUncheckedUpdateManyWithoutNoteNestedInput
}

export type PinboardNoteCreateManyInput = {
  id?: string
  author_user_id: string
  author_name: string
  scope_type: string
  scope_id?: string | null
  body: string
  color?: string
  is_important?: boolean
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  expires_at?: Date | string | null
}

export type PinboardNoteUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  author_name?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  body?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  is_important?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PinboardNoteUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  author_name?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  body?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  is_important?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PinboardNoteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  author_user_id?: Prisma.SortOrder
  author_name?: Prisma.SortOrder
  scope_type?: Prisma.SortOrder
  scope_id?: Prisma.SortOrder
  body?: Prisma.SortOrder
  color?: Prisma.SortOrder
  is_important?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
}

export type PinboardNoteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  author_user_id?: Prisma.SortOrder
  author_name?: Prisma.SortOrder
  scope_type?: Prisma.SortOrder
  scope_id?: Prisma.SortOrder
  body?: Prisma.SortOrder
  color?: Prisma.SortOrder
  is_important?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
}

export type PinboardNoteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  author_user_id?: Prisma.SortOrder
  author_name?: Prisma.SortOrder
  scope_type?: Prisma.SortOrder
  scope_id?: Prisma.SortOrder
  body?: Prisma.SortOrder
  color?: Prisma.SortOrder
  is_important?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
}

export type PinboardNoteScalarRelationFilter = {
  is?: Prisma.PinboardNoteWhereInput
  isNot?: Prisma.PinboardNoteWhereInput
}

export type PinboardNoteCreateNestedOneWithoutReadsInput = {
  create?: Prisma.XOR<Prisma.PinboardNoteCreateWithoutReadsInput, Prisma.PinboardNoteUncheckedCreateWithoutReadsInput>
  connectOrCreate?: Prisma.PinboardNoteCreateOrConnectWithoutReadsInput
  connect?: Prisma.PinboardNoteWhereUniqueInput
}

export type PinboardNoteUpdateOneRequiredWithoutReadsNestedInput = {
  create?: Prisma.XOR<Prisma.PinboardNoteCreateWithoutReadsInput, Prisma.PinboardNoteUncheckedCreateWithoutReadsInput>
  connectOrCreate?: Prisma.PinboardNoteCreateOrConnectWithoutReadsInput
  upsert?: Prisma.PinboardNoteUpsertWithoutReadsInput
  connect?: Prisma.PinboardNoteWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PinboardNoteUpdateToOneWithWhereWithoutReadsInput, Prisma.PinboardNoteUpdateWithoutReadsInput>, Prisma.PinboardNoteUncheckedUpdateWithoutReadsInput>
}

export type PinboardNoteCreateNestedOneWithoutPositionsInput = {
  create?: Prisma.XOR<Prisma.PinboardNoteCreateWithoutPositionsInput, Prisma.PinboardNoteUncheckedCreateWithoutPositionsInput>
  connectOrCreate?: Prisma.PinboardNoteCreateOrConnectWithoutPositionsInput
  connect?: Prisma.PinboardNoteWhereUniqueInput
}

export type PinboardNoteUpdateOneRequiredWithoutPositionsNestedInput = {
  create?: Prisma.XOR<Prisma.PinboardNoteCreateWithoutPositionsInput, Prisma.PinboardNoteUncheckedCreateWithoutPositionsInput>
  connectOrCreate?: Prisma.PinboardNoteCreateOrConnectWithoutPositionsInput
  upsert?: Prisma.PinboardNoteUpsertWithoutPositionsInput
  connect?: Prisma.PinboardNoteWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PinboardNoteUpdateToOneWithWhereWithoutPositionsInput, Prisma.PinboardNoteUpdateWithoutPositionsInput>, Prisma.PinboardNoteUncheckedUpdateWithoutPositionsInput>
}

export type PinboardNoteCreateWithoutReadsInput = {
  id?: string
  author_user_id: string
  author_name: string
  scope_type: string
  scope_id?: string | null
  body: string
  color?: string
  is_important?: boolean
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  expires_at?: Date | string | null
  positions?: Prisma.PinboardNotePositionCreateNestedManyWithoutNoteInput
}

export type PinboardNoteUncheckedCreateWithoutReadsInput = {
  id?: string
  author_user_id: string
  author_name: string
  scope_type: string
  scope_id?: string | null
  body: string
  color?: string
  is_important?: boolean
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  expires_at?: Date | string | null
  positions?: Prisma.PinboardNotePositionUncheckedCreateNestedManyWithoutNoteInput
}

export type PinboardNoteCreateOrConnectWithoutReadsInput = {
  where: Prisma.PinboardNoteWhereUniqueInput
  create: Prisma.XOR<Prisma.PinboardNoteCreateWithoutReadsInput, Prisma.PinboardNoteUncheckedCreateWithoutReadsInput>
}

export type PinboardNoteUpsertWithoutReadsInput = {
  update: Prisma.XOR<Prisma.PinboardNoteUpdateWithoutReadsInput, Prisma.PinboardNoteUncheckedUpdateWithoutReadsInput>
  create: Prisma.XOR<Prisma.PinboardNoteCreateWithoutReadsInput, Prisma.PinboardNoteUncheckedCreateWithoutReadsInput>
  where?: Prisma.PinboardNoteWhereInput
}

export type PinboardNoteUpdateToOneWithWhereWithoutReadsInput = {
  where?: Prisma.PinboardNoteWhereInput
  data: Prisma.XOR<Prisma.PinboardNoteUpdateWithoutReadsInput, Prisma.PinboardNoteUncheckedUpdateWithoutReadsInput>
}

export type PinboardNoteUpdateWithoutReadsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  author_name?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  body?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  is_important?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  positions?: Prisma.PinboardNotePositionUpdateManyWithoutNoteNestedInput
}

export type PinboardNoteUncheckedUpdateWithoutReadsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  author_name?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  body?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  is_important?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  positions?: Prisma.PinboardNotePositionUncheckedUpdateManyWithoutNoteNestedInput
}

export type PinboardNoteCreateWithoutPositionsInput = {
  id?: string
  author_user_id: string
  author_name: string
  scope_type: string
  scope_id?: string | null
  body: string
  color?: string
  is_important?: boolean
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  expires_at?: Date | string | null
  reads?: Prisma.PinboardNoteReadCreateNestedManyWithoutNoteInput
}

export type PinboardNoteUncheckedCreateWithoutPositionsInput = {
  id?: string
  author_user_id: string
  author_name: string
  scope_type: string
  scope_id?: string | null
  body: string
  color?: string
  is_important?: boolean
  is_active?: boolean
  created_at?: Date | string
  updated_at?: Date | string
  expires_at?: Date | string | null
  reads?: Prisma.PinboardNoteReadUncheckedCreateNestedManyWithoutNoteInput
}

export type PinboardNoteCreateOrConnectWithoutPositionsInput = {
  where: Prisma.PinboardNoteWhereUniqueInput
  create: Prisma.XOR<Prisma.PinboardNoteCreateWithoutPositionsInput, Prisma.PinboardNoteUncheckedCreateWithoutPositionsInput>
}

export type PinboardNoteUpsertWithoutPositionsInput = {
  update: Prisma.XOR<Prisma.PinboardNoteUpdateWithoutPositionsInput, Prisma.PinboardNoteUncheckedUpdateWithoutPositionsInput>
  create: Prisma.XOR<Prisma.PinboardNoteCreateWithoutPositionsInput, Prisma.PinboardNoteUncheckedCreateWithoutPositionsInput>
  where?: Prisma.PinboardNoteWhereInput
}

export type PinboardNoteUpdateToOneWithWhereWithoutPositionsInput = {
  where?: Prisma.PinboardNoteWhereInput
  data: Prisma.XOR<Prisma.PinboardNoteUpdateWithoutPositionsInput, Prisma.PinboardNoteUncheckedUpdateWithoutPositionsInput>
}

export type PinboardNoteUpdateWithoutPositionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  author_name?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  body?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  is_important?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reads?: Prisma.PinboardNoteReadUpdateManyWithoutNoteNestedInput
}

export type PinboardNoteUncheckedUpdateWithoutPositionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  author_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  author_name?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  body?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  is_important?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reads?: Prisma.PinboardNoteReadUncheckedUpdateManyWithoutNoteNestedInput
}


/**
 * Count Type PinboardNoteCountOutputType
 */

export type PinboardNoteCountOutputType = {
  reads: number
  positions: number
}

export type PinboardNoteCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reads?: boolean | PinboardNoteCountOutputTypeCountReadsArgs
  positions?: boolean | PinboardNoteCountOutputTypeCountPositionsArgs
}

/**
 * PinboardNoteCountOutputType without action
 */
export type PinboardNoteCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteCountOutputType
   */
  select?: Prisma.PinboardNoteCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PinboardNoteCountOutputType without action
 */
export type PinboardNoteCountOutputTypeCountReadsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PinboardNoteReadWhereInput
}

/**
 * PinboardNoteCountOutputType without action
 */
export type PinboardNoteCountOutputTypeCountPositionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PinboardNotePositionWhereInput
}


export type PinboardNoteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  author_user_id?: boolean
  author_name?: boolean
  scope_type?: boolean
  scope_id?: boolean
  body?: boolean
  color?: boolean
  is_important?: boolean
  is_active?: boolean
  created_at?: boolean
  updated_at?: boolean
  expires_at?: boolean
  reads?: boolean | Prisma.PinboardNote$readsArgs<ExtArgs>
  positions?: boolean | Prisma.PinboardNote$positionsArgs<ExtArgs>
  _count?: boolean | Prisma.PinboardNoteCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pinboardNote"]>

export type PinboardNoteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  author_user_id?: boolean
  author_name?: boolean
  scope_type?: boolean
  scope_id?: boolean
  body?: boolean
  color?: boolean
  is_important?: boolean
  is_active?: boolean
  created_at?: boolean
  updated_at?: boolean
  expires_at?: boolean
}, ExtArgs["result"]["pinboardNote"]>

export type PinboardNoteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  author_user_id?: boolean
  author_name?: boolean
  scope_type?: boolean
  scope_id?: boolean
  body?: boolean
  color?: boolean
  is_important?: boolean
  is_active?: boolean
  created_at?: boolean
  updated_at?: boolean
  expires_at?: boolean
}, ExtArgs["result"]["pinboardNote"]>

export type PinboardNoteSelectScalar = {
  id?: boolean
  author_user_id?: boolean
  author_name?: boolean
  scope_type?: boolean
  scope_id?: boolean
  body?: boolean
  color?: boolean
  is_important?: boolean
  is_active?: boolean
  created_at?: boolean
  updated_at?: boolean
  expires_at?: boolean
}

export type PinboardNoteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "author_user_id" | "author_name" | "scope_type" | "scope_id" | "body" | "color" | "is_important" | "is_active" | "created_at" | "updated_at" | "expires_at", ExtArgs["result"]["pinboardNote"]>
export type PinboardNoteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reads?: boolean | Prisma.PinboardNote$readsArgs<ExtArgs>
  positions?: boolean | Prisma.PinboardNote$positionsArgs<ExtArgs>
  _count?: boolean | Prisma.PinboardNoteCountOutputTypeDefaultArgs<ExtArgs>
}
export type PinboardNoteIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PinboardNoteIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PinboardNotePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PinboardNote"
  objects: {
    reads: Prisma.$PinboardNoteReadPayload<ExtArgs>[]
    positions: Prisma.$PinboardNotePositionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    /**
     * user_id of the author. No FK (auth module).
     */
    author_user_id: string
    /**
     * Snapshot of the author's username, so notes stay readable even if the
     * account is later renamed or removed.
     */
    author_name: string
    /**
     * "GLOBAL" (everyone), "ROLE" (scope_id = role_id) or "USER"
     * (scope_id = user_id). Kept as a string, not an enum, so new scopes can
     * be added without a migration.
     */
    scope_type: string
    /**
     * role_id (ROLE) or user_id (USER); null for GLOBAL.
     */
    scope_id: string | null
    body: string
    color: string
    is_important: boolean
    is_active: boolean
    created_at: Date
    updated_at: Date
    expires_at: Date | null
  }, ExtArgs["result"]["pinboardNote"]>
  composites: {}
}

export type PinboardNoteGetPayload<S extends boolean | null | undefined | PinboardNoteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PinboardNotePayload, S>

export type PinboardNoteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PinboardNoteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PinboardNoteCountAggregateInputType | true
  }

export interface PinboardNoteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PinboardNote'], meta: { name: 'PinboardNote' } }
  /**
   * Find zero or one PinboardNote that matches the filter.
   * @param {PinboardNoteFindUniqueArgs} args - Arguments to find a PinboardNote
   * @example
   * // Get one PinboardNote
   * const pinboardNote = await prisma.pinboardNote.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PinboardNoteFindUniqueArgs>(args: Prisma.SelectSubset<T, PinboardNoteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteClient<runtime.Types.Result.GetResult<Prisma.$PinboardNotePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PinboardNote that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PinboardNoteFindUniqueOrThrowArgs} args - Arguments to find a PinboardNote
   * @example
   * // Get one PinboardNote
   * const pinboardNote = await prisma.pinboardNote.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PinboardNoteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PinboardNoteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteClient<runtime.Types.Result.GetResult<Prisma.$PinboardNotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PinboardNote that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteFindFirstArgs} args - Arguments to find a PinboardNote
   * @example
   * // Get one PinboardNote
   * const pinboardNote = await prisma.pinboardNote.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PinboardNoteFindFirstArgs>(args?: Prisma.SelectSubset<T, PinboardNoteFindFirstArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteClient<runtime.Types.Result.GetResult<Prisma.$PinboardNotePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PinboardNote that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteFindFirstOrThrowArgs} args - Arguments to find a PinboardNote
   * @example
   * // Get one PinboardNote
   * const pinboardNote = await prisma.pinboardNote.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PinboardNoteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PinboardNoteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteClient<runtime.Types.Result.GetResult<Prisma.$PinboardNotePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PinboardNotes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PinboardNotes
   * const pinboardNotes = await prisma.pinboardNote.findMany()
   * 
   * // Get first 10 PinboardNotes
   * const pinboardNotes = await prisma.pinboardNote.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pinboardNoteWithIdOnly = await prisma.pinboardNote.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PinboardNoteFindManyArgs>(args?: Prisma.SelectSubset<T, PinboardNoteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PinboardNotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PinboardNote.
   * @param {PinboardNoteCreateArgs} args - Arguments to create a PinboardNote.
   * @example
   * // Create one PinboardNote
   * const PinboardNote = await prisma.pinboardNote.create({
   *   data: {
   *     // ... data to create a PinboardNote
   *   }
   * })
   * 
   */
  create<T extends PinboardNoteCreateArgs>(args: Prisma.SelectSubset<T, PinboardNoteCreateArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteClient<runtime.Types.Result.GetResult<Prisma.$PinboardNotePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PinboardNotes.
   * @param {PinboardNoteCreateManyArgs} args - Arguments to create many PinboardNotes.
   * @example
   * // Create many PinboardNotes
   * const pinboardNote = await prisma.pinboardNote.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PinboardNoteCreateManyArgs>(args?: Prisma.SelectSubset<T, PinboardNoteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PinboardNotes and returns the data saved in the database.
   * @param {PinboardNoteCreateManyAndReturnArgs} args - Arguments to create many PinboardNotes.
   * @example
   * // Create many PinboardNotes
   * const pinboardNote = await prisma.pinboardNote.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PinboardNotes and only return the `id`
   * const pinboardNoteWithIdOnly = await prisma.pinboardNote.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PinboardNoteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PinboardNoteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PinboardNotePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PinboardNote.
   * @param {PinboardNoteDeleteArgs} args - Arguments to delete one PinboardNote.
   * @example
   * // Delete one PinboardNote
   * const PinboardNote = await prisma.pinboardNote.delete({
   *   where: {
   *     // ... filter to delete one PinboardNote
   *   }
   * })
   * 
   */
  delete<T extends PinboardNoteDeleteArgs>(args: Prisma.SelectSubset<T, PinboardNoteDeleteArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteClient<runtime.Types.Result.GetResult<Prisma.$PinboardNotePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PinboardNote.
   * @param {PinboardNoteUpdateArgs} args - Arguments to update one PinboardNote.
   * @example
   * // Update one PinboardNote
   * const pinboardNote = await prisma.pinboardNote.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PinboardNoteUpdateArgs>(args: Prisma.SelectSubset<T, PinboardNoteUpdateArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteClient<runtime.Types.Result.GetResult<Prisma.$PinboardNotePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PinboardNotes.
   * @param {PinboardNoteDeleteManyArgs} args - Arguments to filter PinboardNotes to delete.
   * @example
   * // Delete a few PinboardNotes
   * const { count } = await prisma.pinboardNote.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PinboardNoteDeleteManyArgs>(args?: Prisma.SelectSubset<T, PinboardNoteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PinboardNotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PinboardNotes
   * const pinboardNote = await prisma.pinboardNote.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PinboardNoteUpdateManyArgs>(args: Prisma.SelectSubset<T, PinboardNoteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PinboardNotes and returns the data updated in the database.
   * @param {PinboardNoteUpdateManyAndReturnArgs} args - Arguments to update many PinboardNotes.
   * @example
   * // Update many PinboardNotes
   * const pinboardNote = await prisma.pinboardNote.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PinboardNotes and only return the `id`
   * const pinboardNoteWithIdOnly = await prisma.pinboardNote.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PinboardNoteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PinboardNoteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PinboardNotePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PinboardNote.
   * @param {PinboardNoteUpsertArgs} args - Arguments to update or create a PinboardNote.
   * @example
   * // Update or create a PinboardNote
   * const pinboardNote = await prisma.pinboardNote.upsert({
   *   create: {
   *     // ... data to create a PinboardNote
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PinboardNote we want to update
   *   }
   * })
   */
  upsert<T extends PinboardNoteUpsertArgs>(args: Prisma.SelectSubset<T, PinboardNoteUpsertArgs<ExtArgs>>): Prisma.Prisma__PinboardNoteClient<runtime.Types.Result.GetResult<Prisma.$PinboardNotePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PinboardNotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteCountArgs} args - Arguments to filter PinboardNotes to count.
   * @example
   * // Count the number of PinboardNotes
   * const count = await prisma.pinboardNote.count({
   *   where: {
   *     // ... the filter for the PinboardNotes we want to count
   *   }
   * })
  **/
  count<T extends PinboardNoteCountArgs>(
    args?: Prisma.Subset<T, PinboardNoteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PinboardNoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PinboardNote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PinboardNoteAggregateArgs>(args: Prisma.Subset<T, PinboardNoteAggregateArgs>): Prisma.PrismaPromise<GetPinboardNoteAggregateType<T>>

  /**
   * Group by PinboardNote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PinboardNoteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PinboardNoteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PinboardNoteGroupByArgs['orderBy'] }
      : { orderBy?: PinboardNoteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PinboardNoteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPinboardNoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PinboardNote model
 */
readonly fields: PinboardNoteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PinboardNote.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PinboardNoteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  reads<T extends Prisma.PinboardNote$readsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PinboardNote$readsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PinboardNoteReadPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  positions<T extends Prisma.PinboardNote$positionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PinboardNote$positionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PinboardNotePositionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PinboardNote model
 */
export interface PinboardNoteFieldRefs {
  readonly id: Prisma.FieldRef<"PinboardNote", 'String'>
  readonly author_user_id: Prisma.FieldRef<"PinboardNote", 'String'>
  readonly author_name: Prisma.FieldRef<"PinboardNote", 'String'>
  readonly scope_type: Prisma.FieldRef<"PinboardNote", 'String'>
  readonly scope_id: Prisma.FieldRef<"PinboardNote", 'String'>
  readonly body: Prisma.FieldRef<"PinboardNote", 'String'>
  readonly color: Prisma.FieldRef<"PinboardNote", 'String'>
  readonly is_important: Prisma.FieldRef<"PinboardNote", 'Boolean'>
  readonly is_active: Prisma.FieldRef<"PinboardNote", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"PinboardNote", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"PinboardNote", 'DateTime'>
  readonly expires_at: Prisma.FieldRef<"PinboardNote", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PinboardNote findUnique
 */
export type PinboardNoteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNote
   */
  select?: Prisma.PinboardNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNote
   */
  omit?: Prisma.PinboardNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteInclude<ExtArgs> | null
  /**
   * Filter, which PinboardNote to fetch.
   */
  where: Prisma.PinboardNoteWhereUniqueInput
}

/**
 * PinboardNote findUniqueOrThrow
 */
export type PinboardNoteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNote
   */
  select?: Prisma.PinboardNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNote
   */
  omit?: Prisma.PinboardNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteInclude<ExtArgs> | null
  /**
   * Filter, which PinboardNote to fetch.
   */
  where: Prisma.PinboardNoteWhereUniqueInput
}

/**
 * PinboardNote findFirst
 */
export type PinboardNoteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNote
   */
  select?: Prisma.PinboardNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNote
   */
  omit?: Prisma.PinboardNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteInclude<ExtArgs> | null
  /**
   * Filter, which PinboardNote to fetch.
   */
  where?: Prisma.PinboardNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PinboardNotes to fetch.
   */
  orderBy?: Prisma.PinboardNoteOrderByWithRelationInput | Prisma.PinboardNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PinboardNotes.
   */
  cursor?: Prisma.PinboardNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PinboardNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PinboardNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PinboardNotes.
   */
  distinct?: Prisma.PinboardNoteScalarFieldEnum | Prisma.PinboardNoteScalarFieldEnum[]
}

/**
 * PinboardNote findFirstOrThrow
 */
export type PinboardNoteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNote
   */
  select?: Prisma.PinboardNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNote
   */
  omit?: Prisma.PinboardNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteInclude<ExtArgs> | null
  /**
   * Filter, which PinboardNote to fetch.
   */
  where?: Prisma.PinboardNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PinboardNotes to fetch.
   */
  orderBy?: Prisma.PinboardNoteOrderByWithRelationInput | Prisma.PinboardNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PinboardNotes.
   */
  cursor?: Prisma.PinboardNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PinboardNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PinboardNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PinboardNotes.
   */
  distinct?: Prisma.PinboardNoteScalarFieldEnum | Prisma.PinboardNoteScalarFieldEnum[]
}

/**
 * PinboardNote findMany
 */
export type PinboardNoteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNote
   */
  select?: Prisma.PinboardNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNote
   */
  omit?: Prisma.PinboardNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteInclude<ExtArgs> | null
  /**
   * Filter, which PinboardNotes to fetch.
   */
  where?: Prisma.PinboardNoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PinboardNotes to fetch.
   */
  orderBy?: Prisma.PinboardNoteOrderByWithRelationInput | Prisma.PinboardNoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PinboardNotes.
   */
  cursor?: Prisma.PinboardNoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PinboardNotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PinboardNotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PinboardNotes.
   */
  distinct?: Prisma.PinboardNoteScalarFieldEnum | Prisma.PinboardNoteScalarFieldEnum[]
}

/**
 * PinboardNote create
 */
export type PinboardNoteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNote
   */
  select?: Prisma.PinboardNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNote
   */
  omit?: Prisma.PinboardNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteInclude<ExtArgs> | null
  /**
   * The data needed to create a PinboardNote.
   */
  data: Prisma.XOR<Prisma.PinboardNoteCreateInput, Prisma.PinboardNoteUncheckedCreateInput>
}

/**
 * PinboardNote createMany
 */
export type PinboardNoteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PinboardNotes.
   */
  data: Prisma.PinboardNoteCreateManyInput | Prisma.PinboardNoteCreateManyInput[]
}

/**
 * PinboardNote createManyAndReturn
 */
export type PinboardNoteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNote
   */
  select?: Prisma.PinboardNoteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNote
   */
  omit?: Prisma.PinboardNoteOmit<ExtArgs> | null
  /**
   * The data used to create many PinboardNotes.
   */
  data: Prisma.PinboardNoteCreateManyInput | Prisma.PinboardNoteCreateManyInput[]
}

/**
 * PinboardNote update
 */
export type PinboardNoteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNote
   */
  select?: Prisma.PinboardNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNote
   */
  omit?: Prisma.PinboardNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteInclude<ExtArgs> | null
  /**
   * The data needed to update a PinboardNote.
   */
  data: Prisma.XOR<Prisma.PinboardNoteUpdateInput, Prisma.PinboardNoteUncheckedUpdateInput>
  /**
   * Choose, which PinboardNote to update.
   */
  where: Prisma.PinboardNoteWhereUniqueInput
}

/**
 * PinboardNote updateMany
 */
export type PinboardNoteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PinboardNotes.
   */
  data: Prisma.XOR<Prisma.PinboardNoteUpdateManyMutationInput, Prisma.PinboardNoteUncheckedUpdateManyInput>
  /**
   * Filter which PinboardNotes to update
   */
  where?: Prisma.PinboardNoteWhereInput
  /**
   * Limit how many PinboardNotes to update.
   */
  limit?: number
}

/**
 * PinboardNote updateManyAndReturn
 */
export type PinboardNoteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNote
   */
  select?: Prisma.PinboardNoteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNote
   */
  omit?: Prisma.PinboardNoteOmit<ExtArgs> | null
  /**
   * The data used to update PinboardNotes.
   */
  data: Prisma.XOR<Prisma.PinboardNoteUpdateManyMutationInput, Prisma.PinboardNoteUncheckedUpdateManyInput>
  /**
   * Filter which PinboardNotes to update
   */
  where?: Prisma.PinboardNoteWhereInput
  /**
   * Limit how many PinboardNotes to update.
   */
  limit?: number
}

/**
 * PinboardNote upsert
 */
export type PinboardNoteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNote
   */
  select?: Prisma.PinboardNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNote
   */
  omit?: Prisma.PinboardNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteInclude<ExtArgs> | null
  /**
   * The filter to search for the PinboardNote to update in case it exists.
   */
  where: Prisma.PinboardNoteWhereUniqueInput
  /**
   * In case the PinboardNote found by the `where` argument doesn't exist, create a new PinboardNote with this data.
   */
  create: Prisma.XOR<Prisma.PinboardNoteCreateInput, Prisma.PinboardNoteUncheckedCreateInput>
  /**
   * In case the PinboardNote was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PinboardNoteUpdateInput, Prisma.PinboardNoteUncheckedUpdateInput>
}

/**
 * PinboardNote delete
 */
export type PinboardNoteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNote
   */
  select?: Prisma.PinboardNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNote
   */
  omit?: Prisma.PinboardNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteInclude<ExtArgs> | null
  /**
   * Filter which PinboardNote to delete.
   */
  where: Prisma.PinboardNoteWhereUniqueInput
}

/**
 * PinboardNote deleteMany
 */
export type PinboardNoteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PinboardNotes to delete
   */
  where?: Prisma.PinboardNoteWhereInput
  /**
   * Limit how many PinboardNotes to delete.
   */
  limit?: number
}

/**
 * PinboardNote.reads
 */
export type PinboardNote$readsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNoteRead
   */
  select?: Prisma.PinboardNoteReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNoteRead
   */
  omit?: Prisma.PinboardNoteReadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteReadInclude<ExtArgs> | null
  where?: Prisma.PinboardNoteReadWhereInput
  orderBy?: Prisma.PinboardNoteReadOrderByWithRelationInput | Prisma.PinboardNoteReadOrderByWithRelationInput[]
  cursor?: Prisma.PinboardNoteReadWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PinboardNoteReadScalarFieldEnum | Prisma.PinboardNoteReadScalarFieldEnum[]
}

/**
 * PinboardNote.positions
 */
export type PinboardNote$positionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNotePosition
   */
  select?: Prisma.PinboardNotePositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNotePosition
   */
  omit?: Prisma.PinboardNotePositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNotePositionInclude<ExtArgs> | null
  where?: Prisma.PinboardNotePositionWhereInput
  orderBy?: Prisma.PinboardNotePositionOrderByWithRelationInput | Prisma.PinboardNotePositionOrderByWithRelationInput[]
  cursor?: Prisma.PinboardNotePositionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PinboardNotePositionScalarFieldEnum | Prisma.PinboardNotePositionScalarFieldEnum[]
}

/**
 * PinboardNote without action
 */
export type PinboardNoteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PinboardNote
   */
  select?: Prisma.PinboardNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PinboardNote
   */
  omit?: Prisma.PinboardNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PinboardNoteInclude<ExtArgs> | null
}
