
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Recipe` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Recipe
 * 
 */
export type RecipeModel = runtime.Types.Result.DefaultSelection<Prisma.$RecipePayload>

export type AggregateRecipe = {
  _count: RecipeCountAggregateOutputType | null
  _min: RecipeMinAggregateOutputType | null
  _max: RecipeMaxAggregateOutputType | null
}

export type RecipeMinAggregateOutputType = {
  id: string | null
  slug: string | null
  created: Date | null
  updated: Date | null
  owner_user_id: string | null
  template_id: string | null
  compiledAt: Date | null
}

export type RecipeMaxAggregateOutputType = {
  id: string | null
  slug: string | null
  created: Date | null
  updated: Date | null
  owner_user_id: string | null
  template_id: string | null
  compiledAt: Date | null
}

export type RecipeCountAggregateOutputType = {
  id: number
  slug: number
  created: number
  updated: number
  owner_user_id: number
  template_id: number
  definition:PrismaJson.Recipe_definition
  plugins:PrismaJson.Recipe_plugins
  compiledAt: number
  _all: number
}


export type RecipeMinAggregateInputType = {
  id?: true
  slug?: true
  created?: true
  updated?: true
  owner_user_id?: true
  template_id?: true
  compiledAt?: true
}

export type RecipeMaxAggregateInputType = {
  id?: true
  slug?: true
  created?: true
  updated?: true
  owner_user_id?: true
  template_id?: true
  compiledAt?: true
}

export type RecipeCountAggregateInputType = {
  id?: true
  slug?: true
  created?: true
  updated?: true
  owner_user_id?: true
  template_id?: true
  definition?: true
  plugins?: true
  compiledAt?: true
  _all?: true
}

export type RecipeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Recipe to aggregate.
   */
  where?: Prisma.RecipeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Recipes to fetch.
   */
  orderBy?: Prisma.RecipeOrderByWithRelationInput | Prisma.RecipeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RecipeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Recipes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Recipes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Recipes
  **/
  _count?: true | RecipeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RecipeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RecipeMaxAggregateInputType
}

export type GetRecipeAggregateType<T extends RecipeAggregateArgs> = {
      [P in keyof T & keyof AggregateRecipe]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRecipe[P]>
    : Prisma.GetScalarType<T[P], AggregateRecipe[P]>
}




export type RecipeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipeWhereInput
  orderBy?: Prisma.RecipeOrderByWithAggregationInput | Prisma.RecipeOrderByWithAggregationInput[]
  by: Prisma.RecipeScalarFieldEnum[] | Prisma.RecipeScalarFieldEnum
  having?: Prisma.RecipeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RecipeCountAggregateInputType | true
  _min?: RecipeMinAggregateInputType
  _max?: RecipeMaxAggregateInputType
}

export type RecipeGroupByOutputType = {
  id: string
  slug: string
  created: Date
  updated: Date
  owner_user_id: string | null
  template_id: string
  definition:PrismaJson.Recipe_definition
  plugins:PrismaJson.Recipe_plugins
  compiledAt: Date
  _count: RecipeCountAggregateOutputType | null
  _min: RecipeMinAggregateOutputType | null
  _max: RecipeMaxAggregateOutputType | null
}

export type GetRecipeGroupByPayload<T extends RecipeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RecipeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RecipeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RecipeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RecipeGroupByOutputType[P]>
      }
    >
  >



export type RecipeWhereInput = {
  AND?: Prisma.RecipeWhereInput | Prisma.RecipeWhereInput[]
  OR?: Prisma.RecipeWhereInput[]
  NOT?: Prisma.RecipeWhereInput | Prisma.RecipeWhereInput[]
  id?: Prisma.StringFilter<"Recipe"> | string
  slug?: Prisma.StringFilter<"Recipe"> | string
  created?: Prisma.DateTimeFilter<"Recipe"> | Date | string
  updated?: Prisma.DateTimeFilter<"Recipe"> | Date | string
  owner_user_id?: Prisma.StringNullableFilter<"Recipe"> | string | null
  template_id?: Prisma.StringFilter<"Recipe"> | string
  definition?: Prisma.JsonFilter<"Recipe">
  plugins?: Prisma.JsonFilter<"Recipe">
  compiledAt?: Prisma.DateTimeFilter<"Recipe"> | Date | string
  template?: Prisma.XOR<Prisma.TemplateScalarRelationFilter, Prisma.TemplateWhereInput>
  recipe_bags?: Prisma.RecipeBagListRelationFilter
  permissions?: Prisma.RecipePermissionListRelationFilter
}

export type RecipeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  template_id?: Prisma.SortOrder
  definition?: Prisma.SortOrder
  plugins?: Prisma.SortOrder
  compiledAt?: Prisma.SortOrder
  template?: Prisma.TemplateOrderByWithRelationInput
  recipe_bags?: Prisma.RecipeBagOrderByRelationAggregateInput
  permissions?: Prisma.RecipePermissionOrderByRelationAggregateInput
}

export type RecipeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.RecipeWhereInput | Prisma.RecipeWhereInput[]
  OR?: Prisma.RecipeWhereInput[]
  NOT?: Prisma.RecipeWhereInput | Prisma.RecipeWhereInput[]
  created?: Prisma.DateTimeFilter<"Recipe"> | Date | string
  updated?: Prisma.DateTimeFilter<"Recipe"> | Date | string
  owner_user_id?: Prisma.StringNullableFilter<"Recipe"> | string | null
  template_id?: Prisma.StringFilter<"Recipe"> | string
  definition?: Prisma.JsonFilter<"Recipe">
  plugins?: Prisma.JsonFilter<"Recipe">
  compiledAt?: Prisma.DateTimeFilter<"Recipe"> | Date | string
  template?: Prisma.XOR<Prisma.TemplateScalarRelationFilter, Prisma.TemplateWhereInput>
  recipe_bags?: Prisma.RecipeBagListRelationFilter
  permissions?: Prisma.RecipePermissionListRelationFilter
}, "id" | "slug">

export type RecipeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  template_id?: Prisma.SortOrder
  definition?: Prisma.SortOrder
  plugins?: Prisma.SortOrder
  compiledAt?: Prisma.SortOrder
  _count?: Prisma.RecipeCountOrderByAggregateInput
  _max?: Prisma.RecipeMaxOrderByAggregateInput
  _min?: Prisma.RecipeMinOrderByAggregateInput
}

export type RecipeScalarWhereWithAggregatesInput = {
  AND?: Prisma.RecipeScalarWhereWithAggregatesInput | Prisma.RecipeScalarWhereWithAggregatesInput[]
  OR?: Prisma.RecipeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RecipeScalarWhereWithAggregatesInput | Prisma.RecipeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Recipe"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Recipe"> | string
  created?: Prisma.DateTimeWithAggregatesFilter<"Recipe"> | Date | string
  updated?: Prisma.DateTimeWithAggregatesFilter<"Recipe"> | Date | string
  owner_user_id?: Prisma.StringNullableWithAggregatesFilter<"Recipe"> | string | null
  template_id?: Prisma.StringWithAggregatesFilter<"Recipe"> | string
  definition?: Prisma.JsonWithAggregatesFilter<"Recipe">
  plugins?: Prisma.JsonWithAggregatesFilter<"Recipe">
  compiledAt?: Prisma.DateTimeWithAggregatesFilter<"Recipe"> | Date | string
}

export type RecipeCreateInput = {
  id?: string
  slug: string
  created?: Date | string
  updated?: Date | string
  owner_user_id?: string | null
  definition:PrismaJson.Recipe_definition
  plugins:PrismaJson.Recipe_plugins
  compiledAt: Date | string
  template: Prisma.TemplateCreateNestedOneWithoutRecipesInput
  recipe_bags?: Prisma.RecipeBagCreateNestedManyWithoutRecipeInput
  permissions?: Prisma.RecipePermissionCreateNestedManyWithoutRecipeInput
}

export type RecipeUncheckedCreateInput = {
  id?: string
  slug: string
  created?: Date | string
  updated?: Date | string
  owner_user_id?: string | null
  template_id: string
  definition:PrismaJson.Recipe_definition
  plugins:PrismaJson.Recipe_plugins
  compiledAt: Date | string
  recipe_bags?: Prisma.RecipeBagUncheckedCreateNestedManyWithoutRecipeInput
  permissions?: Prisma.RecipePermissionUncheckedCreateNestedManyWithoutRecipeInput
}

export type RecipeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  definition?:PrismaJson.Recipe_definition
  plugins?:PrismaJson.Recipe_plugins
  compiledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  template?: Prisma.TemplateUpdateOneRequiredWithoutRecipesNestedInput
  recipe_bags?: Prisma.RecipeBagUpdateManyWithoutRecipeNestedInput
  permissions?: Prisma.RecipePermissionUpdateManyWithoutRecipeNestedInput
}

export type RecipeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  template_id?: Prisma.StringFieldUpdateOperationsInput | string
  definition?:PrismaJson.Recipe_definition
  plugins?:PrismaJson.Recipe_plugins
  compiledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  recipe_bags?: Prisma.RecipeBagUncheckedUpdateManyWithoutRecipeNestedInput
  permissions?: Prisma.RecipePermissionUncheckedUpdateManyWithoutRecipeNestedInput
}

export type RecipeCreateManyInput = {
  id?: string
  slug: string
  created?: Date | string
  updated?: Date | string
  owner_user_id?: string | null
  template_id: string
  definition:PrismaJson.Recipe_definition
  plugins:PrismaJson.Recipe_plugins
  compiledAt: Date | string
}

export type RecipeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  definition?:PrismaJson.Recipe_definition
  plugins?:PrismaJson.Recipe_plugins
  compiledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecipeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  template_id?: Prisma.StringFieldUpdateOperationsInput | string
  definition?:PrismaJson.Recipe_definition
  plugins?:PrismaJson.Recipe_plugins
  compiledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecipeListRelationFilter = {
  every?: Prisma.RecipeWhereInput
  some?: Prisma.RecipeWhereInput
  none?: Prisma.RecipeWhereInput
}

export type RecipeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RecipeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrder
  template_id?: Prisma.SortOrder
  definition?: Prisma.SortOrder
  plugins?: Prisma.SortOrder
  compiledAt?: Prisma.SortOrder
}

export type RecipeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrder
  template_id?: Prisma.SortOrder
  compiledAt?: Prisma.SortOrder
}

export type RecipeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  owner_user_id?: Prisma.SortOrder
  template_id?: Prisma.SortOrder
  compiledAt?: Prisma.SortOrder
}

export type RecipeScalarRelationFilter = {
  is?: Prisma.RecipeWhereInput
  isNot?: Prisma.RecipeWhereInput
}

export type RecipeCreateNestedManyWithoutTemplateInput = {
  create?: Prisma.XOR<Prisma.RecipeCreateWithoutTemplateInput, Prisma.RecipeUncheckedCreateWithoutTemplateInput> | Prisma.RecipeCreateWithoutTemplateInput[] | Prisma.RecipeUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.RecipeCreateOrConnectWithoutTemplateInput | Prisma.RecipeCreateOrConnectWithoutTemplateInput[]
  createMany?: Prisma.RecipeCreateManyTemplateInputEnvelope
  connect?: Prisma.RecipeWhereUniqueInput | Prisma.RecipeWhereUniqueInput[]
}

export type RecipeUncheckedCreateNestedManyWithoutTemplateInput = {
  create?: Prisma.XOR<Prisma.RecipeCreateWithoutTemplateInput, Prisma.RecipeUncheckedCreateWithoutTemplateInput> | Prisma.RecipeCreateWithoutTemplateInput[] | Prisma.RecipeUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.RecipeCreateOrConnectWithoutTemplateInput | Prisma.RecipeCreateOrConnectWithoutTemplateInput[]
  createMany?: Prisma.RecipeCreateManyTemplateInputEnvelope
  connect?: Prisma.RecipeWhereUniqueInput | Prisma.RecipeWhereUniqueInput[]
}

export type RecipeUpdateManyWithoutTemplateNestedInput = {
  create?: Prisma.XOR<Prisma.RecipeCreateWithoutTemplateInput, Prisma.RecipeUncheckedCreateWithoutTemplateInput> | Prisma.RecipeCreateWithoutTemplateInput[] | Prisma.RecipeUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.RecipeCreateOrConnectWithoutTemplateInput | Prisma.RecipeCreateOrConnectWithoutTemplateInput[]
  upsert?: Prisma.RecipeUpsertWithWhereUniqueWithoutTemplateInput | Prisma.RecipeUpsertWithWhereUniqueWithoutTemplateInput[]
  createMany?: Prisma.RecipeCreateManyTemplateInputEnvelope
  set?: Prisma.RecipeWhereUniqueInput | Prisma.RecipeWhereUniqueInput[]
  disconnect?: Prisma.RecipeWhereUniqueInput | Prisma.RecipeWhereUniqueInput[]
  delete?: Prisma.RecipeWhereUniqueInput | Prisma.RecipeWhereUniqueInput[]
  connect?: Prisma.RecipeWhereUniqueInput | Prisma.RecipeWhereUniqueInput[]
  update?: Prisma.RecipeUpdateWithWhereUniqueWithoutTemplateInput | Prisma.RecipeUpdateWithWhereUniqueWithoutTemplateInput[]
  updateMany?: Prisma.RecipeUpdateManyWithWhereWithoutTemplateInput | Prisma.RecipeUpdateManyWithWhereWithoutTemplateInput[]
  deleteMany?: Prisma.RecipeScalarWhereInput | Prisma.RecipeScalarWhereInput[]
}

export type RecipeUncheckedUpdateManyWithoutTemplateNestedInput = {
  create?: Prisma.XOR<Prisma.RecipeCreateWithoutTemplateInput, Prisma.RecipeUncheckedCreateWithoutTemplateInput> | Prisma.RecipeCreateWithoutTemplateInput[] | Prisma.RecipeUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.RecipeCreateOrConnectWithoutTemplateInput | Prisma.RecipeCreateOrConnectWithoutTemplateInput[]
  upsert?: Prisma.RecipeUpsertWithWhereUniqueWithoutTemplateInput | Prisma.RecipeUpsertWithWhereUniqueWithoutTemplateInput[]
  createMany?: Prisma.RecipeCreateManyTemplateInputEnvelope
  set?: Prisma.RecipeWhereUniqueInput | Prisma.RecipeWhereUniqueInput[]
  disconnect?: Prisma.RecipeWhereUniqueInput | Prisma.RecipeWhereUniqueInput[]
  delete?: Prisma.RecipeWhereUniqueInput | Prisma.RecipeWhereUniqueInput[]
  connect?: Prisma.RecipeWhereUniqueInput | Prisma.RecipeWhereUniqueInput[]
  update?: Prisma.RecipeUpdateWithWhereUniqueWithoutTemplateInput | Prisma.RecipeUpdateWithWhereUniqueWithoutTemplateInput[]
  updateMany?: Prisma.RecipeUpdateManyWithWhereWithoutTemplateInput | Prisma.RecipeUpdateManyWithWhereWithoutTemplateInput[]
  deleteMany?: Prisma.RecipeScalarWhereInput | Prisma.RecipeScalarWhereInput[]
}

export type RecipeCreateNestedOneWithoutPermissionsInput = {
  create?: Prisma.XOR<Prisma.RecipeCreateWithoutPermissionsInput, Prisma.RecipeUncheckedCreateWithoutPermissionsInput>
  connectOrCreate?: Prisma.RecipeCreateOrConnectWithoutPermissionsInput
  connect?: Prisma.RecipeWhereUniqueInput
}

export type RecipeUpdateOneRequiredWithoutPermissionsNestedInput = {
  create?: Prisma.XOR<Prisma.RecipeCreateWithoutPermissionsInput, Prisma.RecipeUncheckedCreateWithoutPermissionsInput>
  connectOrCreate?: Prisma.RecipeCreateOrConnectWithoutPermissionsInput
  upsert?: Prisma.RecipeUpsertWithoutPermissionsInput
  connect?: Prisma.RecipeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RecipeUpdateToOneWithWhereWithoutPermissionsInput, Prisma.RecipeUpdateWithoutPermissionsInput>, Prisma.RecipeUncheckedUpdateWithoutPermissionsInput>
}

export type RecipeCreateNestedOneWithoutRecipe_bagsInput = {
  create?: Prisma.XOR<Prisma.RecipeCreateWithoutRecipe_bagsInput, Prisma.RecipeUncheckedCreateWithoutRecipe_bagsInput>
  connectOrCreate?: Prisma.RecipeCreateOrConnectWithoutRecipe_bagsInput
  connect?: Prisma.RecipeWhereUniqueInput
}

export type RecipeUpdateOneRequiredWithoutRecipe_bagsNestedInput = {
  create?: Prisma.XOR<Prisma.RecipeCreateWithoutRecipe_bagsInput, Prisma.RecipeUncheckedCreateWithoutRecipe_bagsInput>
  connectOrCreate?: Prisma.RecipeCreateOrConnectWithoutRecipe_bagsInput
  upsert?: Prisma.RecipeUpsertWithoutRecipe_bagsInput
  connect?: Prisma.RecipeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RecipeUpdateToOneWithWhereWithoutRecipe_bagsInput, Prisma.RecipeUpdateWithoutRecipe_bagsInput>, Prisma.RecipeUncheckedUpdateWithoutRecipe_bagsInput>
}

export type RecipeCreateWithoutTemplateInput = {
  id?: string
  slug: string
  created?: Date | string
  updated?: Date | string
  owner_user_id?: string | null
  definition:PrismaJson.Recipe_definition
  plugins:PrismaJson.Recipe_plugins
  compiledAt: Date | string
  recipe_bags?: Prisma.RecipeBagCreateNestedManyWithoutRecipeInput
  permissions?: Prisma.RecipePermissionCreateNestedManyWithoutRecipeInput
}

export type RecipeUncheckedCreateWithoutTemplateInput = {
  id?: string
  slug: string
  created?: Date | string
  updated?: Date | string
  owner_user_id?: string | null
  definition:PrismaJson.Recipe_definition
  plugins:PrismaJson.Recipe_plugins
  compiledAt: Date | string
  recipe_bags?: Prisma.RecipeBagUncheckedCreateNestedManyWithoutRecipeInput
  permissions?: Prisma.RecipePermissionUncheckedCreateNestedManyWithoutRecipeInput
}

export type RecipeCreateOrConnectWithoutTemplateInput = {
  where: Prisma.RecipeWhereUniqueInput
  create: Prisma.XOR<Prisma.RecipeCreateWithoutTemplateInput, Prisma.RecipeUncheckedCreateWithoutTemplateInput>
}

export type RecipeCreateManyTemplateInputEnvelope = {
  data: Prisma.RecipeCreateManyTemplateInput | Prisma.RecipeCreateManyTemplateInput[]
}

export type RecipeUpsertWithWhereUniqueWithoutTemplateInput = {
  where: Prisma.RecipeWhereUniqueInput
  update: Prisma.XOR<Prisma.RecipeUpdateWithoutTemplateInput, Prisma.RecipeUncheckedUpdateWithoutTemplateInput>
  create: Prisma.XOR<Prisma.RecipeCreateWithoutTemplateInput, Prisma.RecipeUncheckedCreateWithoutTemplateInput>
}

export type RecipeUpdateWithWhereUniqueWithoutTemplateInput = {
  where: Prisma.RecipeWhereUniqueInput
  data: Prisma.XOR<Prisma.RecipeUpdateWithoutTemplateInput, Prisma.RecipeUncheckedUpdateWithoutTemplateInput>
}

export type RecipeUpdateManyWithWhereWithoutTemplateInput = {
  where: Prisma.RecipeScalarWhereInput
  data: Prisma.XOR<Prisma.RecipeUpdateManyMutationInput, Prisma.RecipeUncheckedUpdateManyWithoutTemplateInput>
}

export type RecipeScalarWhereInput = {
  AND?: Prisma.RecipeScalarWhereInput | Prisma.RecipeScalarWhereInput[]
  OR?: Prisma.RecipeScalarWhereInput[]
  NOT?: Prisma.RecipeScalarWhereInput | Prisma.RecipeScalarWhereInput[]
  id?: Prisma.StringFilter<"Recipe"> | string
  slug?: Prisma.StringFilter<"Recipe"> | string
  created?: Prisma.DateTimeFilter<"Recipe"> | Date | string
  updated?: Prisma.DateTimeFilter<"Recipe"> | Date | string
  owner_user_id?: Prisma.StringNullableFilter<"Recipe"> | string | null
  template_id?: Prisma.StringFilter<"Recipe"> | string
  definition?: Prisma.JsonFilter<"Recipe">
  plugins?: Prisma.JsonFilter<"Recipe">
  compiledAt?: Prisma.DateTimeFilter<"Recipe"> | Date | string
}

export type RecipeCreateWithoutPermissionsInput = {
  id?: string
  slug: string
  created?: Date | string
  updated?: Date | string
  owner_user_id?: string | null
  definition:PrismaJson.Recipe_definition
  plugins:PrismaJson.Recipe_plugins
  compiledAt: Date | string
  template: Prisma.TemplateCreateNestedOneWithoutRecipesInput
  recipe_bags?: Prisma.RecipeBagCreateNestedManyWithoutRecipeInput
}

export type RecipeUncheckedCreateWithoutPermissionsInput = {
  id?: string
  slug: string
  created?: Date | string
  updated?: Date | string
  owner_user_id?: string | null
  template_id: string
  definition:PrismaJson.Recipe_definition
  plugins:PrismaJson.Recipe_plugins
  compiledAt: Date | string
  recipe_bags?: Prisma.RecipeBagUncheckedCreateNestedManyWithoutRecipeInput
}

export type RecipeCreateOrConnectWithoutPermissionsInput = {
  where: Prisma.RecipeWhereUniqueInput
  create: Prisma.XOR<Prisma.RecipeCreateWithoutPermissionsInput, Prisma.RecipeUncheckedCreateWithoutPermissionsInput>
}

export type RecipeUpsertWithoutPermissionsInput = {
  update: Prisma.XOR<Prisma.RecipeUpdateWithoutPermissionsInput, Prisma.RecipeUncheckedUpdateWithoutPermissionsInput>
  create: Prisma.XOR<Prisma.RecipeCreateWithoutPermissionsInput, Prisma.RecipeUncheckedCreateWithoutPermissionsInput>
  where?: Prisma.RecipeWhereInput
}

export type RecipeUpdateToOneWithWhereWithoutPermissionsInput = {
  where?: Prisma.RecipeWhereInput
  data: Prisma.XOR<Prisma.RecipeUpdateWithoutPermissionsInput, Prisma.RecipeUncheckedUpdateWithoutPermissionsInput>
}

export type RecipeUpdateWithoutPermissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  definition?:PrismaJson.Recipe_definition
  plugins?:PrismaJson.Recipe_plugins
  compiledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  template?: Prisma.TemplateUpdateOneRequiredWithoutRecipesNestedInput
  recipe_bags?: Prisma.RecipeBagUpdateManyWithoutRecipeNestedInput
}

export type RecipeUncheckedUpdateWithoutPermissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  template_id?: Prisma.StringFieldUpdateOperationsInput | string
  definition?:PrismaJson.Recipe_definition
  plugins?:PrismaJson.Recipe_plugins
  compiledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  recipe_bags?: Prisma.RecipeBagUncheckedUpdateManyWithoutRecipeNestedInput
}

export type RecipeCreateWithoutRecipe_bagsInput = {
  id?: string
  slug: string
  created?: Date | string
  updated?: Date | string
  owner_user_id?: string | null
  definition:PrismaJson.Recipe_definition
  plugins:PrismaJson.Recipe_plugins
  compiledAt: Date | string
  template: Prisma.TemplateCreateNestedOneWithoutRecipesInput
  permissions?: Prisma.RecipePermissionCreateNestedManyWithoutRecipeInput
}

export type RecipeUncheckedCreateWithoutRecipe_bagsInput = {
  id?: string
  slug: string
  created?: Date | string
  updated?: Date | string
  owner_user_id?: string | null
  template_id: string
  definition:PrismaJson.Recipe_definition
  plugins:PrismaJson.Recipe_plugins
  compiledAt: Date | string
  permissions?: Prisma.RecipePermissionUncheckedCreateNestedManyWithoutRecipeInput
}

export type RecipeCreateOrConnectWithoutRecipe_bagsInput = {
  where: Prisma.RecipeWhereUniqueInput
  create: Prisma.XOR<Prisma.RecipeCreateWithoutRecipe_bagsInput, Prisma.RecipeUncheckedCreateWithoutRecipe_bagsInput>
}

export type RecipeUpsertWithoutRecipe_bagsInput = {
  update: Prisma.XOR<Prisma.RecipeUpdateWithoutRecipe_bagsInput, Prisma.RecipeUncheckedUpdateWithoutRecipe_bagsInput>
  create: Prisma.XOR<Prisma.RecipeCreateWithoutRecipe_bagsInput, Prisma.RecipeUncheckedCreateWithoutRecipe_bagsInput>
  where?: Prisma.RecipeWhereInput
}

export type RecipeUpdateToOneWithWhereWithoutRecipe_bagsInput = {
  where?: Prisma.RecipeWhereInput
  data: Prisma.XOR<Prisma.RecipeUpdateWithoutRecipe_bagsInput, Prisma.RecipeUncheckedUpdateWithoutRecipe_bagsInput>
}

export type RecipeUpdateWithoutRecipe_bagsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  definition?:PrismaJson.Recipe_definition
  plugins?:PrismaJson.Recipe_plugins
  compiledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  template?: Prisma.TemplateUpdateOneRequiredWithoutRecipesNestedInput
  permissions?: Prisma.RecipePermissionUpdateManyWithoutRecipeNestedInput
}

export type RecipeUncheckedUpdateWithoutRecipe_bagsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  template_id?: Prisma.StringFieldUpdateOperationsInput | string
  definition?:PrismaJson.Recipe_definition
  plugins?:PrismaJson.Recipe_plugins
  compiledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  permissions?: Prisma.RecipePermissionUncheckedUpdateManyWithoutRecipeNestedInput
}

export type RecipeCreateManyTemplateInput = {
  id?: string
  slug: string
  created?: Date | string
  updated?: Date | string
  owner_user_id?: string | null
  definition:PrismaJson.Recipe_definition
  plugins:PrismaJson.Recipe_plugins
  compiledAt: Date | string
}

export type RecipeUpdateWithoutTemplateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  definition?:PrismaJson.Recipe_definition
  plugins?:PrismaJson.Recipe_plugins
  compiledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  recipe_bags?: Prisma.RecipeBagUpdateManyWithoutRecipeNestedInput
  permissions?: Prisma.RecipePermissionUpdateManyWithoutRecipeNestedInput
}

export type RecipeUncheckedUpdateWithoutTemplateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  definition?:PrismaJson.Recipe_definition
  plugins?:PrismaJson.Recipe_plugins
  compiledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  recipe_bags?: Prisma.RecipeBagUncheckedUpdateManyWithoutRecipeNestedInput
  permissions?: Prisma.RecipePermissionUncheckedUpdateManyWithoutRecipeNestedInput
}

export type RecipeUncheckedUpdateManyWithoutTemplateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner_user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  definition?:PrismaJson.Recipe_definition
  plugins?:PrismaJson.Recipe_plugins
  compiledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type RecipeCountOutputType
 */

export type RecipeCountOutputType = {
  recipe_bags: number
  permissions: number
}

export type RecipeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe_bags?: boolean | RecipeCountOutputTypeCountRecipe_bagsArgs
  permissions?: boolean | RecipeCountOutputTypeCountPermissionsArgs
}

/**
 * RecipeCountOutputType without action
 */
export type RecipeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeCountOutputType
   */
  select?: Prisma.RecipeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RecipeCountOutputType without action
 */
export type RecipeCountOutputTypeCountRecipe_bagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipeBagWhereInput
}

/**
 * RecipeCountOutputType without action
 */
export type RecipeCountOutputTypeCountPermissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipePermissionWhereInput
}


export type RecipeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  created?: boolean
  updated?: boolean
  owner_user_id?: boolean
  template_id?: boolean
  definition?: boolean
  plugins?: boolean
  compiledAt?: boolean
  template?: boolean | Prisma.TemplateDefaultArgs<ExtArgs>
  recipe_bags?: boolean | Prisma.Recipe$recipe_bagsArgs<ExtArgs>
  permissions?: boolean | Prisma.Recipe$permissionsArgs<ExtArgs>
  _count?: boolean | Prisma.RecipeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipe"]>

export type RecipeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  created?: boolean
  updated?: boolean
  owner_user_id?: boolean
  template_id?: boolean
  definition?: boolean
  plugins?: boolean
  compiledAt?: boolean
  template?: boolean | Prisma.TemplateDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipe"]>

export type RecipeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  created?: boolean
  updated?: boolean
  owner_user_id?: boolean
  template_id?: boolean
  definition?: boolean
  plugins?: boolean
  compiledAt?: boolean
  template?: boolean | Prisma.TemplateDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipe"]>

export type RecipeSelectScalar = {
  id?: boolean
  slug?: boolean
  created?: boolean
  updated?: boolean
  owner_user_id?: boolean
  template_id?: boolean
  definition?: boolean
  plugins?: boolean
  compiledAt?: boolean
}

export type RecipeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "slug" | "created" | "updated" | "owner_user_id" | "template_id" | "definition" | "plugins" | "compiledAt", ExtArgs["result"]["recipe"]>
export type RecipeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  template?: boolean | Prisma.TemplateDefaultArgs<ExtArgs>
  recipe_bags?: boolean | Prisma.Recipe$recipe_bagsArgs<ExtArgs>
  permissions?: boolean | Prisma.Recipe$permissionsArgs<ExtArgs>
  _count?: boolean | Prisma.RecipeCountOutputTypeDefaultArgs<ExtArgs>
}
export type RecipeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  template?: boolean | Prisma.TemplateDefaultArgs<ExtArgs>
}
export type RecipeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  template?: boolean | Prisma.TemplateDefaultArgs<ExtArgs>
}

export type $RecipePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Recipe"
  objects: {
    template: Prisma.$TemplatePayload<ExtArgs>
    recipe_bags: Prisma.$RecipeBagPayload<ExtArgs>[]
    permissions: Prisma.$RecipePermissionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    slug: string
    created: Date
    updated: Date
    /**
     * user_id of the user who created this wiki; deletable only by the
     * owner or the site admin account ("admin"). role_id references the
     * auth module, no FK declared here.
     */
    owner_user_id: string | null
    template_id: string
    /**
     * [Recipe_definition]
     */
    definition:PrismaJson.Recipe_definition
    /**
     * [Recipe_plugins]
     */
    plugins:PrismaJson.Recipe_plugins
    compiledAt: Date
  }, ExtArgs["result"]["recipe"]>
  composites: {}
}

export type RecipeGetPayload<S extends boolean | null | undefined | RecipeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RecipePayload, S>

export type RecipeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RecipeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RecipeCountAggregateInputType | true
  }

export interface RecipeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Recipe'], meta: { name: 'Recipe' } }
  /**
   * Find zero or one Recipe that matches the filter.
   * @param {RecipeFindUniqueArgs} args - Arguments to find a Recipe
   * @example
   * // Get one Recipe
   * const recipe = await prisma.recipe.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RecipeFindUniqueArgs>(args: Prisma.SelectSubset<T, RecipeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RecipeClient<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Recipe that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RecipeFindUniqueOrThrowArgs} args - Arguments to find a Recipe
   * @example
   * // Get one Recipe
   * const recipe = await prisma.recipe.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RecipeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RecipeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipeClient<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Recipe that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeFindFirstArgs} args - Arguments to find a Recipe
   * @example
   * // Get one Recipe
   * const recipe = await prisma.recipe.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RecipeFindFirstArgs>(args?: Prisma.SelectSubset<T, RecipeFindFirstArgs<ExtArgs>>): Prisma.Prisma__RecipeClient<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Recipe that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeFindFirstOrThrowArgs} args - Arguments to find a Recipe
   * @example
   * // Get one Recipe
   * const recipe = await prisma.recipe.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RecipeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RecipeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipeClient<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Recipes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Recipes
   * const recipes = await prisma.recipe.findMany()
   * 
   * // Get first 10 Recipes
   * const recipes = await prisma.recipe.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const recipeWithIdOnly = await prisma.recipe.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RecipeFindManyArgs>(args?: Prisma.SelectSubset<T, RecipeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Recipe.
   * @param {RecipeCreateArgs} args - Arguments to create a Recipe.
   * @example
   * // Create one Recipe
   * const Recipe = await prisma.recipe.create({
   *   data: {
   *     // ... data to create a Recipe
   *   }
   * })
   * 
   */
  create<T extends RecipeCreateArgs>(args: Prisma.SelectSubset<T, RecipeCreateArgs<ExtArgs>>): Prisma.Prisma__RecipeClient<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Recipes.
   * @param {RecipeCreateManyArgs} args - Arguments to create many Recipes.
   * @example
   * // Create many Recipes
   * const recipe = await prisma.recipe.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RecipeCreateManyArgs>(args?: Prisma.SelectSubset<T, RecipeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Recipes and returns the data saved in the database.
   * @param {RecipeCreateManyAndReturnArgs} args - Arguments to create many Recipes.
   * @example
   * // Create many Recipes
   * const recipe = await prisma.recipe.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Recipes and only return the `id`
   * const recipeWithIdOnly = await prisma.recipe.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RecipeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RecipeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Recipe.
   * @param {RecipeDeleteArgs} args - Arguments to delete one Recipe.
   * @example
   * // Delete one Recipe
   * const Recipe = await prisma.recipe.delete({
   *   where: {
   *     // ... filter to delete one Recipe
   *   }
   * })
   * 
   */
  delete<T extends RecipeDeleteArgs>(args: Prisma.SelectSubset<T, RecipeDeleteArgs<ExtArgs>>): Prisma.Prisma__RecipeClient<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Recipe.
   * @param {RecipeUpdateArgs} args - Arguments to update one Recipe.
   * @example
   * // Update one Recipe
   * const recipe = await prisma.recipe.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RecipeUpdateArgs>(args: Prisma.SelectSubset<T, RecipeUpdateArgs<ExtArgs>>): Prisma.Prisma__RecipeClient<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Recipes.
   * @param {RecipeDeleteManyArgs} args - Arguments to filter Recipes to delete.
   * @example
   * // Delete a few Recipes
   * const { count } = await prisma.recipe.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RecipeDeleteManyArgs>(args?: Prisma.SelectSubset<T, RecipeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Recipes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Recipes
   * const recipe = await prisma.recipe.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RecipeUpdateManyArgs>(args: Prisma.SelectSubset<T, RecipeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Recipes and returns the data updated in the database.
   * @param {RecipeUpdateManyAndReturnArgs} args - Arguments to update many Recipes.
   * @example
   * // Update many Recipes
   * const recipe = await prisma.recipe.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Recipes and only return the `id`
   * const recipeWithIdOnly = await prisma.recipe.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RecipeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RecipeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Recipe.
   * @param {RecipeUpsertArgs} args - Arguments to update or create a Recipe.
   * @example
   * // Update or create a Recipe
   * const recipe = await prisma.recipe.upsert({
   *   create: {
   *     // ... data to create a Recipe
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Recipe we want to update
   *   }
   * })
   */
  upsert<T extends RecipeUpsertArgs>(args: Prisma.SelectSubset<T, RecipeUpsertArgs<ExtArgs>>): Prisma.Prisma__RecipeClient<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Recipes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeCountArgs} args - Arguments to filter Recipes to count.
   * @example
   * // Count the number of Recipes
   * const count = await prisma.recipe.count({
   *   where: {
   *     // ... the filter for the Recipes we want to count
   *   }
   * })
  **/
  count<T extends RecipeCountArgs>(
    args?: Prisma.Subset<T, RecipeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RecipeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Recipe.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RecipeAggregateArgs>(args: Prisma.Subset<T, RecipeAggregateArgs>): Prisma.PrismaPromise<GetRecipeAggregateType<T>>

  /**
   * Group by Recipe.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RecipeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RecipeGroupByArgs['orderBy'] }
      : { orderBy?: RecipeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RecipeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRecipeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Recipe model
 */
readonly fields: RecipeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Recipe.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RecipeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  template<T extends Prisma.TemplateDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TemplateDefaultArgs<ExtArgs>>): Prisma.Prisma__TemplateClient<runtime.Types.Result.GetResult<Prisma.$TemplatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  recipe_bags<T extends Prisma.Recipe$recipe_bagsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Recipe$recipe_bagsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipeBagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  permissions<T extends Prisma.Recipe$permissionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Recipe$permissionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipePermissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Recipe model
 */
export interface RecipeFieldRefs {
  readonly id: Prisma.FieldRef<"Recipe", 'String'>
  readonly slug: Prisma.FieldRef<"Recipe", 'String'>
  readonly created: Prisma.FieldRef<"Recipe", 'DateTime'>
  readonly updated: Prisma.FieldRef<"Recipe", 'DateTime'>
  readonly owner_user_id: Prisma.FieldRef<"Recipe", 'String'>
  readonly template_id: Prisma.FieldRef<"Recipe", 'String'>
  readonly definition: Prisma.FieldRef<"Recipe", 'Json'>
  readonly plugins: Prisma.FieldRef<"Recipe", 'Json'>
  readonly compiledAt: Prisma.FieldRef<"Recipe", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Recipe findUnique
 */
export type RecipeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe
   */
  select?: Prisma.RecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe
   */
  omit?: Prisma.RecipeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeInclude<ExtArgs> | null
  /**
   * Filter, which Recipe to fetch.
   */
  where: Prisma.RecipeWhereUniqueInput
}

/**
 * Recipe findUniqueOrThrow
 */
export type RecipeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe
   */
  select?: Prisma.RecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe
   */
  omit?: Prisma.RecipeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeInclude<ExtArgs> | null
  /**
   * Filter, which Recipe to fetch.
   */
  where: Prisma.RecipeWhereUniqueInput
}

/**
 * Recipe findFirst
 */
export type RecipeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe
   */
  select?: Prisma.RecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe
   */
  omit?: Prisma.RecipeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeInclude<ExtArgs> | null
  /**
   * Filter, which Recipe to fetch.
   */
  where?: Prisma.RecipeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Recipes to fetch.
   */
  orderBy?: Prisma.RecipeOrderByWithRelationInput | Prisma.RecipeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Recipes.
   */
  cursor?: Prisma.RecipeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Recipes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Recipes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Recipes.
   */
  distinct?: Prisma.RecipeScalarFieldEnum | Prisma.RecipeScalarFieldEnum[]
}

/**
 * Recipe findFirstOrThrow
 */
export type RecipeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe
   */
  select?: Prisma.RecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe
   */
  omit?: Prisma.RecipeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeInclude<ExtArgs> | null
  /**
   * Filter, which Recipe to fetch.
   */
  where?: Prisma.RecipeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Recipes to fetch.
   */
  orderBy?: Prisma.RecipeOrderByWithRelationInput | Prisma.RecipeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Recipes.
   */
  cursor?: Prisma.RecipeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Recipes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Recipes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Recipes.
   */
  distinct?: Prisma.RecipeScalarFieldEnum | Prisma.RecipeScalarFieldEnum[]
}

/**
 * Recipe findMany
 */
export type RecipeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe
   */
  select?: Prisma.RecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe
   */
  omit?: Prisma.RecipeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeInclude<ExtArgs> | null
  /**
   * Filter, which Recipes to fetch.
   */
  where?: Prisma.RecipeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Recipes to fetch.
   */
  orderBy?: Prisma.RecipeOrderByWithRelationInput | Prisma.RecipeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Recipes.
   */
  cursor?: Prisma.RecipeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Recipes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Recipes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Recipes.
   */
  distinct?: Prisma.RecipeScalarFieldEnum | Prisma.RecipeScalarFieldEnum[]
}

/**
 * Recipe create
 */
export type RecipeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe
   */
  select?: Prisma.RecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe
   */
  omit?: Prisma.RecipeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeInclude<ExtArgs> | null
  /**
   * The data needed to create a Recipe.
   */
  data: Prisma.XOR<Prisma.RecipeCreateInput, Prisma.RecipeUncheckedCreateInput>
}

/**
 * Recipe createMany
 */
export type RecipeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Recipes.
   */
  data: Prisma.RecipeCreateManyInput | Prisma.RecipeCreateManyInput[]
}

/**
 * Recipe createManyAndReturn
 */
export type RecipeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe
   */
  select?: Prisma.RecipeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe
   */
  omit?: Prisma.RecipeOmit<ExtArgs> | null
  /**
   * The data used to create many Recipes.
   */
  data: Prisma.RecipeCreateManyInput | Prisma.RecipeCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Recipe update
 */
export type RecipeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe
   */
  select?: Prisma.RecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe
   */
  omit?: Prisma.RecipeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeInclude<ExtArgs> | null
  /**
   * The data needed to update a Recipe.
   */
  data: Prisma.XOR<Prisma.RecipeUpdateInput, Prisma.RecipeUncheckedUpdateInput>
  /**
   * Choose, which Recipe to update.
   */
  where: Prisma.RecipeWhereUniqueInput
}

/**
 * Recipe updateMany
 */
export type RecipeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Recipes.
   */
  data: Prisma.XOR<Prisma.RecipeUpdateManyMutationInput, Prisma.RecipeUncheckedUpdateManyInput>
  /**
   * Filter which Recipes to update
   */
  where?: Prisma.RecipeWhereInput
  /**
   * Limit how many Recipes to update.
   */
  limit?: number
}

/**
 * Recipe updateManyAndReturn
 */
export type RecipeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe
   */
  select?: Prisma.RecipeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe
   */
  omit?: Prisma.RecipeOmit<ExtArgs> | null
  /**
   * The data used to update Recipes.
   */
  data: Prisma.XOR<Prisma.RecipeUpdateManyMutationInput, Prisma.RecipeUncheckedUpdateManyInput>
  /**
   * Filter which Recipes to update
   */
  where?: Prisma.RecipeWhereInput
  /**
   * Limit how many Recipes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Recipe upsert
 */
export type RecipeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe
   */
  select?: Prisma.RecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe
   */
  omit?: Prisma.RecipeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeInclude<ExtArgs> | null
  /**
   * The filter to search for the Recipe to update in case it exists.
   */
  where: Prisma.RecipeWhereUniqueInput
  /**
   * In case the Recipe found by the `where` argument doesn't exist, create a new Recipe with this data.
   */
  create: Prisma.XOR<Prisma.RecipeCreateInput, Prisma.RecipeUncheckedCreateInput>
  /**
   * In case the Recipe was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RecipeUpdateInput, Prisma.RecipeUncheckedUpdateInput>
}

/**
 * Recipe delete
 */
export type RecipeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe
   */
  select?: Prisma.RecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe
   */
  omit?: Prisma.RecipeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeInclude<ExtArgs> | null
  /**
   * Filter which Recipe to delete.
   */
  where: Prisma.RecipeWhereUniqueInput
}

/**
 * Recipe deleteMany
 */
export type RecipeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Recipes to delete
   */
  where?: Prisma.RecipeWhereInput
  /**
   * Limit how many Recipes to delete.
   */
  limit?: number
}

/**
 * Recipe.recipe_bags
 */
export type Recipe$recipe_bagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipeBag
   */
  select?: Prisma.RecipeBagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipeBag
   */
  omit?: Prisma.RecipeBagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeBagInclude<ExtArgs> | null
  where?: Prisma.RecipeBagWhereInput
  orderBy?: Prisma.RecipeBagOrderByWithRelationInput | Prisma.RecipeBagOrderByWithRelationInput[]
  cursor?: Prisma.RecipeBagWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RecipeBagScalarFieldEnum | Prisma.RecipeBagScalarFieldEnum[]
}

/**
 * Recipe.permissions
 */
export type Recipe$permissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePermission
   */
  select?: Prisma.RecipePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePermission
   */
  omit?: Prisma.RecipePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePermissionInclude<ExtArgs> | null
  where?: Prisma.RecipePermissionWhereInput
  orderBy?: Prisma.RecipePermissionOrderByWithRelationInput | Prisma.RecipePermissionOrderByWithRelationInput[]
  cursor?: Prisma.RecipePermissionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RecipePermissionScalarFieldEnum | Prisma.RecipePermissionScalarFieldEnum[]
}

/**
 * Recipe without action
 */
export type RecipeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Recipe
   */
  select?: Prisma.RecipeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Recipe
   */
  omit?: Prisma.RecipeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipeInclude<ExtArgs> | null
}
