
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserFile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model UserFile
 * 
 */
export type UserFileModel = runtime.Types.Result.DefaultSelection<Prisma.$UserFilePayload>

export type AggregateUserFile = {
  _count: UserFileCountAggregateOutputType | null
  _avg: UserFileAvgAggregateOutputType | null
  _sum: UserFileSumAggregateOutputType | null
  _min: UserFileMinAggregateOutputType | null
  _max: UserFileMaxAggregateOutputType | null
}

export type UserFileAvgAggregateOutputType = {
  sizeBytes: number | null
}

export type UserFileSumAggregateOutputType = {
  sizeBytes: number | null
}

export type UserFileMinAggregateOutputType = {
  id: string | null
  user_id: string | null
  recipe_id: string | null
  filename: string | null
  type: string | null
  extension: string | null
  sha256: string | null
  sizeBytes: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type UserFileMaxAggregateOutputType = {
  id: string | null
  user_id: string | null
  recipe_id: string | null
  filename: string | null
  type: string | null
  extension: string | null
  sha256: string | null
  sizeBytes: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type UserFileCountAggregateOutputType = {
  id: number
  user_id: number
  recipe_id: number
  filename: number
  type: number
  extension: number
  sha256: number
  sizeBytes: number
  created_at: number
  updated_at: number
  _all: number
}


export type UserFileAvgAggregateInputType = {
  sizeBytes?: true
}

export type UserFileSumAggregateInputType = {
  sizeBytes?: true
}

export type UserFileMinAggregateInputType = {
  id?: true
  user_id?: true
  recipe_id?: true
  filename?: true
  type?: true
  extension?: true
  sha256?: true
  sizeBytes?: true
  created_at?: true
  updated_at?: true
}

export type UserFileMaxAggregateInputType = {
  id?: true
  user_id?: true
  recipe_id?: true
  filename?: true
  type?: true
  extension?: true
  sha256?: true
  sizeBytes?: true
  created_at?: true
  updated_at?: true
}

export type UserFileCountAggregateInputType = {
  id?: true
  user_id?: true
  recipe_id?: true
  filename?: true
  type?: true
  extension?: true
  sha256?: true
  sizeBytes?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type UserFileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserFile to aggregate.
   */
  where?: Prisma.UserFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserFiles to fetch.
   */
  orderBy?: Prisma.UserFileOrderByWithRelationInput | Prisma.UserFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserFiles
  **/
  _count?: true | UserFileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserFileAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserFileSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserFileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserFileMaxAggregateInputType
}

export type GetUserFileAggregateType<T extends UserFileAggregateArgs> = {
      [P in keyof T & keyof AggregateUserFile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserFile[P]>
    : Prisma.GetScalarType<T[P], AggregateUserFile[P]>
}




export type UserFileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserFileWhereInput
  orderBy?: Prisma.UserFileOrderByWithAggregationInput | Prisma.UserFileOrderByWithAggregationInput[]
  by: Prisma.UserFileScalarFieldEnum[] | Prisma.UserFileScalarFieldEnum
  having?: Prisma.UserFileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserFileCountAggregateInputType | true
  _avg?: UserFileAvgAggregateInputType
  _sum?: UserFileSumAggregateInputType
  _min?: UserFileMinAggregateInputType
  _max?: UserFileMaxAggregateInputType
}

export type UserFileGroupByOutputType = {
  id: string
  user_id: string
  recipe_id: string | null
  filename: string
  type: string
  extension: string
  sha256: string
  sizeBytes: number
  created_at: Date
  updated_at: Date
  _count: UserFileCountAggregateOutputType | null
  _avg: UserFileAvgAggregateOutputType | null
  _sum: UserFileSumAggregateOutputType | null
  _min: UserFileMinAggregateOutputType | null
  _max: UserFileMaxAggregateOutputType | null
}

export type GetUserFileGroupByPayload<T extends UserFileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserFileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserFileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserFileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserFileGroupByOutputType[P]>
      }
    >
  >



export type UserFileWhereInput = {
  AND?: Prisma.UserFileWhereInput | Prisma.UserFileWhereInput[]
  OR?: Prisma.UserFileWhereInput[]
  NOT?: Prisma.UserFileWhereInput | Prisma.UserFileWhereInput[]
  id?: Prisma.StringFilter<"UserFile"> | string
  user_id?: Prisma.StringFilter<"UserFile"> | string
  recipe_id?: Prisma.StringNullableFilter<"UserFile"> | string | null
  filename?: Prisma.StringFilter<"UserFile"> | string
  type?: Prisma.StringFilter<"UserFile"> | string
  extension?: Prisma.StringFilter<"UserFile"> | string
  sha256?: Prisma.StringFilter<"UserFile"> | string
  sizeBytes?: Prisma.IntFilter<"UserFile"> | number
  created_at?: Prisma.DateTimeFilter<"UserFile"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"UserFile"> | Date | string
  shares?: Prisma.UserFileShareListRelationFilter
}

export type UserFileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  recipe_id?: Prisma.SortOrderInput | Prisma.SortOrder
  filename?: Prisma.SortOrder
  type?: Prisma.SortOrder
  extension?: Prisma.SortOrder
  sha256?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  shares?: Prisma.UserFileShareOrderByRelationAggregateInput
}

export type UserFileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UserFileWhereInput | Prisma.UserFileWhereInput[]
  OR?: Prisma.UserFileWhereInput[]
  NOT?: Prisma.UserFileWhereInput | Prisma.UserFileWhereInput[]
  user_id?: Prisma.StringFilter<"UserFile"> | string
  recipe_id?: Prisma.StringNullableFilter<"UserFile"> | string | null
  filename?: Prisma.StringFilter<"UserFile"> | string
  type?: Prisma.StringFilter<"UserFile"> | string
  extension?: Prisma.StringFilter<"UserFile"> | string
  sha256?: Prisma.StringFilter<"UserFile"> | string
  sizeBytes?: Prisma.IntFilter<"UserFile"> | number
  created_at?: Prisma.DateTimeFilter<"UserFile"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"UserFile"> | Date | string
  shares?: Prisma.UserFileShareListRelationFilter
}, "id">

export type UserFileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  recipe_id?: Prisma.SortOrderInput | Prisma.SortOrder
  filename?: Prisma.SortOrder
  type?: Prisma.SortOrder
  extension?: Prisma.SortOrder
  sha256?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.UserFileCountOrderByAggregateInput
  _avg?: Prisma.UserFileAvgOrderByAggregateInput
  _max?: Prisma.UserFileMaxOrderByAggregateInput
  _min?: Prisma.UserFileMinOrderByAggregateInput
  _sum?: Prisma.UserFileSumOrderByAggregateInput
}

export type UserFileScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserFileScalarWhereWithAggregatesInput | Prisma.UserFileScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserFileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserFileScalarWhereWithAggregatesInput | Prisma.UserFileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserFile"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"UserFile"> | string
  recipe_id?: Prisma.StringNullableWithAggregatesFilter<"UserFile"> | string | null
  filename?: Prisma.StringWithAggregatesFilter<"UserFile"> | string
  type?: Prisma.StringWithAggregatesFilter<"UserFile"> | string
  extension?: Prisma.StringWithAggregatesFilter<"UserFile"> | string
  sha256?: Prisma.StringWithAggregatesFilter<"UserFile"> | string
  sizeBytes?: Prisma.IntWithAggregatesFilter<"UserFile"> | number
  created_at?: Prisma.DateTimeWithAggregatesFilter<"UserFile"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"UserFile"> | Date | string
}

export type UserFileCreateInput = {
  id?: string
  user_id: string
  recipe_id?: string | null
  filename: string
  type: string
  extension: string
  sha256: string
  sizeBytes: number
  created_at?: Date | string
  updated_at?: Date | string
  shares?: Prisma.UserFileShareCreateNestedManyWithoutFileInput
}

export type UserFileUncheckedCreateInput = {
  id?: string
  user_id: string
  recipe_id?: string | null
  filename: string
  type: string
  extension: string
  sha256: string
  sizeBytes: number
  created_at?: Date | string
  updated_at?: Date | string
  shares?: Prisma.UserFileShareUncheckedCreateNestedManyWithoutFileInput
}

export type UserFileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  sha256?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shares?: Prisma.UserFileShareUpdateManyWithoutFileNestedInput
}

export type UserFileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  sha256?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shares?: Prisma.UserFileShareUncheckedUpdateManyWithoutFileNestedInput
}

export type UserFileCreateManyInput = {
  id?: string
  user_id: string
  recipe_id?: string | null
  filename: string
  type: string
  extension: string
  sha256: string
  sizeBytes: number
  created_at?: Date | string
  updated_at?: Date | string
}

export type UserFileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  sha256?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserFileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  sha256?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserFileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  recipe_id?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  type?: Prisma.SortOrder
  extension?: Prisma.SortOrder
  sha256?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type UserFileAvgOrderByAggregateInput = {
  sizeBytes?: Prisma.SortOrder
}

export type UserFileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  recipe_id?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  type?: Prisma.SortOrder
  extension?: Prisma.SortOrder
  sha256?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type UserFileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  recipe_id?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  type?: Prisma.SortOrder
  extension?: Prisma.SortOrder
  sha256?: Prisma.SortOrder
  sizeBytes?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type UserFileSumOrderByAggregateInput = {
  sizeBytes?: Prisma.SortOrder
}

export type UserFileScalarRelationFilter = {
  is?: Prisma.UserFileWhereInput
  isNot?: Prisma.UserFileWhereInput
}

export type UserFileCreateNestedOneWithoutSharesInput = {
  create?: Prisma.XOR<Prisma.UserFileCreateWithoutSharesInput, Prisma.UserFileUncheckedCreateWithoutSharesInput>
  connectOrCreate?: Prisma.UserFileCreateOrConnectWithoutSharesInput
  connect?: Prisma.UserFileWhereUniqueInput
}

export type UserFileUpdateOneRequiredWithoutSharesNestedInput = {
  create?: Prisma.XOR<Prisma.UserFileCreateWithoutSharesInput, Prisma.UserFileUncheckedCreateWithoutSharesInput>
  connectOrCreate?: Prisma.UserFileCreateOrConnectWithoutSharesInput
  upsert?: Prisma.UserFileUpsertWithoutSharesInput
  connect?: Prisma.UserFileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserFileUpdateToOneWithWhereWithoutSharesInput, Prisma.UserFileUpdateWithoutSharesInput>, Prisma.UserFileUncheckedUpdateWithoutSharesInput>
}

export type UserFileCreateWithoutSharesInput = {
  id?: string
  user_id: string
  recipe_id?: string | null
  filename: string
  type: string
  extension: string
  sha256: string
  sizeBytes: number
  created_at?: Date | string
  updated_at?: Date | string
}

export type UserFileUncheckedCreateWithoutSharesInput = {
  id?: string
  user_id: string
  recipe_id?: string | null
  filename: string
  type: string
  extension: string
  sha256: string
  sizeBytes: number
  created_at?: Date | string
  updated_at?: Date | string
}

export type UserFileCreateOrConnectWithoutSharesInput = {
  where: Prisma.UserFileWhereUniqueInput
  create: Prisma.XOR<Prisma.UserFileCreateWithoutSharesInput, Prisma.UserFileUncheckedCreateWithoutSharesInput>
}

export type UserFileUpsertWithoutSharesInput = {
  update: Prisma.XOR<Prisma.UserFileUpdateWithoutSharesInput, Prisma.UserFileUncheckedUpdateWithoutSharesInput>
  create: Prisma.XOR<Prisma.UserFileCreateWithoutSharesInput, Prisma.UserFileUncheckedCreateWithoutSharesInput>
  where?: Prisma.UserFileWhereInput
}

export type UserFileUpdateToOneWithWhereWithoutSharesInput = {
  where?: Prisma.UserFileWhereInput
  data: Prisma.XOR<Prisma.UserFileUpdateWithoutSharesInput, Prisma.UserFileUncheckedUpdateWithoutSharesInput>
}

export type UserFileUpdateWithoutSharesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  sha256?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserFileUncheckedUpdateWithoutSharesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  recipe_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  sha256?: Prisma.StringFieldUpdateOperationsInput | string
  sizeBytes?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type UserFileCountOutputType
 */

export type UserFileCountOutputType = {
  shares: number
}

export type UserFileCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  shares?: boolean | UserFileCountOutputTypeCountSharesArgs
}

/**
 * UserFileCountOutputType without action
 */
export type UserFileCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileCountOutputType
   */
  select?: Prisma.UserFileCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserFileCountOutputType without action
 */
export type UserFileCountOutputTypeCountSharesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserFileShareWhereInput
}


export type UserFileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  recipe_id?: boolean
  filename?: boolean
  type?: boolean
  extension?: boolean
  sha256?: boolean
  sizeBytes?: boolean
  created_at?: boolean
  updated_at?: boolean
  shares?: boolean | Prisma.UserFile$sharesArgs<ExtArgs>
  _count?: boolean | Prisma.UserFileCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userFile"]>

export type UserFileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  recipe_id?: boolean
  filename?: boolean
  type?: boolean
  extension?: boolean
  sha256?: boolean
  sizeBytes?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["userFile"]>

export type UserFileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  recipe_id?: boolean
  filename?: boolean
  type?: boolean
  extension?: boolean
  sha256?: boolean
  sizeBytes?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["userFile"]>

export type UserFileSelectScalar = {
  id?: boolean
  user_id?: boolean
  recipe_id?: boolean
  filename?: boolean
  type?: boolean
  extension?: boolean
  sha256?: boolean
  sizeBytes?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type UserFileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "recipe_id" | "filename" | "type" | "extension" | "sha256" | "sizeBytes" | "created_at" | "updated_at", ExtArgs["result"]["userFile"]>
export type UserFileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  shares?: boolean | Prisma.UserFile$sharesArgs<ExtArgs>
  _count?: boolean | Prisma.UserFileCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserFileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UserFileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UserFilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserFile"
  objects: {
    shares: Prisma.$UserFileSharePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    /**
     * user_id of the owner. No FK (auth module).
     */
    user_id: string
    /**
     * recipe_slug (via Recipe id) this file was uploaded to; files uploaded
     * from inside a wiki are visible to that wiki's readers. No FK declared
     * here, mirroring user_id. NULL = personal file (account's "Meine Dateien").
     */
    recipe_id: string | null
    /**
     * Original file name as shown to the owner.
     */
    filename: string
    /**
     * MIME type of the file.
     */
    type: string
    /**
     * File extension derived from the MIME type ("data.<extension>" on disk).
     */
    extension: string
    /**
     * sha256 of the file content; also the directory name in store/files/.
     */
    sha256: string
    /**
     * Size of the file in bytes.
     */
    sizeBytes: number
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["userFile"]>
  composites: {}
}

export type UserFileGetPayload<S extends boolean | null | undefined | UserFileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserFilePayload, S>

export type UserFileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserFileCountAggregateInputType | true
  }

export interface UserFileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserFile'], meta: { name: 'UserFile' } }
  /**
   * Find zero or one UserFile that matches the filter.
   * @param {UserFileFindUniqueArgs} args - Arguments to find a UserFile
   * @example
   * // Get one UserFile
   * const userFile = await prisma.userFile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFileFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserFileClient<runtime.Types.Result.GetResult<Prisma.$UserFilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserFile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFileFindUniqueOrThrowArgs} args - Arguments to find a UserFile
   * @example
   * // Get one UserFile
   * const userFile = await prisma.userFile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserFileClient<runtime.Types.Result.GetResult<Prisma.$UserFilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserFile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileFindFirstArgs} args - Arguments to find a UserFile
   * @example
   * // Get one UserFile
   * const userFile = await prisma.userFile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFileFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFileFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserFileClient<runtime.Types.Result.GetResult<Prisma.$UserFilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserFile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileFindFirstOrThrowArgs} args - Arguments to find a UserFile
   * @example
   * // Get one UserFile
   * const userFile = await prisma.userFile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserFileClient<runtime.Types.Result.GetResult<Prisma.$UserFilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserFiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserFiles
   * const userFiles = await prisma.userFile.findMany()
   * 
   * // Get first 10 UserFiles
   * const userFiles = await prisma.userFile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userFileWithIdOnly = await prisma.userFile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFileFindManyArgs>(args?: Prisma.SelectSubset<T, UserFileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserFile.
   * @param {UserFileCreateArgs} args - Arguments to create a UserFile.
   * @example
   * // Create one UserFile
   * const UserFile = await prisma.userFile.create({
   *   data: {
   *     // ... data to create a UserFile
   *   }
   * })
   * 
   */
  create<T extends UserFileCreateArgs>(args: Prisma.SelectSubset<T, UserFileCreateArgs<ExtArgs>>): Prisma.Prisma__UserFileClient<runtime.Types.Result.GetResult<Prisma.$UserFilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserFiles.
   * @param {UserFileCreateManyArgs} args - Arguments to create many UserFiles.
   * @example
   * // Create many UserFiles
   * const userFile = await prisma.userFile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserFileCreateManyArgs>(args?: Prisma.SelectSubset<T, UserFileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserFiles and returns the data saved in the database.
   * @param {UserFileCreateManyAndReturnArgs} args - Arguments to create many UserFiles.
   * @example
   * // Create many UserFiles
   * const userFile = await prisma.userFile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserFiles and only return the `id`
   * const userFileWithIdOnly = await prisma.userFile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserFileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserFileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserFilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserFile.
   * @param {UserFileDeleteArgs} args - Arguments to delete one UserFile.
   * @example
   * // Delete one UserFile
   * const UserFile = await prisma.userFile.delete({
   *   where: {
   *     // ... filter to delete one UserFile
   *   }
   * })
   * 
   */
  delete<T extends UserFileDeleteArgs>(args: Prisma.SelectSubset<T, UserFileDeleteArgs<ExtArgs>>): Prisma.Prisma__UserFileClient<runtime.Types.Result.GetResult<Prisma.$UserFilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserFile.
   * @param {UserFileUpdateArgs} args - Arguments to update one UserFile.
   * @example
   * // Update one UserFile
   * const userFile = await prisma.userFile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserFileUpdateArgs>(args: Prisma.SelectSubset<T, UserFileUpdateArgs<ExtArgs>>): Prisma.Prisma__UserFileClient<runtime.Types.Result.GetResult<Prisma.$UserFilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserFiles.
   * @param {UserFileDeleteManyArgs} args - Arguments to filter UserFiles to delete.
   * @example
   * // Delete a few UserFiles
   * const { count } = await prisma.userFile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserFileDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserFileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserFiles
   * const userFile = await prisma.userFile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserFileUpdateManyArgs>(args: Prisma.SelectSubset<T, UserFileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserFiles and returns the data updated in the database.
   * @param {UserFileUpdateManyAndReturnArgs} args - Arguments to update many UserFiles.
   * @example
   * // Update many UserFiles
   * const userFile = await prisma.userFile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserFiles and only return the `id`
   * const userFileWithIdOnly = await prisma.userFile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserFileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserFileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserFilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserFile.
   * @param {UserFileUpsertArgs} args - Arguments to update or create a UserFile.
   * @example
   * // Update or create a UserFile
   * const userFile = await prisma.userFile.upsert({
   *   create: {
   *     // ... data to create a UserFile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserFile we want to update
   *   }
   * })
   */
  upsert<T extends UserFileUpsertArgs>(args: Prisma.SelectSubset<T, UserFileUpsertArgs<ExtArgs>>): Prisma.Prisma__UserFileClient<runtime.Types.Result.GetResult<Prisma.$UserFilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileCountArgs} args - Arguments to filter UserFiles to count.
   * @example
   * // Count the number of UserFiles
   * const count = await prisma.userFile.count({
   *   where: {
   *     // ... the filter for the UserFiles we want to count
   *   }
   * })
  **/
  count<T extends UserFileCountArgs>(
    args?: Prisma.Subset<T, UserFileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserFileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserFileAggregateArgs>(args: Prisma.Subset<T, UserFileAggregateArgs>): Prisma.PrismaPromise<GetUserFileAggregateType<T>>

  /**
   * Group by UserFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserFileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserFileGroupByArgs['orderBy'] }
      : { orderBy?: UserFileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserFileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserFileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserFile model
 */
readonly fields: UserFileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserFile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserFileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  shares<T extends Prisma.UserFile$sharesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserFile$sharesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserFileSharePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserFile model
 */
export interface UserFileFieldRefs {
  readonly id: Prisma.FieldRef<"UserFile", 'String'>
  readonly user_id: Prisma.FieldRef<"UserFile", 'String'>
  readonly recipe_id: Prisma.FieldRef<"UserFile", 'String'>
  readonly filename: Prisma.FieldRef<"UserFile", 'String'>
  readonly type: Prisma.FieldRef<"UserFile", 'String'>
  readonly extension: Prisma.FieldRef<"UserFile", 'String'>
  readonly sha256: Prisma.FieldRef<"UserFile", 'String'>
  readonly sizeBytes: Prisma.FieldRef<"UserFile", 'Int'>
  readonly created_at: Prisma.FieldRef<"UserFile", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"UserFile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserFile findUnique
 */
export type UserFileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFile
   */
  select?: Prisma.UserFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFile
   */
  omit?: Prisma.UserFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileInclude<ExtArgs> | null
  /**
   * Filter, which UserFile to fetch.
   */
  where: Prisma.UserFileWhereUniqueInput
}

/**
 * UserFile findUniqueOrThrow
 */
export type UserFileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFile
   */
  select?: Prisma.UserFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFile
   */
  omit?: Prisma.UserFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileInclude<ExtArgs> | null
  /**
   * Filter, which UserFile to fetch.
   */
  where: Prisma.UserFileWhereUniqueInput
}

/**
 * UserFile findFirst
 */
export type UserFileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFile
   */
  select?: Prisma.UserFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFile
   */
  omit?: Prisma.UserFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileInclude<ExtArgs> | null
  /**
   * Filter, which UserFile to fetch.
   */
  where?: Prisma.UserFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserFiles to fetch.
   */
  orderBy?: Prisma.UserFileOrderByWithRelationInput | Prisma.UserFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserFiles.
   */
  cursor?: Prisma.UserFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserFiles.
   */
  distinct?: Prisma.UserFileScalarFieldEnum | Prisma.UserFileScalarFieldEnum[]
}

/**
 * UserFile findFirstOrThrow
 */
export type UserFileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFile
   */
  select?: Prisma.UserFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFile
   */
  omit?: Prisma.UserFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileInclude<ExtArgs> | null
  /**
   * Filter, which UserFile to fetch.
   */
  where?: Prisma.UserFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserFiles to fetch.
   */
  orderBy?: Prisma.UserFileOrderByWithRelationInput | Prisma.UserFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserFiles.
   */
  cursor?: Prisma.UserFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserFiles.
   */
  distinct?: Prisma.UserFileScalarFieldEnum | Prisma.UserFileScalarFieldEnum[]
}

/**
 * UserFile findMany
 */
export type UserFileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFile
   */
  select?: Prisma.UserFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFile
   */
  omit?: Prisma.UserFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileInclude<ExtArgs> | null
  /**
   * Filter, which UserFiles to fetch.
   */
  where?: Prisma.UserFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserFiles to fetch.
   */
  orderBy?: Prisma.UserFileOrderByWithRelationInput | Prisma.UserFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserFiles.
   */
  cursor?: Prisma.UserFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserFiles.
   */
  distinct?: Prisma.UserFileScalarFieldEnum | Prisma.UserFileScalarFieldEnum[]
}

/**
 * UserFile create
 */
export type UserFileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFile
   */
  select?: Prisma.UserFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFile
   */
  omit?: Prisma.UserFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileInclude<ExtArgs> | null
  /**
   * The data needed to create a UserFile.
   */
  data: Prisma.XOR<Prisma.UserFileCreateInput, Prisma.UserFileUncheckedCreateInput>
}

/**
 * UserFile createMany
 */
export type UserFileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserFiles.
   */
  data: Prisma.UserFileCreateManyInput | Prisma.UserFileCreateManyInput[]
}

/**
 * UserFile createManyAndReturn
 */
export type UserFileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFile
   */
  select?: Prisma.UserFileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserFile
   */
  omit?: Prisma.UserFileOmit<ExtArgs> | null
  /**
   * The data used to create many UserFiles.
   */
  data: Prisma.UserFileCreateManyInput | Prisma.UserFileCreateManyInput[]
}

/**
 * UserFile update
 */
export type UserFileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFile
   */
  select?: Prisma.UserFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFile
   */
  omit?: Prisma.UserFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileInclude<ExtArgs> | null
  /**
   * The data needed to update a UserFile.
   */
  data: Prisma.XOR<Prisma.UserFileUpdateInput, Prisma.UserFileUncheckedUpdateInput>
  /**
   * Choose, which UserFile to update.
   */
  where: Prisma.UserFileWhereUniqueInput
}

/**
 * UserFile updateMany
 */
export type UserFileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserFiles.
   */
  data: Prisma.XOR<Prisma.UserFileUpdateManyMutationInput, Prisma.UserFileUncheckedUpdateManyInput>
  /**
   * Filter which UserFiles to update
   */
  where?: Prisma.UserFileWhereInput
  /**
   * Limit how many UserFiles to update.
   */
  limit?: number
}

/**
 * UserFile updateManyAndReturn
 */
export type UserFileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFile
   */
  select?: Prisma.UserFileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserFile
   */
  omit?: Prisma.UserFileOmit<ExtArgs> | null
  /**
   * The data used to update UserFiles.
   */
  data: Prisma.XOR<Prisma.UserFileUpdateManyMutationInput, Prisma.UserFileUncheckedUpdateManyInput>
  /**
   * Filter which UserFiles to update
   */
  where?: Prisma.UserFileWhereInput
  /**
   * Limit how many UserFiles to update.
   */
  limit?: number
}

/**
 * UserFile upsert
 */
export type UserFileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFile
   */
  select?: Prisma.UserFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFile
   */
  omit?: Prisma.UserFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileInclude<ExtArgs> | null
  /**
   * The filter to search for the UserFile to update in case it exists.
   */
  where: Prisma.UserFileWhereUniqueInput
  /**
   * In case the UserFile found by the `where` argument doesn't exist, create a new UserFile with this data.
   */
  create: Prisma.XOR<Prisma.UserFileCreateInput, Prisma.UserFileUncheckedCreateInput>
  /**
   * In case the UserFile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserFileUpdateInput, Prisma.UserFileUncheckedUpdateInput>
}

/**
 * UserFile delete
 */
export type UserFileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFile
   */
  select?: Prisma.UserFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFile
   */
  omit?: Prisma.UserFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileInclude<ExtArgs> | null
  /**
   * Filter which UserFile to delete.
   */
  where: Prisma.UserFileWhereUniqueInput
}

/**
 * UserFile deleteMany
 */
export type UserFileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserFiles to delete
   */
  where?: Prisma.UserFileWhereInput
  /**
   * Limit how many UserFiles to delete.
   */
  limit?: number
}

/**
 * UserFile.shares
 */
export type UserFile$sharesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileShare
   */
  select?: Prisma.UserFileShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFileShare
   */
  omit?: Prisma.UserFileShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileShareInclude<ExtArgs> | null
  where?: Prisma.UserFileShareWhereInput
  orderBy?: Prisma.UserFileShareOrderByWithRelationInput | Prisma.UserFileShareOrderByWithRelationInput[]
  cursor?: Prisma.UserFileShareWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserFileShareScalarFieldEnum | Prisma.UserFileShareScalarFieldEnum[]
}

/**
 * UserFile without action
 */
export type UserFileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFile
   */
  select?: Prisma.UserFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFile
   */
  omit?: Prisma.UserFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileInclude<ExtArgs> | null
}
