
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserFileShare` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model UserFileShare
 * Who a file is shared with. Copying the pinboard's scope model: "GLOBAL"
 * (everyone), "ROLE" (scope_id = role_id) or "USER" (scope_id = user_id).
 * Kept as a string, not an enum, so new scopes can be added without a
 * migration. Which scopes a user may actually pick is enforced at the API
 * level (see UserFileRoutes.shareTargetsFor), not here.
 */
export type UserFileShareModel = runtime.Types.Result.DefaultSelection<Prisma.$UserFileSharePayload>

export type AggregateUserFileShare = {
  _count: UserFileShareCountAggregateOutputType | null
  _min: UserFileShareMinAggregateOutputType | null
  _max: UserFileShareMaxAggregateOutputType | null
}

export type UserFileShareMinAggregateOutputType = {
  id: string | null
  file_id: string | null
  scope_type: string | null
  scope_id: string | null
  created_at: Date | null
}

export type UserFileShareMaxAggregateOutputType = {
  id: string | null
  file_id: string | null
  scope_type: string | null
  scope_id: string | null
  created_at: Date | null
}

export type UserFileShareCountAggregateOutputType = {
  id: number
  file_id: number
  scope_type: number
  scope_id: number
  created_at: number
  _all: number
}


export type UserFileShareMinAggregateInputType = {
  id?: true
  file_id?: true
  scope_type?: true
  scope_id?: true
  created_at?: true
}

export type UserFileShareMaxAggregateInputType = {
  id?: true
  file_id?: true
  scope_type?: true
  scope_id?: true
  created_at?: true
}

export type UserFileShareCountAggregateInputType = {
  id?: true
  file_id?: true
  scope_type?: true
  scope_id?: true
  created_at?: true
  _all?: true
}

export type UserFileShareAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserFileShare to aggregate.
   */
  where?: Prisma.UserFileShareWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserFileShares to fetch.
   */
  orderBy?: Prisma.UserFileShareOrderByWithRelationInput | Prisma.UserFileShareOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserFileShareWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserFileShares from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserFileShares.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserFileShares
  **/
  _count?: true | UserFileShareCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserFileShareMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserFileShareMaxAggregateInputType
}

export type GetUserFileShareAggregateType<T extends UserFileShareAggregateArgs> = {
      [P in keyof T & keyof AggregateUserFileShare]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserFileShare[P]>
    : Prisma.GetScalarType<T[P], AggregateUserFileShare[P]>
}




export type UserFileShareGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserFileShareWhereInput
  orderBy?: Prisma.UserFileShareOrderByWithAggregationInput | Prisma.UserFileShareOrderByWithAggregationInput[]
  by: Prisma.UserFileShareScalarFieldEnum[] | Prisma.UserFileShareScalarFieldEnum
  having?: Prisma.UserFileShareScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserFileShareCountAggregateInputType | true
  _min?: UserFileShareMinAggregateInputType
  _max?: UserFileShareMaxAggregateInputType
}

export type UserFileShareGroupByOutputType = {
  id: string
  file_id: string
  scope_type: string
  scope_id: string | null
  created_at: Date
  _count: UserFileShareCountAggregateOutputType | null
  _min: UserFileShareMinAggregateOutputType | null
  _max: UserFileShareMaxAggregateOutputType | null
}

export type GetUserFileShareGroupByPayload<T extends UserFileShareGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserFileShareGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserFileShareGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserFileShareGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserFileShareGroupByOutputType[P]>
      }
    >
  >



export type UserFileShareWhereInput = {
  AND?: Prisma.UserFileShareWhereInput | Prisma.UserFileShareWhereInput[]
  OR?: Prisma.UserFileShareWhereInput[]
  NOT?: Prisma.UserFileShareWhereInput | Prisma.UserFileShareWhereInput[]
  id?: Prisma.StringFilter<"UserFileShare"> | string
  file_id?: Prisma.StringFilter<"UserFileShare"> | string
  scope_type?: Prisma.StringFilter<"UserFileShare"> | string
  scope_id?: Prisma.StringNullableFilter<"UserFileShare"> | string | null
  created_at?: Prisma.DateTimeFilter<"UserFileShare"> | Date | string
  file?: Prisma.XOR<Prisma.UserFileScalarRelationFilter, Prisma.UserFileWhereInput>
}

export type UserFileShareOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  file_id?: Prisma.SortOrder
  scope_type?: Prisma.SortOrder
  scope_id?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  file?: Prisma.UserFileOrderByWithRelationInput
}

export type UserFileShareWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UserFileShareWhereInput | Prisma.UserFileShareWhereInput[]
  OR?: Prisma.UserFileShareWhereInput[]
  NOT?: Prisma.UserFileShareWhereInput | Prisma.UserFileShareWhereInput[]
  file_id?: Prisma.StringFilter<"UserFileShare"> | string
  scope_type?: Prisma.StringFilter<"UserFileShare"> | string
  scope_id?: Prisma.StringNullableFilter<"UserFileShare"> | string | null
  created_at?: Prisma.DateTimeFilter<"UserFileShare"> | Date | string
  file?: Prisma.XOR<Prisma.UserFileScalarRelationFilter, Prisma.UserFileWhereInput>
}, "id">

export type UserFileShareOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  file_id?: Prisma.SortOrder
  scope_type?: Prisma.SortOrder
  scope_id?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.UserFileShareCountOrderByAggregateInput
  _max?: Prisma.UserFileShareMaxOrderByAggregateInput
  _min?: Prisma.UserFileShareMinOrderByAggregateInput
}

export type UserFileShareScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserFileShareScalarWhereWithAggregatesInput | Prisma.UserFileShareScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserFileShareScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserFileShareScalarWhereWithAggregatesInput | Prisma.UserFileShareScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserFileShare"> | string
  file_id?: Prisma.StringWithAggregatesFilter<"UserFileShare"> | string
  scope_type?: Prisma.StringWithAggregatesFilter<"UserFileShare"> | string
  scope_id?: Prisma.StringNullableWithAggregatesFilter<"UserFileShare"> | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"UserFileShare"> | Date | string
}

export type UserFileShareCreateInput = {
  id?: string
  scope_type: string
  scope_id?: string | null
  created_at?: Date | string
  file: Prisma.UserFileCreateNestedOneWithoutSharesInput
}

export type UserFileShareUncheckedCreateInput = {
  id?: string
  file_id: string
  scope_type: string
  scope_id?: string | null
  created_at?: Date | string
}

export type UserFileShareUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  file?: Prisma.UserFileUpdateOneRequiredWithoutSharesNestedInput
}

export type UserFileShareUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  file_id?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserFileShareCreateManyInput = {
  id?: string
  file_id: string
  scope_type: string
  scope_id?: string | null
  created_at?: Date | string
}

export type UserFileShareUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserFileShareUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  file_id?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserFileShareListRelationFilter = {
  every?: Prisma.UserFileShareWhereInput
  some?: Prisma.UserFileShareWhereInput
  none?: Prisma.UserFileShareWhereInput
}

export type UserFileShareOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserFileShareCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  file_id?: Prisma.SortOrder
  scope_type?: Prisma.SortOrder
  scope_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type UserFileShareMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  file_id?: Prisma.SortOrder
  scope_type?: Prisma.SortOrder
  scope_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type UserFileShareMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  file_id?: Prisma.SortOrder
  scope_type?: Prisma.SortOrder
  scope_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type UserFileShareCreateNestedManyWithoutFileInput = {
  create?: Prisma.XOR<Prisma.UserFileShareCreateWithoutFileInput, Prisma.UserFileShareUncheckedCreateWithoutFileInput> | Prisma.UserFileShareCreateWithoutFileInput[] | Prisma.UserFileShareUncheckedCreateWithoutFileInput[]
  connectOrCreate?: Prisma.UserFileShareCreateOrConnectWithoutFileInput | Prisma.UserFileShareCreateOrConnectWithoutFileInput[]
  createMany?: Prisma.UserFileShareCreateManyFileInputEnvelope
  connect?: Prisma.UserFileShareWhereUniqueInput | Prisma.UserFileShareWhereUniqueInput[]
}

export type UserFileShareUncheckedCreateNestedManyWithoutFileInput = {
  create?: Prisma.XOR<Prisma.UserFileShareCreateWithoutFileInput, Prisma.UserFileShareUncheckedCreateWithoutFileInput> | Prisma.UserFileShareCreateWithoutFileInput[] | Prisma.UserFileShareUncheckedCreateWithoutFileInput[]
  connectOrCreate?: Prisma.UserFileShareCreateOrConnectWithoutFileInput | Prisma.UserFileShareCreateOrConnectWithoutFileInput[]
  createMany?: Prisma.UserFileShareCreateManyFileInputEnvelope
  connect?: Prisma.UserFileShareWhereUniqueInput | Prisma.UserFileShareWhereUniqueInput[]
}

export type UserFileShareUpdateManyWithoutFileNestedInput = {
  create?: Prisma.XOR<Prisma.UserFileShareCreateWithoutFileInput, Prisma.UserFileShareUncheckedCreateWithoutFileInput> | Prisma.UserFileShareCreateWithoutFileInput[] | Prisma.UserFileShareUncheckedCreateWithoutFileInput[]
  connectOrCreate?: Prisma.UserFileShareCreateOrConnectWithoutFileInput | Prisma.UserFileShareCreateOrConnectWithoutFileInput[]
  upsert?: Prisma.UserFileShareUpsertWithWhereUniqueWithoutFileInput | Prisma.UserFileShareUpsertWithWhereUniqueWithoutFileInput[]
  createMany?: Prisma.UserFileShareCreateManyFileInputEnvelope
  set?: Prisma.UserFileShareWhereUniqueInput | Prisma.UserFileShareWhereUniqueInput[]
  disconnect?: Prisma.UserFileShareWhereUniqueInput | Prisma.UserFileShareWhereUniqueInput[]
  delete?: Prisma.UserFileShareWhereUniqueInput | Prisma.UserFileShareWhereUniqueInput[]
  connect?: Prisma.UserFileShareWhereUniqueInput | Prisma.UserFileShareWhereUniqueInput[]
  update?: Prisma.UserFileShareUpdateWithWhereUniqueWithoutFileInput | Prisma.UserFileShareUpdateWithWhereUniqueWithoutFileInput[]
  updateMany?: Prisma.UserFileShareUpdateManyWithWhereWithoutFileInput | Prisma.UserFileShareUpdateManyWithWhereWithoutFileInput[]
  deleteMany?: Prisma.UserFileShareScalarWhereInput | Prisma.UserFileShareScalarWhereInput[]
}

export type UserFileShareUncheckedUpdateManyWithoutFileNestedInput = {
  create?: Prisma.XOR<Prisma.UserFileShareCreateWithoutFileInput, Prisma.UserFileShareUncheckedCreateWithoutFileInput> | Prisma.UserFileShareCreateWithoutFileInput[] | Prisma.UserFileShareUncheckedCreateWithoutFileInput[]
  connectOrCreate?: Prisma.UserFileShareCreateOrConnectWithoutFileInput | Prisma.UserFileShareCreateOrConnectWithoutFileInput[]
  upsert?: Prisma.UserFileShareUpsertWithWhereUniqueWithoutFileInput | Prisma.UserFileShareUpsertWithWhereUniqueWithoutFileInput[]
  createMany?: Prisma.UserFileShareCreateManyFileInputEnvelope
  set?: Prisma.UserFileShareWhereUniqueInput | Prisma.UserFileShareWhereUniqueInput[]
  disconnect?: Prisma.UserFileShareWhereUniqueInput | Prisma.UserFileShareWhereUniqueInput[]
  delete?: Prisma.UserFileShareWhereUniqueInput | Prisma.UserFileShareWhereUniqueInput[]
  connect?: Prisma.UserFileShareWhereUniqueInput | Prisma.UserFileShareWhereUniqueInput[]
  update?: Prisma.UserFileShareUpdateWithWhereUniqueWithoutFileInput | Prisma.UserFileShareUpdateWithWhereUniqueWithoutFileInput[]
  updateMany?: Prisma.UserFileShareUpdateManyWithWhereWithoutFileInput | Prisma.UserFileShareUpdateManyWithWhereWithoutFileInput[]
  deleteMany?: Prisma.UserFileShareScalarWhereInput | Prisma.UserFileShareScalarWhereInput[]
}

export type UserFileShareCreateWithoutFileInput = {
  id?: string
  scope_type: string
  scope_id?: string | null
  created_at?: Date | string
}

export type UserFileShareUncheckedCreateWithoutFileInput = {
  id?: string
  scope_type: string
  scope_id?: string | null
  created_at?: Date | string
}

export type UserFileShareCreateOrConnectWithoutFileInput = {
  where: Prisma.UserFileShareWhereUniqueInput
  create: Prisma.XOR<Prisma.UserFileShareCreateWithoutFileInput, Prisma.UserFileShareUncheckedCreateWithoutFileInput>
}

export type UserFileShareCreateManyFileInputEnvelope = {
  data: Prisma.UserFileShareCreateManyFileInput | Prisma.UserFileShareCreateManyFileInput[]
}

export type UserFileShareUpsertWithWhereUniqueWithoutFileInput = {
  where: Prisma.UserFileShareWhereUniqueInput
  update: Prisma.XOR<Prisma.UserFileShareUpdateWithoutFileInput, Prisma.UserFileShareUncheckedUpdateWithoutFileInput>
  create: Prisma.XOR<Prisma.UserFileShareCreateWithoutFileInput, Prisma.UserFileShareUncheckedCreateWithoutFileInput>
}

export type UserFileShareUpdateWithWhereUniqueWithoutFileInput = {
  where: Prisma.UserFileShareWhereUniqueInput
  data: Prisma.XOR<Prisma.UserFileShareUpdateWithoutFileInput, Prisma.UserFileShareUncheckedUpdateWithoutFileInput>
}

export type UserFileShareUpdateManyWithWhereWithoutFileInput = {
  where: Prisma.UserFileShareScalarWhereInput
  data: Prisma.XOR<Prisma.UserFileShareUpdateManyMutationInput, Prisma.UserFileShareUncheckedUpdateManyWithoutFileInput>
}

export type UserFileShareScalarWhereInput = {
  AND?: Prisma.UserFileShareScalarWhereInput | Prisma.UserFileShareScalarWhereInput[]
  OR?: Prisma.UserFileShareScalarWhereInput[]
  NOT?: Prisma.UserFileShareScalarWhereInput | Prisma.UserFileShareScalarWhereInput[]
  id?: Prisma.StringFilter<"UserFileShare"> | string
  file_id?: Prisma.StringFilter<"UserFileShare"> | string
  scope_type?: Prisma.StringFilter<"UserFileShare"> | string
  scope_id?: Prisma.StringNullableFilter<"UserFileShare"> | string | null
  created_at?: Prisma.DateTimeFilter<"UserFileShare"> | Date | string
}

export type UserFileShareCreateManyFileInput = {
  id?: string
  scope_type: string
  scope_id?: string | null
  created_at?: Date | string
}

export type UserFileShareUpdateWithoutFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserFileShareUncheckedUpdateWithoutFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserFileShareUncheckedUpdateManyWithoutFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scope_type?: Prisma.StringFieldUpdateOperationsInput | string
  scope_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UserFileShareSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  file_id?: boolean
  scope_type?: boolean
  scope_id?: boolean
  created_at?: boolean
  file?: boolean | Prisma.UserFileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userFileShare"]>

export type UserFileShareSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  file_id?: boolean
  scope_type?: boolean
  scope_id?: boolean
  created_at?: boolean
  file?: boolean | Prisma.UserFileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userFileShare"]>

export type UserFileShareSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  file_id?: boolean
  scope_type?: boolean
  scope_id?: boolean
  created_at?: boolean
  file?: boolean | Prisma.UserFileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userFileShare"]>

export type UserFileShareSelectScalar = {
  id?: boolean
  file_id?: boolean
  scope_type?: boolean
  scope_id?: boolean
  created_at?: boolean
}

export type UserFileShareOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "file_id" | "scope_type" | "scope_id" | "created_at", ExtArgs["result"]["userFileShare"]>
export type UserFileShareInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  file?: boolean | Prisma.UserFileDefaultArgs<ExtArgs>
}
export type UserFileShareIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  file?: boolean | Prisma.UserFileDefaultArgs<ExtArgs>
}
export type UserFileShareIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  file?: boolean | Prisma.UserFileDefaultArgs<ExtArgs>
}

export type $UserFileSharePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserFileShare"
  objects: {
    file: Prisma.$UserFilePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    file_id: string
    scope_type: string
    scope_id: string | null
    created_at: Date
  }, ExtArgs["result"]["userFileShare"]>
  composites: {}
}

export type UserFileShareGetPayload<S extends boolean | null | undefined | UserFileShareDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserFileSharePayload, S>

export type UserFileShareCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFileShareFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserFileShareCountAggregateInputType | true
  }

export interface UserFileShareDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserFileShare'], meta: { name: 'UserFileShare' } }
  /**
   * Find zero or one UserFileShare that matches the filter.
   * @param {UserFileShareFindUniqueArgs} args - Arguments to find a UserFileShare
   * @example
   * // Get one UserFileShare
   * const userFileShare = await prisma.userFileShare.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFileShareFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFileShareFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserFileShareClient<runtime.Types.Result.GetResult<Prisma.$UserFileSharePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserFileShare that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFileShareFindUniqueOrThrowArgs} args - Arguments to find a UserFileShare
   * @example
   * // Get one UserFileShare
   * const userFileShare = await prisma.userFileShare.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFileShareFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFileShareFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserFileShareClient<runtime.Types.Result.GetResult<Prisma.$UserFileSharePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserFileShare that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileShareFindFirstArgs} args - Arguments to find a UserFileShare
   * @example
   * // Get one UserFileShare
   * const userFileShare = await prisma.userFileShare.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFileShareFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFileShareFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserFileShareClient<runtime.Types.Result.GetResult<Prisma.$UserFileSharePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserFileShare that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileShareFindFirstOrThrowArgs} args - Arguments to find a UserFileShare
   * @example
   * // Get one UserFileShare
   * const userFileShare = await prisma.userFileShare.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFileShareFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFileShareFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserFileShareClient<runtime.Types.Result.GetResult<Prisma.$UserFileSharePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserFileShares that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileShareFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserFileShares
   * const userFileShares = await prisma.userFileShare.findMany()
   * 
   * // Get first 10 UserFileShares
   * const userFileShares = await prisma.userFileShare.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userFileShareWithIdOnly = await prisma.userFileShare.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFileShareFindManyArgs>(args?: Prisma.SelectSubset<T, UserFileShareFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserFileSharePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserFileShare.
   * @param {UserFileShareCreateArgs} args - Arguments to create a UserFileShare.
   * @example
   * // Create one UserFileShare
   * const UserFileShare = await prisma.userFileShare.create({
   *   data: {
   *     // ... data to create a UserFileShare
   *   }
   * })
   * 
   */
  create<T extends UserFileShareCreateArgs>(args: Prisma.SelectSubset<T, UserFileShareCreateArgs<ExtArgs>>): Prisma.Prisma__UserFileShareClient<runtime.Types.Result.GetResult<Prisma.$UserFileSharePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserFileShares.
   * @param {UserFileShareCreateManyArgs} args - Arguments to create many UserFileShares.
   * @example
   * // Create many UserFileShares
   * const userFileShare = await prisma.userFileShare.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserFileShareCreateManyArgs>(args?: Prisma.SelectSubset<T, UserFileShareCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserFileShares and returns the data saved in the database.
   * @param {UserFileShareCreateManyAndReturnArgs} args - Arguments to create many UserFileShares.
   * @example
   * // Create many UserFileShares
   * const userFileShare = await prisma.userFileShare.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserFileShares and only return the `id`
   * const userFileShareWithIdOnly = await prisma.userFileShare.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserFileShareCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserFileShareCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserFileSharePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserFileShare.
   * @param {UserFileShareDeleteArgs} args - Arguments to delete one UserFileShare.
   * @example
   * // Delete one UserFileShare
   * const UserFileShare = await prisma.userFileShare.delete({
   *   where: {
   *     // ... filter to delete one UserFileShare
   *   }
   * })
   * 
   */
  delete<T extends UserFileShareDeleteArgs>(args: Prisma.SelectSubset<T, UserFileShareDeleteArgs<ExtArgs>>): Prisma.Prisma__UserFileShareClient<runtime.Types.Result.GetResult<Prisma.$UserFileSharePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserFileShare.
   * @param {UserFileShareUpdateArgs} args - Arguments to update one UserFileShare.
   * @example
   * // Update one UserFileShare
   * const userFileShare = await prisma.userFileShare.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserFileShareUpdateArgs>(args: Prisma.SelectSubset<T, UserFileShareUpdateArgs<ExtArgs>>): Prisma.Prisma__UserFileShareClient<runtime.Types.Result.GetResult<Prisma.$UserFileSharePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserFileShares.
   * @param {UserFileShareDeleteManyArgs} args - Arguments to filter UserFileShares to delete.
   * @example
   * // Delete a few UserFileShares
   * const { count } = await prisma.userFileShare.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserFileShareDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserFileShareDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserFileShares.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileShareUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserFileShares
   * const userFileShare = await prisma.userFileShare.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserFileShareUpdateManyArgs>(args: Prisma.SelectSubset<T, UserFileShareUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserFileShares and returns the data updated in the database.
   * @param {UserFileShareUpdateManyAndReturnArgs} args - Arguments to update many UserFileShares.
   * @example
   * // Update many UserFileShares
   * const userFileShare = await prisma.userFileShare.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserFileShares and only return the `id`
   * const userFileShareWithIdOnly = await prisma.userFileShare.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserFileShareUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserFileShareUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserFileSharePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserFileShare.
   * @param {UserFileShareUpsertArgs} args - Arguments to update or create a UserFileShare.
   * @example
   * // Update or create a UserFileShare
   * const userFileShare = await prisma.userFileShare.upsert({
   *   create: {
   *     // ... data to create a UserFileShare
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserFileShare we want to update
   *   }
   * })
   */
  upsert<T extends UserFileShareUpsertArgs>(args: Prisma.SelectSubset<T, UserFileShareUpsertArgs<ExtArgs>>): Prisma.Prisma__UserFileShareClient<runtime.Types.Result.GetResult<Prisma.$UserFileSharePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserFileShares.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileShareCountArgs} args - Arguments to filter UserFileShares to count.
   * @example
   * // Count the number of UserFileShares
   * const count = await prisma.userFileShare.count({
   *   where: {
   *     // ... the filter for the UserFileShares we want to count
   *   }
   * })
  **/
  count<T extends UserFileShareCountArgs>(
    args?: Prisma.Subset<T, UserFileShareCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserFileShareCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserFileShare.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileShareAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserFileShareAggregateArgs>(args: Prisma.Subset<T, UserFileShareAggregateArgs>): Prisma.PrismaPromise<GetUserFileShareAggregateType<T>>

  /**
   * Group by UserFileShare.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFileShareGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserFileShareGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserFileShareGroupByArgs['orderBy'] }
      : { orderBy?: UserFileShareGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserFileShareGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserFileShareGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserFileShare model
 */
readonly fields: UserFileShareFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserFileShare.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserFileShareClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  file<T extends Prisma.UserFileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserFileDefaultArgs<ExtArgs>>): Prisma.Prisma__UserFileClient<runtime.Types.Result.GetResult<Prisma.$UserFilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserFileShare model
 */
export interface UserFileShareFieldRefs {
  readonly id: Prisma.FieldRef<"UserFileShare", 'String'>
  readonly file_id: Prisma.FieldRef<"UserFileShare", 'String'>
  readonly scope_type: Prisma.FieldRef<"UserFileShare", 'String'>
  readonly scope_id: Prisma.FieldRef<"UserFileShare", 'String'>
  readonly created_at: Prisma.FieldRef<"UserFileShare", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserFileShare findUnique
 */
export type UserFileShareFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileShare
   */
  select?: Prisma.UserFileShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFileShare
   */
  omit?: Prisma.UserFileShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileShareInclude<ExtArgs> | null
  /**
   * Filter, which UserFileShare to fetch.
   */
  where: Prisma.UserFileShareWhereUniqueInput
}

/**
 * UserFileShare findUniqueOrThrow
 */
export type UserFileShareFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileShare
   */
  select?: Prisma.UserFileShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFileShare
   */
  omit?: Prisma.UserFileShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileShareInclude<ExtArgs> | null
  /**
   * Filter, which UserFileShare to fetch.
   */
  where: Prisma.UserFileShareWhereUniqueInput
}

/**
 * UserFileShare findFirst
 */
export type UserFileShareFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileShare
   */
  select?: Prisma.UserFileShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFileShare
   */
  omit?: Prisma.UserFileShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileShareInclude<ExtArgs> | null
  /**
   * Filter, which UserFileShare to fetch.
   */
  where?: Prisma.UserFileShareWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserFileShares to fetch.
   */
  orderBy?: Prisma.UserFileShareOrderByWithRelationInput | Prisma.UserFileShareOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserFileShares.
   */
  cursor?: Prisma.UserFileShareWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserFileShares from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserFileShares.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserFileShares.
   */
  distinct?: Prisma.UserFileShareScalarFieldEnum | Prisma.UserFileShareScalarFieldEnum[]
}

/**
 * UserFileShare findFirstOrThrow
 */
export type UserFileShareFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileShare
   */
  select?: Prisma.UserFileShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFileShare
   */
  omit?: Prisma.UserFileShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileShareInclude<ExtArgs> | null
  /**
   * Filter, which UserFileShare to fetch.
   */
  where?: Prisma.UserFileShareWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserFileShares to fetch.
   */
  orderBy?: Prisma.UserFileShareOrderByWithRelationInput | Prisma.UserFileShareOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserFileShares.
   */
  cursor?: Prisma.UserFileShareWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserFileShares from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserFileShares.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserFileShares.
   */
  distinct?: Prisma.UserFileShareScalarFieldEnum | Prisma.UserFileShareScalarFieldEnum[]
}

/**
 * UserFileShare findMany
 */
export type UserFileShareFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileShare
   */
  select?: Prisma.UserFileShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFileShare
   */
  omit?: Prisma.UserFileShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileShareInclude<ExtArgs> | null
  /**
   * Filter, which UserFileShares to fetch.
   */
  where?: Prisma.UserFileShareWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserFileShares to fetch.
   */
  orderBy?: Prisma.UserFileShareOrderByWithRelationInput | Prisma.UserFileShareOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserFileShares.
   */
  cursor?: Prisma.UserFileShareWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserFileShares from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserFileShares.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserFileShares.
   */
  distinct?: Prisma.UserFileShareScalarFieldEnum | Prisma.UserFileShareScalarFieldEnum[]
}

/**
 * UserFileShare create
 */
export type UserFileShareCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileShare
   */
  select?: Prisma.UserFileShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFileShare
   */
  omit?: Prisma.UserFileShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileShareInclude<ExtArgs> | null
  /**
   * The data needed to create a UserFileShare.
   */
  data: Prisma.XOR<Prisma.UserFileShareCreateInput, Prisma.UserFileShareUncheckedCreateInput>
}

/**
 * UserFileShare createMany
 */
export type UserFileShareCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserFileShares.
   */
  data: Prisma.UserFileShareCreateManyInput | Prisma.UserFileShareCreateManyInput[]
}

/**
 * UserFileShare createManyAndReturn
 */
export type UserFileShareCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileShare
   */
  select?: Prisma.UserFileShareSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserFileShare
   */
  omit?: Prisma.UserFileShareOmit<ExtArgs> | null
  /**
   * The data used to create many UserFileShares.
   */
  data: Prisma.UserFileShareCreateManyInput | Prisma.UserFileShareCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileShareIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserFileShare update
 */
export type UserFileShareUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileShare
   */
  select?: Prisma.UserFileShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFileShare
   */
  omit?: Prisma.UserFileShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileShareInclude<ExtArgs> | null
  /**
   * The data needed to update a UserFileShare.
   */
  data: Prisma.XOR<Prisma.UserFileShareUpdateInput, Prisma.UserFileShareUncheckedUpdateInput>
  /**
   * Choose, which UserFileShare to update.
   */
  where: Prisma.UserFileShareWhereUniqueInput
}

/**
 * UserFileShare updateMany
 */
export type UserFileShareUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserFileShares.
   */
  data: Prisma.XOR<Prisma.UserFileShareUpdateManyMutationInput, Prisma.UserFileShareUncheckedUpdateManyInput>
  /**
   * Filter which UserFileShares to update
   */
  where?: Prisma.UserFileShareWhereInput
  /**
   * Limit how many UserFileShares to update.
   */
  limit?: number
}

/**
 * UserFileShare updateManyAndReturn
 */
export type UserFileShareUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileShare
   */
  select?: Prisma.UserFileShareSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserFileShare
   */
  omit?: Prisma.UserFileShareOmit<ExtArgs> | null
  /**
   * The data used to update UserFileShares.
   */
  data: Prisma.XOR<Prisma.UserFileShareUpdateManyMutationInput, Prisma.UserFileShareUncheckedUpdateManyInput>
  /**
   * Filter which UserFileShares to update
   */
  where?: Prisma.UserFileShareWhereInput
  /**
   * Limit how many UserFileShares to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileShareIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserFileShare upsert
 */
export type UserFileShareUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileShare
   */
  select?: Prisma.UserFileShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFileShare
   */
  omit?: Prisma.UserFileShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileShareInclude<ExtArgs> | null
  /**
   * The filter to search for the UserFileShare to update in case it exists.
   */
  where: Prisma.UserFileShareWhereUniqueInput
  /**
   * In case the UserFileShare found by the `where` argument doesn't exist, create a new UserFileShare with this data.
   */
  create: Prisma.XOR<Prisma.UserFileShareCreateInput, Prisma.UserFileShareUncheckedCreateInput>
  /**
   * In case the UserFileShare was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserFileShareUpdateInput, Prisma.UserFileShareUncheckedUpdateInput>
}

/**
 * UserFileShare delete
 */
export type UserFileShareDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileShare
   */
  select?: Prisma.UserFileShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFileShare
   */
  omit?: Prisma.UserFileShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileShareInclude<ExtArgs> | null
  /**
   * Filter which UserFileShare to delete.
   */
  where: Prisma.UserFileShareWhereUniqueInput
}

/**
 * UserFileShare deleteMany
 */
export type UserFileShareDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserFileShares to delete
   */
  where?: Prisma.UserFileShareWhereInput
  /**
   * Limit how many UserFileShares to delete.
   */
  limit?: number
}

/**
 * UserFileShare without action
 */
export type UserFileShareDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserFileShare
   */
  select?: Prisma.UserFileShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserFileShare
   */
  omit?: Prisma.UserFileShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserFileShareInclude<ExtArgs> | null
}
