
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.ts"
import { type PrismaClient } from "./class.ts"

export type * from '../models.ts'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Bag: 'Bag',
  BagPermission: 'BagPermission',
  Tiddler: 'Tiddler',
  TiddlerEvent: 'TiddlerEvent',
  Template: 'Template',
  TemplatePermission: 'TemplatePermission',
  Recipe: 'Recipe',
  RecipePermission: 'RecipePermission',
  RecipeBag: 'RecipeBag',
  Settings: 'Settings',
  Roles: 'Roles',
  Users: 'Users',
  Sessions: 'Sessions',
  PinboardNote: 'PinboardNote',
  PinboardNoteRead: 'PinboardNoteRead',
  PinboardNotePosition: 'PinboardNotePosition'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "bag" | "bagPermission" | "tiddler" | "tiddlerEvent" | "template" | "templatePermission" | "recipe" | "recipePermission" | "recipeBag" | "settings" | "roles" | "users" | "sessions" | "pinboardNote" | "pinboardNoteRead" | "pinboardNotePosition"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Bag: {
      payload: Prisma.$BagPayload<ExtArgs>
      fields: Prisma.BagFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BagFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BagFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPayload>
        }
        findFirst: {
          args: Prisma.BagFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BagFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPayload>
        }
        findMany: {
          args: Prisma.BagFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPayload>[]
        }
        create: {
          args: Prisma.BagCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPayload>
        }
        createMany: {
          args: Prisma.BagCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BagCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPayload>[]
        }
        delete: {
          args: Prisma.BagDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPayload>
        }
        update: {
          args: Prisma.BagUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPayload>
        }
        deleteMany: {
          args: Prisma.BagDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BagUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BagUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPayload>[]
        }
        upsert: {
          args: Prisma.BagUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPayload>
        }
        aggregate: {
          args: Prisma.BagAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBag>
        }
        groupBy: {
          args: Prisma.BagGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BagGroupByOutputType>[]
        }
        count: {
          args: Prisma.BagCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BagCountAggregateOutputType> | number
        }
      }
    }
    BagPermission: {
      payload: Prisma.$BagPermissionPayload<ExtArgs>
      fields: Prisma.BagPermissionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BagPermissionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPermissionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BagPermissionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPermissionPayload>
        }
        findFirst: {
          args: Prisma.BagPermissionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPermissionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BagPermissionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPermissionPayload>
        }
        findMany: {
          args: Prisma.BagPermissionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPermissionPayload>[]
        }
        create: {
          args: Prisma.BagPermissionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPermissionPayload>
        }
        createMany: {
          args: Prisma.BagPermissionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BagPermissionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPermissionPayload>[]
        }
        delete: {
          args: Prisma.BagPermissionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPermissionPayload>
        }
        update: {
          args: Prisma.BagPermissionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPermissionPayload>
        }
        deleteMany: {
          args: Prisma.BagPermissionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BagPermissionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BagPermissionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPermissionPayload>[]
        }
        upsert: {
          args: Prisma.BagPermissionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BagPermissionPayload>
        }
        aggregate: {
          args: Prisma.BagPermissionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBagPermission>
        }
        groupBy: {
          args: Prisma.BagPermissionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BagPermissionGroupByOutputType>[]
        }
        count: {
          args: Prisma.BagPermissionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BagPermissionCountAggregateOutputType> | number
        }
      }
    }
    Tiddler: {
      payload: Prisma.$TiddlerPayload<ExtArgs>
      fields: Prisma.TiddlerFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TiddlerFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TiddlerFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerPayload>
        }
        findFirst: {
          args: Prisma.TiddlerFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TiddlerFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerPayload>
        }
        findMany: {
          args: Prisma.TiddlerFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerPayload>[]
        }
        create: {
          args: Prisma.TiddlerCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerPayload>
        }
        createMany: {
          args: Prisma.TiddlerCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TiddlerCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerPayload>[]
        }
        delete: {
          args: Prisma.TiddlerDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerPayload>
        }
        update: {
          args: Prisma.TiddlerUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerPayload>
        }
        deleteMany: {
          args: Prisma.TiddlerDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TiddlerUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TiddlerUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerPayload>[]
        }
        upsert: {
          args: Prisma.TiddlerUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerPayload>
        }
        aggregate: {
          args: Prisma.TiddlerAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTiddler>
        }
        groupBy: {
          args: Prisma.TiddlerGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TiddlerGroupByOutputType>[]
        }
        count: {
          args: Prisma.TiddlerCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TiddlerCountAggregateOutputType> | number
        }
      }
    }
    TiddlerEvent: {
      payload: Prisma.$TiddlerEventPayload<ExtArgs>
      fields: Prisma.TiddlerEventFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TiddlerEventFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerEventPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TiddlerEventFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerEventPayload>
        }
        findFirst: {
          args: Prisma.TiddlerEventFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerEventPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TiddlerEventFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerEventPayload>
        }
        findMany: {
          args: Prisma.TiddlerEventFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerEventPayload>[]
        }
        create: {
          args: Prisma.TiddlerEventCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerEventPayload>
        }
        createMany: {
          args: Prisma.TiddlerEventCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TiddlerEventCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerEventPayload>[]
        }
        delete: {
          args: Prisma.TiddlerEventDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerEventPayload>
        }
        update: {
          args: Prisma.TiddlerEventUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerEventPayload>
        }
        deleteMany: {
          args: Prisma.TiddlerEventDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TiddlerEventUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TiddlerEventUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerEventPayload>[]
        }
        upsert: {
          args: Prisma.TiddlerEventUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiddlerEventPayload>
        }
        aggregate: {
          args: Prisma.TiddlerEventAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTiddlerEvent>
        }
        groupBy: {
          args: Prisma.TiddlerEventGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TiddlerEventGroupByOutputType>[]
        }
        count: {
          args: Prisma.TiddlerEventCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TiddlerEventCountAggregateOutputType> | number
        }
      }
    }
    Template: {
      payload: Prisma.$TemplatePayload<ExtArgs>
      fields: Prisma.TemplateFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TemplateFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TemplateFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>
        }
        findFirst: {
          args: Prisma.TemplateFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TemplateFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>
        }
        findMany: {
          args: Prisma.TemplateFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>[]
        }
        create: {
          args: Prisma.TemplateCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>
        }
        createMany: {
          args: Prisma.TemplateCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TemplateCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>[]
        }
        delete: {
          args: Prisma.TemplateDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>
        }
        update: {
          args: Prisma.TemplateUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>
        }
        deleteMany: {
          args: Prisma.TemplateDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TemplateUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TemplateUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>[]
        }
        upsert: {
          args: Prisma.TemplateUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePayload>
        }
        aggregate: {
          args: Prisma.TemplateAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTemplate>
        }
        groupBy: {
          args: Prisma.TemplateGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TemplateGroupByOutputType>[]
        }
        count: {
          args: Prisma.TemplateCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TemplateCountAggregateOutputType> | number
        }
      }
    }
    TemplatePermission: {
      payload: Prisma.$TemplatePermissionPayload<ExtArgs>
      fields: Prisma.TemplatePermissionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TemplatePermissionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePermissionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TemplatePermissionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePermissionPayload>
        }
        findFirst: {
          args: Prisma.TemplatePermissionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePermissionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TemplatePermissionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePermissionPayload>
        }
        findMany: {
          args: Prisma.TemplatePermissionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePermissionPayload>[]
        }
        create: {
          args: Prisma.TemplatePermissionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePermissionPayload>
        }
        createMany: {
          args: Prisma.TemplatePermissionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TemplatePermissionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePermissionPayload>[]
        }
        delete: {
          args: Prisma.TemplatePermissionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePermissionPayload>
        }
        update: {
          args: Prisma.TemplatePermissionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePermissionPayload>
        }
        deleteMany: {
          args: Prisma.TemplatePermissionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TemplatePermissionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TemplatePermissionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePermissionPayload>[]
        }
        upsert: {
          args: Prisma.TemplatePermissionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TemplatePermissionPayload>
        }
        aggregate: {
          args: Prisma.TemplatePermissionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTemplatePermission>
        }
        groupBy: {
          args: Prisma.TemplatePermissionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TemplatePermissionGroupByOutputType>[]
        }
        count: {
          args: Prisma.TemplatePermissionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TemplatePermissionCountAggregateOutputType> | number
        }
      }
    }
    Recipe: {
      payload: Prisma.$RecipePayload<ExtArgs>
      fields: Prisma.RecipeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RecipeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RecipeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>
        }
        findFirst: {
          args: Prisma.RecipeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RecipeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>
        }
        findMany: {
          args: Prisma.RecipeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>[]
        }
        create: {
          args: Prisma.RecipeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>
        }
        createMany: {
          args: Prisma.RecipeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RecipeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>[]
        }
        delete: {
          args: Prisma.RecipeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>
        }
        update: {
          args: Prisma.RecipeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>
        }
        deleteMany: {
          args: Prisma.RecipeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RecipeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RecipeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>[]
        }
        upsert: {
          args: Prisma.RecipeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePayload>
        }
        aggregate: {
          args: Prisma.RecipeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRecipe>
        }
        groupBy: {
          args: Prisma.RecipeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeGroupByOutputType>[]
        }
        count: {
          args: Prisma.RecipeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeCountAggregateOutputType> | number
        }
      }
    }
    RecipePermission: {
      payload: Prisma.$RecipePermissionPayload<ExtArgs>
      fields: Prisma.RecipePermissionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RecipePermissionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePermissionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RecipePermissionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePermissionPayload>
        }
        findFirst: {
          args: Prisma.RecipePermissionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePermissionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RecipePermissionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePermissionPayload>
        }
        findMany: {
          args: Prisma.RecipePermissionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePermissionPayload>[]
        }
        create: {
          args: Prisma.RecipePermissionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePermissionPayload>
        }
        createMany: {
          args: Prisma.RecipePermissionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RecipePermissionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePermissionPayload>[]
        }
        delete: {
          args: Prisma.RecipePermissionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePermissionPayload>
        }
        update: {
          args: Prisma.RecipePermissionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePermissionPayload>
        }
        deleteMany: {
          args: Prisma.RecipePermissionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RecipePermissionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RecipePermissionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePermissionPayload>[]
        }
        upsert: {
          args: Prisma.RecipePermissionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipePermissionPayload>
        }
        aggregate: {
          args: Prisma.RecipePermissionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRecipePermission>
        }
        groupBy: {
          args: Prisma.RecipePermissionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipePermissionGroupByOutputType>[]
        }
        count: {
          args: Prisma.RecipePermissionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipePermissionCountAggregateOutputType> | number
        }
      }
    }
    RecipeBag: {
      payload: Prisma.$RecipeBagPayload<ExtArgs>
      fields: Prisma.RecipeBagFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RecipeBagFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeBagPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RecipeBagFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeBagPayload>
        }
        findFirst: {
          args: Prisma.RecipeBagFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeBagPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RecipeBagFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeBagPayload>
        }
        findMany: {
          args: Prisma.RecipeBagFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeBagPayload>[]
        }
        create: {
          args: Prisma.RecipeBagCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeBagPayload>
        }
        createMany: {
          args: Prisma.RecipeBagCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RecipeBagCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeBagPayload>[]
        }
        delete: {
          args: Prisma.RecipeBagDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeBagPayload>
        }
        update: {
          args: Prisma.RecipeBagUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeBagPayload>
        }
        deleteMany: {
          args: Prisma.RecipeBagDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RecipeBagUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RecipeBagUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeBagPayload>[]
        }
        upsert: {
          args: Prisma.RecipeBagUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RecipeBagPayload>
        }
        aggregate: {
          args: Prisma.RecipeBagAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRecipeBag>
        }
        groupBy: {
          args: Prisma.RecipeBagGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeBagGroupByOutputType>[]
        }
        count: {
          args: Prisma.RecipeBagCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RecipeBagCountAggregateOutputType> | number
        }
      }
    }
    Settings: {
      payload: Prisma.$SettingsPayload<ExtArgs>
      fields: Prisma.SettingsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SettingsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SettingsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>
        }
        findFirst: {
          args: Prisma.SettingsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SettingsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>
        }
        findMany: {
          args: Prisma.SettingsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>[]
        }
        create: {
          args: Prisma.SettingsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>
        }
        createMany: {
          args: Prisma.SettingsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SettingsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>[]
        }
        delete: {
          args: Prisma.SettingsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>
        }
        update: {
          args: Prisma.SettingsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>
        }
        deleteMany: {
          args: Prisma.SettingsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SettingsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SettingsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>[]
        }
        upsert: {
          args: Prisma.SettingsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>
        }
        aggregate: {
          args: Prisma.SettingsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSettings>
        }
        groupBy: {
          args: Prisma.SettingsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SettingsGroupByOutputType>[]
        }
        count: {
          args: Prisma.SettingsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SettingsCountAggregateOutputType> | number
        }
      }
    }
    Roles: {
      payload: Prisma.$RolesPayload<ExtArgs>
      fields: Prisma.RolesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RolesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RolesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>
        }
        findFirst: {
          args: Prisma.RolesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RolesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>
        }
        findMany: {
          args: Prisma.RolesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>[]
        }
        create: {
          args: Prisma.RolesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>
        }
        createMany: {
          args: Prisma.RolesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RolesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>[]
        }
        delete: {
          args: Prisma.RolesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>
        }
        update: {
          args: Prisma.RolesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>
        }
        deleteMany: {
          args: Prisma.RolesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RolesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RolesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>[]
        }
        upsert: {
          args: Prisma.RolesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RolesPayload>
        }
        aggregate: {
          args: Prisma.RolesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRoles>
        }
        groupBy: {
          args: Prisma.RolesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RolesGroupByOutputType>[]
        }
        count: {
          args: Prisma.RolesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RolesCountAggregateOutputType> | number
        }
      }
    }
    Users: {
      payload: Prisma.$UsersPayload<ExtArgs>
      fields: Prisma.UsersFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UsersFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UsersFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        findFirst: {
          args: Prisma.UsersFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UsersFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        findMany: {
          args: Prisma.UsersFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>[]
        }
        create: {
          args: Prisma.UsersCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        createMany: {
          args: Prisma.UsersCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UsersCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>[]
        }
        delete: {
          args: Prisma.UsersDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        update: {
          args: Prisma.UsersUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        deleteMany: {
          args: Prisma.UsersDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UsersUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UsersUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>[]
        }
        upsert: {
          args: Prisma.UsersUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        aggregate: {
          args: Prisma.UsersAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUsers>
        }
        groupBy: {
          args: Prisma.UsersGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsersGroupByOutputType>[]
        }
        count: {
          args: Prisma.UsersCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsersCountAggregateOutputType> | number
        }
      }
    }
    Sessions: {
      payload: Prisma.$SessionsPayload<ExtArgs>
      fields: Prisma.SessionsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SessionsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SessionsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionsPayload>
        }
        findFirst: {
          args: Prisma.SessionsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SessionsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionsPayload>
        }
        findMany: {
          args: Prisma.SessionsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionsPayload>[]
        }
        create: {
          args: Prisma.SessionsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionsPayload>
        }
        createMany: {
          args: Prisma.SessionsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SessionsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionsPayload>[]
        }
        delete: {
          args: Prisma.SessionsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionsPayload>
        }
        update: {
          args: Prisma.SessionsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionsPayload>
        }
        deleteMany: {
          args: Prisma.SessionsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SessionsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SessionsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionsPayload>[]
        }
        upsert: {
          args: Prisma.SessionsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SessionsPayload>
        }
        aggregate: {
          args: Prisma.SessionsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSessions>
        }
        groupBy: {
          args: Prisma.SessionsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SessionsGroupByOutputType>[]
        }
        count: {
          args: Prisma.SessionsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SessionsCountAggregateOutputType> | number
        }
      }
    }
    PinboardNote: {
      payload: Prisma.$PinboardNotePayload<ExtArgs>
      fields: Prisma.PinboardNoteFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PinboardNoteFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PinboardNoteFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePayload>
        }
        findFirst: {
          args: Prisma.PinboardNoteFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PinboardNoteFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePayload>
        }
        findMany: {
          args: Prisma.PinboardNoteFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePayload>[]
        }
        create: {
          args: Prisma.PinboardNoteCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePayload>
        }
        createMany: {
          args: Prisma.PinboardNoteCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PinboardNoteCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePayload>[]
        }
        delete: {
          args: Prisma.PinboardNoteDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePayload>
        }
        update: {
          args: Prisma.PinboardNoteUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePayload>
        }
        deleteMany: {
          args: Prisma.PinboardNoteDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PinboardNoteUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PinboardNoteUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePayload>[]
        }
        upsert: {
          args: Prisma.PinboardNoteUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePayload>
        }
        aggregate: {
          args: Prisma.PinboardNoteAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePinboardNote>
        }
        groupBy: {
          args: Prisma.PinboardNoteGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PinboardNoteGroupByOutputType>[]
        }
        count: {
          args: Prisma.PinboardNoteCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PinboardNoteCountAggregateOutputType> | number
        }
      }
    }
    PinboardNoteRead: {
      payload: Prisma.$PinboardNoteReadPayload<ExtArgs>
      fields: Prisma.PinboardNoteReadFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PinboardNoteReadFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNoteReadPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PinboardNoteReadFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNoteReadPayload>
        }
        findFirst: {
          args: Prisma.PinboardNoteReadFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNoteReadPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PinboardNoteReadFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNoteReadPayload>
        }
        findMany: {
          args: Prisma.PinboardNoteReadFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNoteReadPayload>[]
        }
        create: {
          args: Prisma.PinboardNoteReadCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNoteReadPayload>
        }
        createMany: {
          args: Prisma.PinboardNoteReadCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PinboardNoteReadCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNoteReadPayload>[]
        }
        delete: {
          args: Prisma.PinboardNoteReadDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNoteReadPayload>
        }
        update: {
          args: Prisma.PinboardNoteReadUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNoteReadPayload>
        }
        deleteMany: {
          args: Prisma.PinboardNoteReadDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PinboardNoteReadUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PinboardNoteReadUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNoteReadPayload>[]
        }
        upsert: {
          args: Prisma.PinboardNoteReadUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNoteReadPayload>
        }
        aggregate: {
          args: Prisma.PinboardNoteReadAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePinboardNoteRead>
        }
        groupBy: {
          args: Prisma.PinboardNoteReadGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PinboardNoteReadGroupByOutputType>[]
        }
        count: {
          args: Prisma.PinboardNoteReadCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PinboardNoteReadCountAggregateOutputType> | number
        }
      }
    }
    PinboardNotePosition: {
      payload: Prisma.$PinboardNotePositionPayload<ExtArgs>
      fields: Prisma.PinboardNotePositionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PinboardNotePositionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePositionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PinboardNotePositionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePositionPayload>
        }
        findFirst: {
          args: Prisma.PinboardNotePositionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePositionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PinboardNotePositionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePositionPayload>
        }
        findMany: {
          args: Prisma.PinboardNotePositionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePositionPayload>[]
        }
        create: {
          args: Prisma.PinboardNotePositionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePositionPayload>
        }
        createMany: {
          args: Prisma.PinboardNotePositionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PinboardNotePositionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePositionPayload>[]
        }
        delete: {
          args: Prisma.PinboardNotePositionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePositionPayload>
        }
        update: {
          args: Prisma.PinboardNotePositionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePositionPayload>
        }
        deleteMany: {
          args: Prisma.PinboardNotePositionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PinboardNotePositionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PinboardNotePositionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePositionPayload>[]
        }
        upsert: {
          args: Prisma.PinboardNotePositionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PinboardNotePositionPayload>
        }
        aggregate: {
          args: Prisma.PinboardNotePositionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePinboardNotePosition>
        }
        groupBy: {
          args: Prisma.PinboardNotePositionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PinboardNotePositionGroupByOutputType>[]
        }
        count: {
          args: Prisma.PinboardNotePositionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PinboardNotePositionCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const BagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  created: 'created',
  updated: 'updated',
  description: 'description',
  owner_user_id: 'owner_user_id'
} as const

export type BagScalarFieldEnum = (typeof BagScalarFieldEnum)[keyof typeof BagScalarFieldEnum]


export const BagPermissionScalarFieldEnum = {
  bag_id: 'bag_id',
  role_id: 'role_id',
  level: 'level'
} as const

export type BagPermissionScalarFieldEnum = (typeof BagPermissionScalarFieldEnum)[keyof typeof BagPermissionScalarFieldEnum]


export const TiddlerScalarFieldEnum = {
  bag_id: 'bag_id',
  title: 'title',
  created: 'created',
  updated: 'updated',
  revision: 'revision',
  fields: 'fields'
} as const

export type TiddlerScalarFieldEnum = (typeof TiddlerScalarFieldEnum)[keyof typeof TiddlerScalarFieldEnum]


export const TiddlerEventScalarFieldEnum = {
  seq: 'seq',
  bag_id: 'bag_id',
  title: 'title',
  type: 'type'
} as const

export type TiddlerEventScalarFieldEnum = (typeof TiddlerEventScalarFieldEnum)[keyof typeof TiddlerEventScalarFieldEnum]


export const TemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  created: 'created',
  updated: 'updated',
  owner_user_id: 'owner_user_id',
  type: 'type',
  definition: 'definition'
} as const

export type TemplateScalarFieldEnum = (typeof TemplateScalarFieldEnum)[keyof typeof TemplateScalarFieldEnum]


export const TemplatePermissionScalarFieldEnum = {
  template_id: 'template_id',
  role_id: 'role_id',
  level: 'level'
} as const

export type TemplatePermissionScalarFieldEnum = (typeof TemplatePermissionScalarFieldEnum)[keyof typeof TemplatePermissionScalarFieldEnum]


export const RecipeScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  created: 'created',
  updated: 'updated',
  owner_user_id: 'owner_user_id',
  template_id: 'template_id',
  definition: 'definition',
  plugins: 'plugins',
  compiledAt: 'compiledAt'
} as const

export type RecipeScalarFieldEnum = (typeof RecipeScalarFieldEnum)[keyof typeof RecipeScalarFieldEnum]


export const RecipePermissionScalarFieldEnum = {
  recipe_id: 'recipe_id',
  role_id: 'role_id',
  level: 'level'
} as const

export type RecipePermissionScalarFieldEnum = (typeof RecipePermissionScalarFieldEnum)[keyof typeof RecipePermissionScalarFieldEnum]


export const RecipeBagScalarFieldEnum = {
  recipe_id: 'recipe_id',
  bag_id: 'bag_id',
  priority: 'priority',
  is_writable: 'is_writable',
  prefix: 'prefix'
} as const

export type RecipeBagScalarFieldEnum = (typeof RecipeBagScalarFieldEnum)[keyof typeof RecipeBagScalarFieldEnum]


export const SettingsScalarFieldEnum = {
  key: 'key',
  value: 'value',
  updated: 'updated'
} as const

export type SettingsScalarFieldEnum = (typeof SettingsScalarFieldEnum)[keyof typeof SettingsScalarFieldEnum]


export const RolesScalarFieldEnum = {
  role_id: 'role_id',
  role_name: 'role_name',
  description: 'description',
  is_teacher: 'is_teacher',
  owner_user_id: 'owner_user_id'
} as const

export type RolesScalarFieldEnum = (typeof RolesScalarFieldEnum)[keyof typeof RolesScalarFieldEnum]


export const UsersScalarFieldEnum = {
  user_id: 'user_id',
  username: 'username',
  email: 'email',
  password: 'password',
  owner_user_id: 'owner_user_id',
  resetCode: 'resetCode',
  created_at: 'created_at',
  last_login: 'last_login',
  wiki_limit: 'wiki_limit'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const SessionsScalarFieldEnum = {
  session_id: 'session_id',
  created_at: 'created_at',
  last_accessed: 'last_accessed',
  session_key: 'session_key',
  user_id: 'user_id'
} as const

export type SessionsScalarFieldEnum = (typeof SessionsScalarFieldEnum)[keyof typeof SessionsScalarFieldEnum]


export const PinboardNoteScalarFieldEnum = {
  id: 'id',
  author_user_id: 'author_user_id',
  author_name: 'author_name',
  scope_type: 'scope_type',
  scope_id: 'scope_id',
  body: 'body',
  color: 'color',
  is_important: 'is_important',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at',
  expires_at: 'expires_at'
} as const

export type PinboardNoteScalarFieldEnum = (typeof PinboardNoteScalarFieldEnum)[keyof typeof PinboardNoteScalarFieldEnum]


export const PinboardNoteReadScalarFieldEnum = {
  note_id: 'note_id',
  user_id: 'user_id',
  read_at: 'read_at',
  dismissed_at: 'dismissed_at'
} as const

export type PinboardNoteReadScalarFieldEnum = (typeof PinboardNoteReadScalarFieldEnum)[keyof typeof PinboardNoteReadScalarFieldEnum]


export const PinboardNotePositionScalarFieldEnum = {
  note_id: 'note_id',
  user_id: 'user_id',
  x: 'x',
  y: 'y'
} as const

export type PinboardNotePositionScalarFieldEnum = (typeof PinboardNotePositionScalarFieldEnum)[keyof typeof PinboardNotePositionScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'BagPermissionLevel'
 */
export type EnumBagPermissionLevelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BagPermissionLevel'>
    


/**
 * Reference to a field of type 'BigInt'
 */
export type BigIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BigInt'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'TiddlerEventType'
 */
export type EnumTiddlerEventTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TiddlerEventType'>
    


/**
 * Reference to a field of type 'TemplatePermissionLevel'
 */
export type EnumTemplatePermissionLevelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TemplatePermissionLevel'>
    


/**
 * Reference to a field of type 'RecipePermissionLevel'
 */
export type EnumRecipePermissionLevelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'RecipePermissionLevel'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  bag?: Prisma.BagOmit
  bagPermission?: Prisma.BagPermissionOmit
  tiddler?: Prisma.TiddlerOmit
  tiddlerEvent?: Prisma.TiddlerEventOmit
  template?: Prisma.TemplateOmit
  templatePermission?: Prisma.TemplatePermissionOmit
  recipe?: Prisma.RecipeOmit
  recipePermission?: Prisma.RecipePermissionOmit
  recipeBag?: Prisma.RecipeBagOmit
  settings?: Prisma.SettingsOmit
  roles?: Prisma.RolesOmit
  users?: Prisma.UsersOmit
  sessions?: Prisma.SessionsOmit
  pinboardNote?: Prisma.PinboardNoteOmit
  pinboardNoteRead?: Prisma.PinboardNoteReadOmit
  pinboardNotePosition?: Prisma.PinboardNotePositionOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

