import { createRequire } from "module";
const require = createRequire("/home/r2d2/Documents/AI_Master/MultiWikiServer-wikiwise/package.json");
const { chromium } = require("playwright-core");
const b = await chromium.launch();
const p = await b.newPage();
const logs=[];
p.on("console", m => { const t=m.text(); if (t.startsWith("DBG")) logs.push(t); });
await p.goto("file:///home/r2d2/scratch_tw/wiki-dbg.html", { waitUntil: "load" });
await p.waitForTimeout(1500);
const names = await p.evaluate(() => $tw.wiki.allTitles().length);
console.log("titles:", names);
console.log("logs:", JSON.stringify(logs));
await b.close();
