import { createRequire } from "module";
const require = createRequire("/home/r2d2/Documents/AI_Master/MultiWikiServer-wikiwise/package.json");
const { chromium } = require("playwright-core");
const b = await chromium.launch();
const p = await b.newPage();
const errs=[]; const reqs=[];
p.on("console", m => { if(m.type()==="error") errs.push(m.text().slice(0,100)); });
p.on("request", r => { const u=r.url(); if(u.includes("/recipe/")&&!u.includes("plugin")) reqs.push(u.replace("http://localhost:5000","")); });
await p.goto("http://localhost:5000/wiki/bedienungsanleitung", { waitUntil: "networkidle" });
await p.waitForTimeout(2000);
const r = await p.evaluate(()=>({ start: $tw.wiki.tiddlerExists("Start"), titles: $tw.wiki.allTitles().length, recipe: $tw.wiki.getTiddlerText("$:/config/multiwikiclient/recipe") }));
console.log(JSON.stringify(r), "| reqs:", JSON.stringify(reqs), "| errs:", JSON.stringify(errs.slice(0,3)));
await b.close();
